/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

#ifndef TRIGGERANALYSISINTERFACES_TRIGGERANALYSISINTERFACESDICT_H
#define TRIGGERANALYSISINTERFACES_TRIGGERANALYSISINTERFACESDICT_H
	
// Local include(s):
#include "TriggerAnalysisInterfaces/ITrigGlobalEfficiencyCorrectionTool.h"

#endif // TRIGGERANALYSISINTERFACES_TRIGGERANALYSISINTERFACESDICT_H
