# Copyright (C) 2002-2019 CERN for the benefit of the ATLAS collaboration

#====================================================================
# Common file used by TOPQCommonSlimming.py
# Access variables with:
#   from DerivationFrameworkTop.TOPQCommonExtraContent import *
#====================================================================

#================================
# EXTRA VARIABLES - Data & MC
#================================
# Full list: DerivationFrameworkEGamma/python/ElectronsCPContent.py
TOPQExtraVariables_Electrons  = ["Electrons."
                                 + "etcone30."
                                 + "etcone40."
                                 ]

TOPQExtraVariables_ForwardElectrons  = ["ForwardElectrons."
                                        + "DeltaE."
                                        + "Eratio."
                                        + "Loose."
                                        + "Medium."
                                        + "OQ."
                                        + "Reta."
                                        + "Rhad."
                                        + "Rhad1."
                                        + "Rphi."
                                        + "Tight."
                                        + "author."
                                        + "caloClusterLinks."
                                        + "charge."
                                        + "deltaEta0."
                                        + "deltaEta1."
                                        + "deltaEta2."
                                        + "deltaEta3."
                                        + "deltaPhi0."
                                        + "deltaPhi1."
                                        + "deltaPhi2."
                                        + "deltaPhi3."
                                        + "deltaPhiFromLastMeasurement."
                                        + "deltaPhiRescaled0."
                                        + "deltaPhiRescaled1."
                                        + "deltaPhiRescaled2."
                                        + "deltaPhiRescaled3."
                                        + "e277."
                                        + "eta."
                                        + "f1."
                                        + "f1core."
                                        + "f3."
                                        + "f3core."
                                        + "fracs1."
                                        + "m."
                                        + "phi."
                                        + "pt."
                                        + "topoetcone20."
                                        + "topoetcone30."
                                        + "topoetcone40."
                                        + "topoetconeCorrBitset."
                                        + "topoetconecoreConeEnergyCorrection."
                                        + "trackParticleLinks."
                                        + "weta1."
                                        + "weta2."
                                        + "wtots1."
                                        ]

# Full list: DerivationFrameworkMuons/python/MuonsCPContent.py
TOPQExtraVariables_Muons = ["Muons."
                            + "etcone20."
                            + "etcone30."
                            + "etcone40."
                            ]

# Full list: DerivationFrameworkTau/python/TauJetsCPContent.py
TOPQExtraVariables_TauTracks = ["TauTracks.bdtScores"]

# Full list:
TOPQExtraVariables_CaloCalTopoClusters = ["CaloCalTopoClusters.CENTER_MAG"]

# Full list: DerivationFrameworkEGamma/python/ElectronsCPContent.py
# Full list: DerivationFrameworkEGamma/python/PhotonsCPContent.py
TOPQExtraVariables_egammaClusters = ["egammaClusters."
                                     + "BadChannelList."
                                     + "CellLink."
                                     + "ETA1CALOFRAME."
                                     + "PHI1CALOFRAME."
                                     + "altEta."
                                     + "altM."
                                     + "altPhi."
                                     + "emax_sampl."
                                     + "eta0."
                                     + "etamax_sampl."
                                     + "phi0."
                                     + "phi_sampl."
                                     + "phimax_sampl."
                                     + "rawE."
                                     + "rawEta."
                                     + "rawM."
                                     + "rawPhi."
                                     + "time."
                                     ]

# Full list: DerivationFrameworkJetEtMiss/python/AntiKt4EMTopoJetsCPContent.py
TOPQExtraVariables_AntiKt4EMTopoJets =  ["AntiKt4EMTopoJets."
                                         + "ActiveArea."
                                         + "AlgorithmType."
                                         + "BchCorrCell."
                                         + "CentroidR."
                                         + "Charge."
                                         + "ConstituentScale."
                                         + "DFCommonJets_Calib_eta."
                                         + "DFCommonJets_Calib_m."
                                         + "DFCommonJets_Calib_phi."
                                         + "DFCommonJets_Calib_pt."
                                         + "DFCommonJets_Jvt."
                                         + "DFCommonJets_QGTagger_NTracks."
                                         + "DFCommonJets_QGTagger_TracksC1."
                                         + "DFCommonJets_QGTagger_TracksWidth."
                                         + "DFCommonJets_QGTagger_truthjet_eta."
                                         + "DFCommonJets_QGTagger_truthjet_nCharged."
                                         + "DFCommonJets_QGTagger_truthjet_pt."
                                         + "DFCommonJets_passJvt."
                                         + "DFCommonJets_passOR."
                                         + "DetectorPhi."
                                         + "ECPSFraction."
                                         + "GhostMuonSegment."
                                         + "GhostTrackCount."
                                         + "GhostTrackPt."
                                         + "HighestJVFVtx."
                                         + "InputType."
                                         + "JVF."
                                         + "JetEMScaleMomentum_eta."
                                         + "JetEMScaleMomentum_m."
                                         + "JetEMScaleMomentum_phi."
                                         + "JetEMScaleMomentum_pt."
                                         + "JetEtaJESScaleMomentum_eta."
                                         + "JetEtaJESScaleMomentum_m."
                                         + "JetEtaJESScaleMomentum_phi."
                                         + "JetEtaJESScaleMomentum_pt."
                                         + "JetGhostArea."
                                         + "JetLCScaleMomentum_eta."
                                         + "JetLCScaleMomentum_m."
                                         + "JetLCScaleMomentum_phi."
                                         + "JetLCScaleMomentum_pt."
                                         + "JetPileupScaleMomentum_eta."
                                         + "JetPileupScaleMomentum_m."
                                         + "JetPileupScaleMomentum_phi."
                                         + "JetPileupScaleMomentum_pt."
                                         + "LArBadHVEnergyFrac."
                                         + "LArBadHVNCell."
                                         + "LeadingClusterCenterLambda."
                                         + "LeadingClusterPt."
                                         + "LeadingClusterSecondLambda."
                                         + "LeadingClusterSecondR."
                                         + "N90Constituents."
                                         + "OotFracClusters10."
                                         + "OotFracClusters5."
                                         + "OriginCorrected."
                                         + "OriginVertex."
                                         + "PileupCorrected."
                                         + "SizeParameter."
                                         + "SumPtTrkPt1000."
                                         + "TrackSumMass."
                                         + "TrackSumPt."
                                         + "TrackWidthPt500."
                                         + "WidthPhi."
                                         + "btaggingLink."
                                         + "selected."
                                         ]

# Full list: DerivationFrameworkJetEtMiss/python/AntiKt4EMTopoJetsCPContent.py
TOPQExtraVariables_AntiKt4EMPFlowJets_ForTOPQ1           =  ["AntiKt4EMPFlowJets."
                                                             + "LargeJetLabel."]
TOPQExtraVariables_AntiKt8EMPFlowJets_ForTOPQ1           =  ["AntiKt8EMPFlowJets."
                                                             + "ExKt2GASubJets."
                                                             + "ExKt2SubJets."]
TOPQExtraVariables_AntiKt8EMPFlowExKt2GASubJets_ForTOPQ1 =  ["AntiKt8EMPFlowExKt2GASubJets."
                                                             + "AlgorithmType."
                                                             + "ConeExclTausFinal."
                                                             + "GhostBHadronsFinal."
                                                             + "GhostBHadronsFinalCount."
                                                             + "GhostBHadronsFinalPt."
                                                             + "GhostCHadronsFinal."
                                                             + "GhostCHadronsFinalCount."
                                                             + "GhostCHadronsFinalPt."
                                                             + "GhostTrack."
                                                             + "GhostTrackCount."
                                                             + "GhostTrackPt."
                                                             + "InputType."
                                                             + "MatchedMuons."
                                                             + "MatchedTracks."
                                                             + "ExKtbb_maxsd0."
                                                             + "ExKtbb_av3sd0."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_pt."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_eta."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_phi."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_mass."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_vtxx."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_vtxy."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_vtxz."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_lxy."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_lxysig."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_lz."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_lzsig."
                                                             + "SoftBVrtClusterTool_MSVTight_Vertices_3dsig."]

# Full list: DerivationFrameworkJetEtMiss/python/AntiKt4EMPFlowJetsCPContent.py
TOPQExtraVariables_AntiKt4EMPFlowJets = ["AntiKt4EMPFlowJets."
                                         + "ActiveArea."
                                         + "AlgorithmType."
                                         + "AverageLArQF."
                                         + "BchCorrCell."
                                         + "CentroidR."
                                         + "Charge."
                                         + "ChargedPFOWidthPt500."
                                         + "ConstituentScale."
                                         + "DFCommonJets_QGTagger_NTracks."
                                         + "DFCommonJets_QGTagger_TracksC1."
                                         + "DFCommonJets_QGTagger_TracksWidth."
                                         + "DFCommonJets_QGTagger_truthjet_eta."
                                         + "DFCommonJets_QGTagger_truthjet_nCharged."
                                         + "DFCommonJets_QGTagger_truthjet_pt."
                                         + "DetectorPhi."
                                         + "GhostAntiKt2TrackJet."
                                         + "GhostAntiKt4TrackJet."
                                         + "GhostMuonSegment."
                                         + "GhostTrackCount."
                                         + "GhostTrackPt."
                                         + "HighestJVFVtx."
                                         + "InputType."
                                         + "JVF."
                                         + "JetEMScaleMomentum_eta."
                                         + "JetEMScaleMomentum_m."
                                         + "JetEMScaleMomentum_phi."
                                         + "JetEMScaleMomentum_pt."
                                         + "JetEtaJESScaleMomentum_eta."
                                         + "JetEtaJESScaleMomentum_m."
                                         + "JetEtaJESScaleMomentum_phi."
                                         + "JetEtaJESScaleMomentum_pt."
                                         + "JetGhostArea."
                                         + "JetPileupScaleMomentum_eta."
                                         + "JetPileupScaleMomentum_m."
                                         + "JetPileupScaleMomentum_phi."
                                         + "JetPileupScaleMomentum_pt."
                                         + "LArBadHVEnergyFrac."
                                         + "LArBadHVNCell."
                                         + "LArQuality."
                                         + "N90Constituents."
                                         + "NegativeE."
                                         + "OotFracClusters10."
                                         + "OotFracClusters5."
                                         + "OriginCorrected."
                                         + "OriginVertex."
                                         + "PileupCorrected."
                                         + "SizeParameter."
                                         + "SumPtChargedPFOPt1000."
                                         + "SumPtTrkPt1000."
                                         + "TrackSumMass."
                                         + "TrackSumPt."
                                         + "TrackWidthPt500."
                                         + "WidthPhi."
                                         + "btaggingLink."
                                         ]

# Full list: DerivationFrameworkJetEtMiss/python/AntiKt4EMTopoJetsCPContent.py
TOPQExtraVariables_AntiKtVR30Rmax4Rmin02TrackJets =  ["AntiKtVR30Rmax4Rmin02TrackJets_BTagging201810."
                                                      + "AlgorithmType."
                                                      + "ConeExclTausFinal."
                                                      + "ConstituentScale."
                                                      + "GhostBHadronsFinal."
                                                      + "GhostBHadronsFinalCount."
                                                      + "GhostBHadronsFinalPt."
                                                      + "GhostBHadronsInitial."
                                                      + "GhostBHadronsInitialCount."
                                                      + "GhostBHadronsInitialPt."
                                                      + "GhostBQuarksFinal."
                                                      + "GhostBQuarksFinalCount."
                                                      + "GhostBQuarksFinalPt."
                                                      + "GhostCHadronsFinal."
                                                      + "GhostCHadronsFinalCount."
                                                      + "GhostCHadronsFinalPt."
                                                      + "GhostCHadronsInitial."
                                                      + "GhostCHadronsInitialCount."
                                                      + "GhostCHadronsInitialPt."
                                                      + "GhostCQuarksFinal."
                                                      + "GhostCQuarksFinalCount."
                                                      + "GhostCQuarksFinalPt."
                                                      + "GhostHBosons."
                                                      + "GhostHBosonsCount."
                                                      + "GhostHBosonsPt."
                                                      + "GhostPartons."
                                                      + "GhostPartonsCount."
                                                      + "GhostPartonsPt."
                                                      + "GhostTQuarksFinal."
                                                      + "GhostTQuarksFinalCount."
                                                      + "GhostTQuarksFinalPt."
                                                      + "GhostTausFinal."
                                                      + "GhostTausFinalCount."
                                                      + "GhostTausFinalPt."
                                                      + "GhostTrack."
                                                      + "GhostTrackCount."
                                                      + "GhostTrackPt."
                                                      + "GhostTruth."
                                                      + "GhostTruthCount."
                                                      + "GhostTruthPt."
                                                      + "GhostWBosons."
                                                      + "GhostWBosonsCount."
                                                      + "GhostWBosonsPt."
                                                      + "GhostZBosons."
                                                      + "GhostZBosonsCount."
                                                      + "GhostZBosonsPt."
                                                      + "InputType."
                                                      + "JetConstitScaleMomentum_eta."
                                                      + "JetConstitScaleMomentum_m."
                                                      + "JetConstitScaleMomentum_phi."
                                                      + "JetConstitScaleMomentum_pt."
                                                      + "JetEMScaleMomentum_eta."
                                                      + "JetEMScaleMomentum_m."
                                                      + "JetEMScaleMomentum_phi."
                                                      + "JetEMScaleMomentum_pt."
                                                      + "JetGhostArea."
                                                      + "MatchedMuons."
                                                      + "MatchedTracks."
                                                      + "OriginVertex."
                                                      + "SizeParameter."
                                                      + "VariableRMassScale."
                                                      + "VariableRMinRadius."
                                                      ]

TOPQExtraVariables_AntiKtVR30Rmax4Rmin02TrackJets_201903 =  ["AntiKtVR30Rmax4Rmin02TrackJets_BTagging201903."
                                                             + "AlgorithmType."
                                                             + "ConeExclTausFinal."
                                                             + "ConstituentScale."
                                                             + "GhostBHadronsFinal."
                                                             + "GhostBHadronsFinalCount."
                                                             + "GhostBHadronsFinalPt."
                                                             + "GhostBHadronsInitial."
                                                             + "GhostBHadronsInitialCount."
                                                             + "GhostBHadronsInitialPt."
                                                             + "GhostBQuarksFinal."
                                                             + "GhostBQuarksFinalCount."
                                                             + "GhostBQuarksFinalPt."
                                                             + "GhostCHadronsFinal."
                                                             + "GhostCHadronsFinalCount."
                                                             + "GhostCHadronsFinalPt."
                                                             + "GhostCHadronsInitial."
                                                             + "GhostCHadronsInitialCount."
                                                             + "GhostCHadronsInitialPt."
                                                             + "GhostCQuarksFinal."
                                                             + "GhostCQuarksFinalCount."
                                                             + "GhostCQuarksFinalPt."
                                                             + "GhostHBosons."
                                                             + "GhostHBosonsCount."
                                                             + "GhostHBosonsPt."
                                                             + "GhostPartons."
                                                             + "GhostPartonsCount."
                                                             + "GhostPartonsPt."
                                                             + "GhostTQuarksFinal."
                                                             + "GhostTQuarksFinalCount."
                                                             + "GhostTQuarksFinalPt."
                                                             + "GhostTausFinal."
                                                             + "GhostTausFinalCount."
                                                             + "GhostTausFinalPt."
                                                             + "GhostTrack."
                                                             + "GhostTrackCount."
                                                             + "GhostTrackPt."
                                                             + "GhostTruth."
                                                             + "GhostTruthCount."
                                                             + "GhostTruthPt."
                                                             + "GhostWBosons."
                                                             + "GhostWBosonsCount."
                                                             + "GhostWBosonsPt."
                                                             + "GhostZBosons."
                                                             + "GhostZBosonsCount."
                                                             + "GhostZBosonsPt."
                                                             + "InputType."
                                                             + "JetConstitScaleMomentum_eta."
                                                             + "JetConstitScaleMomentum_m."
                                                             + "JetConstitScaleMomentum_phi."
                                                             + "JetConstitScaleMomentum_pt."
                                                             + "JetEMScaleMomentum_eta."
                                                             + "JetEMScaleMomentum_m."
                                                             + "JetEMScaleMomentum_phi."
                                                             + "JetEMScaleMomentum_pt."
                                                             + "JetGhostArea."
                                                             + "MatchedMuons."
                                                             + "MatchedTracks."
                                                             + "OriginVertex."
                                                             + "SizeParameter."
                                                             + "VariableRMassScale."
                                                             + "VariableRMinRadius."
                                                             ]

TOPQExtraVariables_BTagging_SecVtx_AntiKtVR30Rmax4Rmin02TrackJets_201903 = [
    "BTagging_AntiKtVR30Rmax4Rmin02Track_201903JFVtx."
    + "track_links."
    + "chi2."
    + "NDF.",
    "BTagging_AntiKtVR30Rmax4Rmin02Track_201903SecVtx."
    + "chiSquared."
    + "numberDoF."
    + "vertexType."
]

# Full list: DerivationFrameworkFlavourTag/python/BTaggingContent.py
TOPQExtraVariables_BTagging_AntiKtVR30Rmax4Rmin02Track =  ["BTagging_AntiKtVR30Rmax4Rmin02Track_201810."
                                                           + "IP3D_pb."
                                                           + "IP3D_pu."
                                                           + "SV1_pb."
                                                           + "SV1_pu."
                                                           ]

TOPQExtraVariables_BTagging_AntiKtVR30Rmax4Rmin02Track_201903 =  ["BTagging_AntiKtVR30Rmax4Rmin02Track_201903."
                                                                  + "IP3D_pb."
                                                                  + "IP3D_pu."
                                                                  + "SV1_pb."
                                                                  + "SV1_pu."
                                                                  + "SV1_vertices."
                                                                  + "SV1_badTracksIP."
                                                                  + "SV1_energyTrkInJet."
                                                                  + "SV1_L3d."
                                                                  + "SV1_Lxy."
                                                                  + "SV1_N2Tpair."
                                                                  + "SV1_NGTinSvx."
                                                                  + "SV1_deltaR."
                                                                  + "SV1_dstToMatLay."
                                                                  + "SV1_efracsvx."
                                                                  + "SV1_masssvx."
                                                                  + "SV1_significance3d."
                                                                  + "SV1_normdist."
                                                                  + "SV1_TrackParticleLinks."
                                                                  + "JetVertexCharge_discriminant."
                                                                  + "JetFitter_JFvertices."
                                                                  + "JetFitter_fittedCov."
                                                                  + "JetFitter_fittedPosition."
                                                                  + "JetFitter_tracksAtPVlinks."
                                                                  + "JetFitter_mass."
                                                                  + "JetFitter_massUncorr."
                                                                  + "JetFitter_nSingleTracks."
                                                                  + "JetFitter_significance3d."
                                                                  ]

# Full list: DerivationFrameworkFlavourTag/python/BTaggingContent.py
TOPQExtraVariables_BTagging_AntiKt4EMPFlow_201810 = ["BTagging_AntiKt4EMPFlow_201810."
                                                     + "BTagTrackToJetAssociator."
                                                     + "BTagTrackToJetAssociatorBB."
                                                     + "IP3D_pb."
                                                     + "IP3D_pu."
                                                     + "JetFitter_JFvertices."
                                                     + "JetFitter_tracksAtPVlinks."
                                                     + "MSV_badTracksIP."
                                                     + "MSV_vertices."
                                                     + "SV1_badTracksIP."
                                                     + "SV1_pb."
                                                     + "SV1_pu."
                                                     + "SV1_vertices."
                                                     ]

# Full list: DerivationFrameworkFlavourTag/python/BTaggingContent.py
TOPQExtraVariables_BTagging_AntiKt4EMPFlow_201903 = ["BTagging_AntiKt4EMPFlow_201903."
                                                     + "BTagTrackToJetAssociator."
                                                     + "BTagTrackToJetAssociatorBB."
                                                     + "IP3D_pb."
                                                     + "IP3D_pu."
                                                     + "JetFitter_JFvertices."
                                                     + "JetFitter_tracksAtPVlinks."
                                                     + "MSV_badTracksIP."
                                                     + "MSV_vertices."
                                                     + "SV1_badTracksIP."
                                                     + "SV1_pb."
                                                     + "SV1_pu."
                                                     + "SV1_vertices."
                                                     ]

# Full list: DerivationFrameworkFlavourTag/python/BTaggingContent.py
TOPQExtraVariables_BTagging_AntiKt4EMTopo_201810 = ["BTagging_AntiKt4EMTopo_201810."
                                                    + "JetVertexCharge_discriminant."
                                                    + "SV1_TrackParticleLinks."
                                                    ]

# Full list: DerivationFrameworkJetEtMiss/python/AntiKt10LCTopoTrimmedPtFrac5SmallR20JetsCPContent.py
TOPQExtraVariables_AntiKt10LCTopoTrimmedPtFrac5SmallR20Jets = ["AntiKt10LCTopoTrimmedPtFrac5SmallR20Jets."
                                                               + "ActiveArea."
                                                               + "ActiveArea4vec_eta."
                                                               + "ActiveArea4vec_m."
                                                               + "ActiveArea4vec_phi."
                                                               + "ActiveArea4vec_pt."
                                                               + "Charge."
                                                               + "DFCommonJets_Calib_eta."
                                                               + "DFCommonJets_Calib_m."
                                                               + "DFCommonJets_Calib_phi."
                                                               + "DFCommonJets_Calib_pt."
                                                               + "DetectorPhi."
                                                               + "Dip12."
                                                               + "Dip13."
                                                               + "Dip23."
                                                               + "DipExcl12."
                                                               + "EMFrac."
                                                               + "FoxWolfram1."
                                                               + "FoxWolfram3."
                                                               + "FoxWolfram4."
                                                               + "GhostAntiKt2TrackJetCount."
                                                               + "GhostAntiKt2TrackJetPt."
                                                               + "GhostAntiKt4TrackJet."
                                                               + "GhostAntiKt4TrackJetCount."
                                                               + "GhostAntiKt4TrackJetPt."
                                                               + "GhostMuonSegment."
                                                               + "GhostMuonSegmentCount."
                                                               + "GhostTrack."
                                                               + "GhostTrackCount."
                                                               + "GhostTrackPt."
                                                               + "JetEMScaleMomentum_eta."
                                                               + "JetEMScaleMomentum_m."
                                                               + "JetEMScaleMomentum_phi."
                                                               + "JetEMScaleMomentum_pt."
                                                               + "JetGhostArea."
                                                               + "Mu12."
                                                               + "PullMag."
                                                               + "PullPhi."
                                                               + "Pull_C00."
                                                               + "Pull_C01."
                                                               + "Pull_C10."
                                                               + "Pull_C11."
                                                               + "Sphericity."
                                                               + "Split34."
                                                               + "Tau1."
                                                               + "Tau2."
                                                               + "Tau3."
                                                               + "ThrustMaj."
                                                               + "ThrustMin."
                                                               + "Width."
                                                               + "WidthPhi."
                                                               + "ZCut23."
                                                               ]
TOPQExtraVariables_AntiKt10LCTopoJets = ["AntiKt10LCTopoJets."
                                         + "GhostVR30Rmax4Rmin02TrackJet_BTagging201810."
                                         + "GhostVR30Rmax4Rmin02TrackJet_BTagging201903"
]

# Full list: DerivationFrameworkInDet/python/InDetTrackParticlesCPContent.py
TOPQExtraVariables_InDetTrackParticles = ["InDetTrackParticles."
                                          + "TRTdEdx."
                                          + "particleHypothesis."
                                          + "pixeldEdx."
                                          + "radiusOfFirstHit."
                                          + "vx."
                                          + "vy."
                                          ]

TOPQExtraVariables_MET_Track = ["MET_Track."
                                + "source."
                                + "sumet."
                                ]

############################
# Extra variables HLT
############################
TOPQExtraVariables_BTag_HLT = ["HLT_xAOD__BTaggingContainer_HLTBjetFex.MV2c00_discriminant.MV2c10_discriminant.MV2c20_discriminant.BTagBtagToJetAssociator"]

TOPQExtraVariables_HLT_EFJet = ["HLT_xAOD__JetContainer_EFJet.eta.m.pt.phi"]

TOPQExtraVariables_HLT_SplitJet = ["HLT_xAOD__JetContainer_SplitJet.eta.m.pt.phi"]

#================================
# MC Only
#================================
TOPQExtraVariables_Muons_Truth = ["MuonTruthParticles.truthOrigin.truthType"]

TOPQExtraVariables_ForwardElectrons_Truth = ["ForwardElectrons.truthOrigin.truthType.truthParticleLink"]

TOPQExtraVariables_Taus_Truth = ["TauJets.IsTruthMatched.truthJetLink.truthParticleLink"]

TOPQExtraVariables_AntiKt4EMTopoJets_Truth =  ["AntiKt4EMTopoJets."
                                               + "ConeExclTausFinal."
                                               + "GhostBHadronsFinal."
                                               + "GhostBHadronsFinalCount."
                                               + "GhostBHadronsFinalPt."
                                               + "GhostBHadronsInitial."
                                               + "GhostBHadronsInitialCount."
                                               + "GhostBHadronsInitialPt."
                                               + "GhostBQuarksFinal."
                                               + "GhostBQuarksFinalCount."
                                               + "GhostBQuarksFinalPt."
                                               + "GhostCHadronsFinal."
                                               + "GhostCHadronsFinalCount."
                                               + "GhostCHadronsFinalPt."
                                               + "GhostCHadronsInitial."
                                               + "GhostCHadronsInitialCount."
                                               + "GhostCHadronsInitialPt."
                                               + "GhostCQuarksFinal."
                                               + "GhostCQuarksFinalCount."
                                               + "GhostCQuarksFinalPt."
                                               + "GhostHBosons."
                                               + "GhostHBosonsCount."
                                               + "GhostHBosonsPt."
                                               + "GhostPartons."
                                               + "GhostPartonsCount."
                                               + "GhostPartonsPt."
                                               + "GhostTQuarksFinal."
                                               + "GhostTQuarksFinalCount."
                                               + "GhostTQuarksFinalPt."
                                               + "GhostTausFinal."
                                               + "GhostTausFinalCount."
                                               + "GhostTausFinalPt."
                                               + "GhostTruth."
                                               + "GhostTruthAssociationLink."
                                               + "GhostTruthCount."
                                               + "GhostTruthPt."
                                               + "GhostWBosons."
                                               + "GhostWBosonsCount."
                                               + "GhostWBosonsPt."
                                               + "GhostZBosons."
                                               + "GhostZBosonsCount."
                                               + "GhostZBosonsPt."
                                               + "HadronConeExclTruthLabelID."
                                               + "PartonTruthLabelID."
                                               + "TruthLabelDeltaR_B."
                                               + "TruthLabelDeltaR_C."
                                               + "TruthLabelDeltaR_T."
                                               + "TruthLabelID."
                                               ]

TOPQExtraVariables_AntiKt4EMPFlowJets_Truth = ["AntiKt4EMPFlowJets."
                                               + "ConeExclBHadronsFinal."
                                               + "ConeExclCHadronsFinal."
                                               + "ConeExclTausFinal."
                                               + "ConeTruthLabelID."
                                               + "GhostBHadronsFinal."
                                               + "GhostBHadronsFinalCount."
                                               + "GhostBHadronsFinalPt."
                                               + "GhostBHadronsInitial."
                                               + "GhostBHadronsInitialCount."
                                               + "GhostBHadronsInitialPt."
                                               + "GhostBQuarksFinal."
                                               + "GhostBQuarksFinalCount."
                                               + "GhostBQuarksFinalPt."
                                               + "GhostCHadronsFinal."
                                               + "GhostCHadronsFinalCount."
                                               + "GhostCHadronsFinalPt."
                                               + "GhostCHadronsInitial."
                                               + "GhostCHadronsInitialCount."
                                               + "GhostCHadronsInitialPt."
                                               + "GhostCQuarksFinal."
                                               + "GhostCQuarksFinalCount."
                                               + "GhostCQuarksFinalPt."
                                               + "GhostHBosons."
                                               + "GhostHBosonsCount."
                                               + "GhostHBosonsPt."
                                               + "GhostPartons."
                                               + "GhostPartonsCount."
                                               + "GhostPartonsPt."
                                               + "GhostTQuarksFinal."
                                               + "GhostTQuarksFinalCount."
                                               + "GhostTQuarksFinalPt."
                                               + "GhostTausFinal."
                                               + "GhostTausFinalCount."
                                               + "GhostTausFinalPt."
                                               + "GhostTruth."
                                               + "GhostTruthAssociationLink."
                                               + "GhostTruthCount."
                                               + "GhostTruthPt."
                                               + "GhostWBosons."
                                               + "GhostWBosonsCount."
                                               + "GhostWBosonsPt."
                                               + "GhostZBosons."
                                               + "GhostZBosonsCount."
                                               + "GhostZBosonsPt."
                                               + "HadronConeExclTruthLabelID."
                                               + "PartonTruthLabelID."
                                               + "TruthLabelDeltaR_B."
                                               + "TruthLabelDeltaR_C."
                                               + "TruthLabelDeltaR_T."
                                               + "TruthLabelID."
                                               ]

TOPQExtraVariables_AntiKt10LCTopoTrimmedPtFrac5SmallR20Jets_Truth = ["AntiKt10LCTopoTrimmedPtFrac5SmallR20Jets."
                                                                     + "GhostBHadronsFinal."
                                                                     + "GhostBHadronsFinalCount."
                                                                     + "GhostBHadronsFinalPt."
                                                                     + "GhostBHadronsInitial."
                                                                     + "GhostBHadronsInitialCount."
                                                                     + "GhostBHadronsInitialPt."
                                                                     + "GhostBQuarksFinal."
                                                                     + "GhostBQuarksFinalCount."
                                                                     + "GhostBQuarksFinalPt."
                                                                     + "GhostCHadronsFinal."
                                                                     + "GhostCHadronsFinalCount."
                                                                     + "GhostCHadronsFinalPt."
                                                                     + "GhostCHadronsInitial."
                                                                     + "GhostCHadronsInitialCount."
                                                                     + "GhostCHadronsInitialPt."
                                                                     + "GhostCQuarksFinal."
                                                                     + "GhostCQuarksFinalCount."
                                                                     + "GhostCQuarksFinalPt."
                                                                     + "GhostHBosons."
                                                                     + "GhostHBosonsCount."
                                                                     + "GhostHBosonsPt."
                                                                     + "GhostMuonSegment."
                                                                     + "GhostMuonSegmentCount."
                                                                     + "GhostPartons."
                                                                     + "GhostPartonsCount."
                                                                     + "GhostPartonsPt."
                                                                     + "GhostTQuarksFinal."
                                                                     + "GhostTQuarksFinalCount."
                                                                     + "GhostTQuarksFinalPt."
                                                                     + "GhostTausFinal."
                                                                     + "GhostTausFinalCount."
                                                                     + "GhostTausFinalPt."
                                                                     + "GhostTruth."
                                                                     + "GhostTruthCount."
                                                                     + "GhostTruthPt."
                                                                     + "GhostWBosons."
                                                                     + "GhostWBosonsCount."
                                                                     + "GhostWBosonsPt."
                                                                     + "GhostZBosons."
                                                                     + "GhostZBosonsCount."
                                                                     + "GhostZBosonsPt."
                                                                     + "TruthLabelDeltaR_B."
                                                                     + "TruthLabelDeltaR_C."
                                                                     + "TruthLabelDeltaR_T."
                                                                     ]

#===========================================
# COLLECTIONS AT TRUTH LEVEL
#===========================================
TOPQExtraVariables_AntiKt4TruthJets = ["AntiKt4TruthJets."
                                       + "ActiveArea."
                                       + "ActiveArea4vec_eta."
                                       + "ActiveArea4vec_m."
                                       + "ActiveArea4vec_phi."
                                       + "ActiveArea4vec_pt."
                                       + "AlgorithmType."
                                       + "ConeExclBHadronsFinal."
                                       + "ConeExclCHadronsFinal."
                                       + "ConeExclTausFinal."
                                       + "ConstituentScale."
                                       + "GhostBHadronsFinal."
                                       + "GhostBHadronsFinalCount."
                                       + "GhostBHadronsFinalPt."
                                       + "GhostBHadronsInitial."
                                       + "GhostBHadronsInitialCount."
                                       + "GhostBHadronsInitialPt."
                                       + "GhostBQuarksFinal."
                                       + "GhostBQuarksFinalCount."
                                       + "GhostBQuarksFinalPt."
                                       + "GhostCHadronsFinal."
                                       + "GhostCHadronsFinalCount."
                                       + "GhostCHadronsFinalPt."
                                       + "GhostCHadronsInitial."
                                       + "GhostCHadronsInitialCount."
                                       + "GhostCHadronsInitialPt."
                                       + "GhostCQuarksFinal."
                                       + "GhostCQuarksFinalCount."
                                       + "GhostCQuarksFinalPt."
                                       + "GhostHBosons."
                                       + "GhostHBosonsCount."
                                       + "GhostHBosonsPt."
                                       + "GhostPartons."
                                       + "GhostPartonsCount."
                                       + "GhostPartonsPt."
                                       + "GhostTQuarksFinal."
                                       + "GhostTQuarksFinalCount."
                                       + "GhostTQuarksFinalPt."
                                       + "GhostTausFinal."
                                       + "GhostTausFinalCount."
                                       + "GhostTausFinalPt."
                                       + "GhostWBosons."
                                       + "GhostWBosonsCount."
                                       + "GhostWBosonsPt."
                                       + "GhostZBosons."
                                       + "GhostZBosonsCount."
                                       + "GhostZBosonsPt."
                                       + "InputType."
                                       + "JetConstitScaleMomentum_eta."
                                       + "JetConstitScaleMomentum_m."
                                       + "JetConstitScaleMomentum_phi."
                                       + "JetConstitScaleMomentum_pt."
                                       + "JetGhostArea."
                                       + "SizeParameter."
                                       + "TruthLabelDeltaR_B."
                                       + "TruthLabelDeltaR_C."
                                       + "TruthLabelDeltaR_T."
                                       + "Width."
                                       + "WidthPhi."
                                       ]

TOPQExtraVariables_AntiKt4TruthDressedWZJets = ["AntiKt4TruthDressedWZJets."
                                                + "ActiveArea."
                                                + "ActiveArea4vec_eta."
                                                + "ActiveArea4vec_m."
                                                + "ActiveArea4vec_phi."
                                                + "ActiveArea4vec_pt."
                                                + "AlgorithmType."
                                                + "ConeExclBHadronsFinal."
                                                + "ConeExclCHadronsFinal."
                                                + "ConeExclTausFinal."
                                                + "ConstituentScale."
                                                + "GhostBHadronsFinalPt."
                                                + "GhostBHadronsInitial."
                                                + "GhostBHadronsInitialCount."
                                                + "GhostBHadronsInitialPt."
                                                + "GhostBQuarksFinal."
                                                + "GhostBQuarksFinalCount."
                                                + "GhostBQuarksFinalPt."
                                                + "GhostCHadronsFinal."
                                                + "GhostCHadronsFinalCount."
                                                + "GhostCHadronsFinalPt."
                                                + "GhostCHadronsInitial."
                                                + "GhostCHadronsInitialCount."
                                                + "GhostCHadronsInitialPt."
                                                + "GhostCQuarksFinal."
                                                + "GhostCQuarksFinalCount."
                                                + "GhostCQuarksFinalPt."
                                                + "GhostHBosons."
                                                + "GhostHBosonsCount."
                                                + "GhostHBosonsPt."
                                                + "GhostPartons."
                                                + "GhostPartonsCount."
                                                + "GhostPartonsPt."
                                                + "GhostTQuarksFinal."
                                                + "GhostTQuarksFinalCount."
                                                + "GhostTQuarksFinalPt."
                                                + "GhostTausFinal."
                                                + "GhostTausFinalCount."
                                                + "GhostTausFinalPt."
                                                + "GhostWBosons."
                                                + "GhostWBosonsCount."
                                                + "GhostWBosonsPt."
                                                + "GhostZBosons."
                                                + "GhostZBosonsCount."
                                                + "GhostZBosonsPt."
                                                + "InputType."
                                                + "JetConstitScaleMomentum_eta."
                                                + "JetConstitScaleMomentum_m."
                                                + "JetConstitScaleMomentum_phi."
                                                + "JetConstitScaleMomentum_pt."
                                                + "JetGhostArea."
                                                + "SizeParameter."
                                                + "TruthLabelDeltaR_B."
                                                + "TruthLabelDeltaR_C."
                                                + "TruthLabelDeltaR_T."
                                                + "Width."
                                                + "WidthPhi."
                                                ]

TOPQExtraVariables_AntiKt4TruthWZJets = ["AntiKt4TruthWZJets."
                                         + "ActiveArea."
                                         + "ActiveArea4vec_eta."
                                         + "ActiveArea4vec_m."
                                         + "ActiveArea4vec_phi."
                                         + "ActiveArea4vec_pt."
                                         + "AlgorithmType."
                                         + "ConeExclBHadronsFinal."
                                         + "ConeExclCHadronsFinal."
                                         + "ConeExclTausFinal."
                                         + "ConstituentScale."
                                         + "GhostBHadronsFinalPt."
                                         + "GhostBHadronsInitial."
                                         + "GhostBHadronsInitialCount."
                                         + "GhostBHadronsInitialPt."
                                         + "GhostBQuarksFinal."
                                         + "GhostBQuarksFinalCount."
                                         + "GhostBQuarksFinalPt."
                                         + "GhostCHadronsFinal."
                                         + "GhostCHadronsFinalCount."
                                         + "GhostCHadronsFinalPt."
                                         + "GhostCHadronsInitial."
                                         + "GhostCHadronsInitialCount."
                                         + "GhostCHadronsInitialPt."
                                         + "GhostCQuarksFinal."
                                         + "GhostCQuarksFinalCount."
                                         + "GhostCQuarksFinalPt."
                                         + "GhostHBosons."
                                         + "GhostHBosonsCount."
                                         + "GhostHBosonsPt."
                                         + "GhostPartons."
                                         + "GhostPartonsCount."
                                         + "GhostPartonsPt."
                                         + "GhostTQuarksFinal."
                                         + "GhostTQuarksFinalCount."
                                         + "GhostTQuarksFinalPt."
                                         + "GhostTausFinal."
                                         + "GhostTausFinalCount."
                                         + "GhostTausFinalPt."
                                         + "GhostWBosons."
                                         + "GhostWBosonsCount."
                                         + "GhostWBosonsPt."
                                         + "GhostZBosons."
                                         + "GhostZBosonsCount."
                                         + "GhostZBosonsPt."
                                         + "InputType."
                                         + "JetConstitScaleMomentum_eta."
                                         + "JetConstitScaleMomentum_m."
                                         + "JetConstitScaleMomentum_phi."
                                         + "JetConstitScaleMomentum_pt."
                                         + "JetGhostArea."
                                         + "SizeParameter."
                                         + "TruthLabelDeltaR_B."
                                         + "TruthLabelDeltaR_C."
                                         + "TruthLabelDeltaR_T."
                                         + "Width."
                                         + "WidthPhi."
                                         ]

TOPQExtraVariables_TruthEvents = ["TruthEvents."
                                  + "PDFID1."
                                  + "PDFID2."
                                  + "PDGID1."
                                  + "PDGID2."
                                  + "Q."
                                  + "X1."
                                  + "X2."
                                  + "XF1."
                                  + "XF2."
                                  + "beamParticle1Link."
                                  + "beamParticle2Link."
                                  + "crossSection."
                                  + "crossSectionError."
                                  + "signalProcessVertexLink."
                                  + "truthParticleLinks."
                                  + "truthVertexLinks."
                                  + "weights."
                                  ]

TOPQExtraVariables_TruthParticles = ["TruthParticles."
                                     + "TopHadronOriginFlag."
                                     + "barcode."
                                     + "classifierParticleOrigin."
                                     + "classifierParticleOutCome."
                                     + "classifierParticleType."
                                     + "decayVtxLink."
                                     + "dressedPhoton."
                                     + "e."
                                     + "m."
                                     + "pdgId."
                                     + "polarizationPhi."
                                     + "polarizationTheta."
                                     + "prodVtxLink."
                                     + "px."
                                     + "py."
                                     + "pz."
                                     + "status."
                                     ]

TOPQExtraVariables_TruthVertices = ["TruthVertices."
                                    + "barcode."
                                    + "id."
                                    + "incomingParticleLinks."
                                    + "outgoingParticleLinks."
                                    + "t."
                                    + "x."
                                    + "y."
                                    + "z."
                                    ]

TOPQExtraVariables_MET_TruthRegions = ["MET_TruthRegions."
                                       + "mpx."
                                       + "mpy."
                                       + "name."
                                       + "source."
                                       + "sumet."
                                       ]
