# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

""" MinBias slice specific flags  """

from AthenaCommon.JobProperties import JobProperty, JobPropertyContainer, jobproperties
from TriggerMenuPython.CommonSliceHelper import CommonSliceHelper, AllowedList

__author__  = 'R. Kwee, B. Demirkoz, T.Bold, T.Kohno, W. H. Bell'
__version__="$Revision: 1.18 $"
__doc__="Minimum Bias slice specific flags  "

#
# This file should not be modified without consulting 
# the Minimum Bias trigger slice coordinator.
#
# The Minimum Bias trigger slice is documented at:
# https://twiki.cern.ch/twiki/bin/view/Atlas/MinbiasTrigger
#

#===================================================================

_flags = [] 

class signatures(JobProperty):
    """ signatures in MinBias slice """
    statusOn=True
    allowedTypes=['list']
    allowedValues = AllowedList(['mbSpTrk',
                                 'mbSpLowPtTrk',
                                 'mbTrtTrk',
                                 "mbSp_oneD",
                                 "mbSp_fwd",
                                 "mbSp",
                                 'mbMbts_1_NoCut_Time',
                                 'mbMbts_1_NoAlg',
                                 'mbMbts_2_NoAlg',
                                 'mbMbts_1',
                                 'mbMbts_2_NoCut_Time',
                                 'mbMbts_2_Monitoring',
                                 'VdM_Monitoring',
                                 'mbMbts_2',
                                 'mbMbts_2_eff',
                                 'mbMbts_1_1_NoCut_Time',
                                 'mbMbts_1_1', 'mbMbts_1_1_overlay', 'mbMbts_ZB_overlay',
                                 'mbMbts_2_2',
                                 'mbMbts_2_2_eff_HI',
                                 'mbMbts_2_2_unpaired_iso',
                                 'mbMbts_2_2_eff_unpaired_iso_HI',
                                 'mbMbts_3_3',
                                 'mbMbts_3_3_eff_HI',
                                 'mbMbts_3_3_unpaired_iso',
                                 'mbMbts_3_3_eff_unpaired_iso_HI',
                                 'mbMbts_4_4',
                                 'mbMbts_4_4_eff_HI',
                                 'mbMbts_4_4_unpaired_iso',
                                 'mbMbts_4_4_eff_unpaired_iso_HI',
                                 'mbRmMbts_1',
                                 'mbRmMbts_2',
                                 'mbRmMbts_1_1',
                                 'mbRmMbts_1_NoCut_Time',
                                 'mbRmMbts_2_NoCut_Time',
                                 'mbRmMbts_1_1_NoCut_Time',
                                 'mb_RM_calib',
                                 'mb_BM_calib',
                                 'mb_LD_calib',
                                 'mb_M1_calib',
                                 'mb_M2_calib',
                                 'mb_ZC_calib',
                                 'mb_MU',
                                 'mbSpTrkMh_MB1',
                                 'mbSpTrkMh_MB2',
                                 'mbSpTrkVtxMh',
                                 'mbSpTrkVtxMh_eff',
                                 'mbSpTrkVtxMh_medium',
                                 'mbSpTrkVtxMh_medium_eff',
                                 'mbSpTrkVtxMh_tight',
                                 'mbSpTrkVtxMh_tight_eff',
				 #pPb high-mult triggers
                                 'mbSpTrkVtxMh_hip_trk100_L1TE10', 'mbSpTrkVtxMh_hip_trk110_L1TE10', 'mbSpTrkVtxMh_hip_trk120_L1TE10',
                                 'mbSpTrkVtxMh_hip_trk130_L1TE10',
                                 'mbSpTrkVtxMh_hip_trk140_L1TE20', 'mbSpTrkVtxMh_hip_trk150_L1TE20', 'mbSpTrkVtxMh_hip_trk155_L1TE20',
                                 'mbSpTrkVtxMh_hip_trk160_L1TE20',
                                 'mbSpTrkVtxMh_hip_trk170_L1TE35', 'mbSpTrkVtxMh_hip_trk175_L1TE35', 'mbSpTrkVtxMh_hip_trk180_L1TE35',
                                 'mbSpTrkVtxMh_hip_trk190_L1TE35',
                                 'mbSpTrkVtxMh_hip_trk140_L1TE50', 'mbSpTrkVtxMh_hip_trk150_L1TE50', 'mbSpTrkVtxMh_hip_trk155_L1TE50',
                                 'mbSpTrkVtxMh_hip_trk160_L1TE50',
                                 'mbSpTrkVtxMh_hip_trk170_L1TE50', 'mbSpTrkVtxMh_hip_trk175_L1TE50', 'mbSpTrkVtxMh_hip_trk180_L1TE50',
                                 'mbSpTrkVtxMh_hip_trk190_L1TE50',
			         'mbSpTrkVtxMh_hip_trk180_L1TE65', 'mbSpTrkVtxMh_hip_trk190_L1TE65', 'mbSpTrkVtxMh_hip_trk200_L1TE65', 
                                 'mbSpTrkVtxMh_hip_trk210_L1TE65',
                                 'mbSpTrkVtxMh_hip_trk175_L1MBTS',
                                 'mbSpTrkVtxMh_hip_trk220_L1TE65', 'mbSpTrkVtxMh_hip_trk225_L1TE65', 'mbSpTrkVtxMh_hip_trk230_L1TE65',
                                 'mbSpTrkVtxMh_hip_trk240_L1TE65', 'mbSpTrkVtxMh_hip_trk245_L1TE65',
                                 'mbSpTrkVtxMh_hip_trk200_L1TE90', 'mbSpTrkVtxMh_hip_trk210_L1TE90',
                                 'mbSpTrkVtxMh_hip_trk220_L1TE90', 'mbSpTrkVtxMh_hip_trk230_L1TE90',
                                 'mbSpTrkVtxMh_hip_trk240_L1TE90', 'mbSpTrkVtxMh_hip_trk260_L1TE90',
				 'mbSpTrkVtxMh_hip_trk140_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_hip_trk160_L1TE50_pileupSup', 'mbSpTrkVtxMh_hip_trk180_L1TE50_pileupSup', 'mbSpTrkVtxMh_hip_trk200_L1TE65_pileupSup',
                                 'mbSpTrkVtxMh_hip_trk240_L1TE90_pileupSup', 'mbSpTrkVtxMh_hip_trk260_L1TE90_pileupSup',
                                 #pp HMT
				 'mbSpTrkVtxMh_pp_trk50_L1TE10',
                                 'mbSpTrkVtxMh_pp_trk50_L1MBTS', 'mbSpTrkVtxMh_pp_trk50_L1TE0',
                                 'mbSpTrkVtxMh_pp_trk60_L1TE10',
                                 'mbSpTrkVtxMh_pp_trk60_L1MBTS', 'mbSpTrkVtxMh_pp_trk60_L1TE0',
                                 'mbSpTrkVtxMh_pp_trk70_L1TE10', 'mbSpTrkVtxMh_pp_trk70_L1TE0',
                                 'mbSpTrkVtxMh_pp_trk70_L1TE20',
                                 'mbSpTrkVtxMh_pp_trk80_L1TE10', 'mbSpTrkVtxMh_pp_trk80_L1TE0',
                                 'mbSpTrkVtxMh_pp_trk80_L1TE20',
                                 'mbSpTrkVtxMh_pp_trk90_L1TE10', 'mbSpTrkVtxMh_pp_trk90_L1TE0',
                                 'mbSpTrkVtxMh_pp_trk100_L1TE10', 'mbSpTrkVtxMh_pp_trk110_L1TE10', 'mbSpTrkVtxMh_pp_trk120_L1TE10', 'mbSpTrkVtxMh_pp_trk130_L1TE10',
                                 'mbSpTrkVtxMh_pp_trk90_L1TE20',
                                 'mbSpTrkVtxMh_pp_trk100_L1TE20', 'mbSpTrkVtxMh_pp_trk100_L1TE0',
                                 'mbSpTrkVtxMh_pp_trk100_L1TE35',
                                 'mbSpTrkVtxMh_pp_trk110_L1TE20',
                                 'mbSpTrkVtxMh_pp_trk110_L1TE35',
                                 'mbSpTrkVtxMh_pp_trk120_L1TE20',
                                 'mbSpTrkVtxMh_pp_trk120_L1TE35',
                                 'mbSpTrkVtxMh_pp_trk130_L1TE20',
                                 'mbSpTrkVtxMh_pp_trk130_L1TE35',
				#pileupSup
				 'mbSpTrkVtxMh_pp_trk30_L1TE0_pileupSup', 'mbSpTrkVtxMh_pp_trk30_L1TE10_pileupSup', 'mbSpTrkVtxMh_pp_trk30_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk50_L1TE10_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk50_L1MBTS_pileupSup', 'mbSpTrkVtxMh_pp_trk50_L1TE0_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk60_L1TE10_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk60_L1MBTS_pileupSup', 'mbSpTrkVtxMh_pp_trk60_L1TE0_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk70_L1TE10_pileupSup', 'mbSpTrkVtxMh_pp_trk70_L1TE0_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk70_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk80_L1TE10_pileupSup', 'mbSpTrkVtxMh_pp_trk80_L1TE0_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk80_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk90_L1TE10_pileupSup', 'mbSpTrkVtxMh_pp_trk90_L1TE0_pileupSup', 'mbSpTrkVtxMh_pp_trk100_L1TE0_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk100_L1TE10_pileupSup', 'mbSpTrkVtxMh_pp_trk110_L1TE10_pileupSup', 'mbSpTrkVtxMh_pp_trk120_L1TE10_pileupSup', 
                                 'mbSpTrkVtxMh_pp_trk130_L1TE10_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk90_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk100_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk100_L1TE35_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk110_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk110_L1TE35_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk120_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk120_L1TE35_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk130_L1TE20_pileupSup',
                                 'mbSpTrkVtxMh_pp_trk130_L1TE35_pileupSup',
                                 #'mb_ZD_calib',
                                 'mbBcm',
                                 'mbRndm',
                                 'mbLucid',
                                 'mbZdc',
                                 'mb_TGC_calib',
                                 'mbMbts_1_TGC_calib',
                                 'mbMbts_2_TGC_calib',
                                 'mbMbts_1_1_TGC_calib',
                                 'mbSpTrk_L1J20_MV',
                                 'always',
                                 'mbSpTrk_cosmic', # (with pass through at EF)
                                 'mbTrtTrk_cosmic', # (with pass through at EF)
                                 'mbMbts_1_NoCut_Time_cosmic',
                                 'mbMbts_2_NoCut_Time_cosmic',
                                 'mbMbts_1_1_NoCut_Time_cosmic',
                                 'mb_RM_calib_cosmic',
                                 'mb_BM_calib_cosmic',
                                 'mb_LD_calib_cosmic',
                                 'mb_ZC_calib_cosmic',
                                 'mb_M2_calib_cosmic',
                                 'mb_MU_cosmic',
                                 'mbBcm_cosmic', # (low importance)
                                 'mbRndm_cosmic', # (low importance)
                                 'mbLucid_cosmic', # (low importance)
                                 'mbZdc_cosmic', #  (low importance)
                                 'mb_TGC_calib_cosmic',
                                 'mbMbts_1_TGC_calib_cosmic',
                                 'mbMbts_2_TGC_calib_cosmic',
                                 'mbMbts_1_1_TGC_calib_cosmic',
                                 'mbRmMbts_1_cosmic',
                                 'mbRmMbts_2_cosmic',
                                 'mb_BX0_calib',
                                 'mb_BX1_calib',
                                 'mbMbts_1_BX0',
                                 'mbMbts_1_BX1',
                                 'mbMbts_2_BX0',
                                 'mbMbts_2_BX1',
                                 'mbTrtTrk_BX0',
                                 'mbTrtTrk_BX1',
                                 'mbSpTrk_BX0',
                                 'mbSpTrk_BX1',
                                 'mb_allL1_calib',
                                 'mbMbts_1_1_BX0',
                                 'mbMbts_1_1_BX1',
                                 'mbMbts_1_NoCut_Time_BX0',
                                 'mbMbts_1_NoCut_Time_BX1',
                                 'mbMbts_2_NoCut_Time_BX0',
                                 'mbMbts_2_NoCut_Time_BX1',
                                 'mbMbts_1_1_NoCut_Time_BX0',
                                 'mbMbts_1_1_NoCut_Time_BX1',
                                 'mbSpBg_unpaired',
                                 'mbSpTrk_unpaired',
                                 'mbSpTrk_empty',
                                 'mbTrtTrk_unpaired',
                                 'mbRmMbts_1_unpaired',
                                 'mbRmMbts_1_NoCut_Time_unpaired',
                                 'mbMbts_1_NoCut_Time_unpaired',
                                 'mb_RM_calib_unpaired',
                                 'mb_M1_calib_unpaired',
                                 'mb_M2_calib_unpaired',
                                 'mb_M4_4_calib',
                                 'mb_M4_4_calib_firstempty',
                                 'mb_M4_4_calib_cosmic',
                                 'mb_M1_calib_cosmic', 
                                 'mb_M4_4_calib_unpaired',
                                 'mb_M2_calib_unpaired',
                                 'mb_M1_calib_unpaired', 
                                 'mb_LD_A_calib_unpaired',
                                 'mb_LD_C_calib_unpaired',
                                 'mbLucid_eff_unpaired_iso',
                                 'mbLucid_eff_empty',
                                 'mbTE20_eff',
                                 'mb_RM_eff',
                                 'mb_RM_eff_unpaired',
                                 'mb_RM_eff_cosmic',
                                 'mb_M1_eff',
                                 'mb_M1_eff_unpaired',
                                 'mb_M1_eff_cosmic', 
                                 'mb_M2_eff',
                                 'mb_M2_eff_unpaired',
                                 'mb_M4_4_eff',
                                 'mb_M4_4_eff_firstempty',
                                 'mb_M4_4_eff_unpaired',
                                 'mb_LD_A_eff_unpaired',
                                 'mb_LD_C_eff_unpaired',
                                 'mb_ZC_eff',
                                 'mb_ZC_eff_unpaired',
                                 'mb_BM_eff',
                                 'mb_BCM_HT_eff','mb_BCM_Wide_eff','mb_BCM_AC_CA_eff',
                                 'mb_LD_eff',
				 'L1LHCF_NoAlg',
                                 'mbZdc_and_cosmic_NoAlg','mbZdc_and_NoAlg',
                                 'mbZdc_and_Mbts_1_1',
                                 'mbZdc_and_Mbts_2_2',
                                 'mbZdc_a_c_Mbts_1_1',
                                 'mbZdc_a_c_Mbts_2_2',
                                 'mbZdc_a_cosmic','mbZdc_a',
                                 'mbZdc_c_cosmic','mbZdc_c',
                                 'mbZdc_a_c_cosmic_NoAlg',
                                 'mbZdc_a_c_NoAlg', 'mbZdc_a_c_overlay_NoAlg',
                                 'L1MBTS_1_1_overlay_NoAlg',
                                 'mbZdc_a_c_L1TE50_NoAlg',
                                 'mbZdc_a_c_eff_HI',
                                 'mbZdc_a_c_eff_unpaired_iso_HI',
                                 'L1ZDC_A_C_BGRP7_NoAlg',
                                 'mbLucid_comm_cosmic','mbLucid_comm',
                                 'mbLucid_a_cosmic','mbLucid_a',
                                 'mbLucid_c_cosmic','mbLucid_c',
                                 'mbLucid_a_c_cosmic','mbLucid_a_c',
                                 'mbLucid_a_c_unpaired',
                                 'mbBcm_AtoC_cosmic','mbBcm_AtoC',
                                 'mbBcm_ht_cosmic','mbBcm_ht',
                                 'mbBcm_mul_1_cosmic','mbBcm_mul_1',
                                 'mbBcm_mul_2_cosmic','mbBcm_mul_2',
                                 'mbBcm_mul_3_cosmic','mbBcm_mul_3',
                                 'mbBcm_mul_4_cosmic','mbBcm_mul_4',
                                 'mbBcm_mul_5_cosmic','mbBcm_mul_5',
                                 'mbBcm_mul_6_cosmic','mbBcm_mul_6',
                                 'mbMbts_a','mbMbts_c',
                                 'mbMbts_1_unpaired1','mbMbts_1_unpaired2',
                                 'mbMbts_2_unpaired1','mbMbts_2_unpaired2',
                                 'mbMbts_1_1_unpaired1','mbMbts_1_1_unpaired2',
                                 'mbMbts_4_4_unpaired1','mbMbts_4_4_unpaired2',
                                 'mbMbts_1_1_unpaired', 'mbMbts_1_1_unpaired_iso',
                                 'mbMbts_1_1_firstempty',
                                 'mbMbts_1_firstempty','mbMbts_2_firstempty',
                                 'mbMbts_1_empty','mbMbts_2_empty','zerobias_noAlg',
                                 'mbMbts_1_empty_NoAlg',
                                 'mbMbts_1_1_unpaired_iso_NoAlg','mbMbts_4_4_unpaired_iso_NoAlg',
                                 'rd1_empty_noAlg',
                                 'L1TRT_NoAlg',
                                 'zerobias_NoAlg', 'zerobias_Overlay_NoAlg', 'zerobias_Overlay_L2mbMbts',
                                 'rd1_empty_NoAlg',
                                 'rd0_empty_NoAlg',
                                 'rd0_filled_NoAlg',
                                 'rd0_unpaired_iso_NoAlg',
                                 'mbLucidComm_cosmic_NoAlg',
                                 'mbLucid_eff',
                                 'mbLucid_A_eff_unpaired',
                                 'mbLucid_C_eff_unpaired',
                                 'mbZdc_eff',
                                 'mbZdc_eff_unpaired',
                                 'mbRd0_eff_unpaired',
                                 'mbRmMbts_1_NoCut_Time', 
                                 'mbRd1_eff',
                                 'mbRd0_eff_empty',
                                 'mbMbts_1_eff_unpaired',
                                 'mbMbts_2_Monitoring',
                                 'mbRd0_Monitoring',
                                 'mbMbts_2_SpTrkMh',
                                 'mbMbts_2_SpTrkMh120',
                                 'mbMbts_1_eff',
                                 'mbLucid_A_eff_unpaired_iso',
                                 'mbLucid_C_eff_unpaired_iso',
                                 'mbZdc_eff_unpaired_iso',
                                 'mbRd0_eff_unpaired_iso',
                                 'mbSpTrk_unpaired_iso',
                                 'mbSpBg_unpaired_iso',
                                 'mbMbts_1_eff_unpaired_iso',
                                 'mbMbts_2_eff_unpaired_iso',
                                 'mbMbts_2_unpaired_iso',
                                 #HI chains
                                 'mbSp_HI',
                                 'mbSp_HI_L1BGRP1',
                                 'mbSpTrk_L1ZDC',
                                 'mbSpTrk_L1ZDC_A',
                                 'mbSpTrk_L1ZDC_C',
                                 'mbSpTrk_L1MBTS_1',
				 'mbSpTrk_L1MBTS_2',
				 'mbSpTrk_L1MBTS_1_1',
                                 'mbSpTrk_L1TE0',
                                 'mbSpTrk_L1FJ0',
                                 'mbSpTrk_L1FJ0_A',
                                 'mbSpTrk_L1FJ0_C',
                                 'mbSpTrk_L1LHCF',	
                                 'mbRd1_eff_HI',
                                 'mbMbts_1_eff_HI',
                                 'mbMbts_1_eff_unpaired_iso_HI',
                                 'mbMbts_1_1_eff_HI',
                                 'mbMbts_1_1_eff_unpaired_iso_HI',
                                 'mbZdc_eff_HI',
                                 'mbZdc_eff_unpaired_HI',
                                 'mbZdc_and_eff_HI',
                                 'mbZdc_and_eff_unpaired_iso_HI',
                                 'mbLucid_eff_HI',
                                 'mbLucid_a_c_eff_HI',
                                 'mbLucid_a_c_eff_unpaired_iso_HI',
                                 'mbLucid_A_eff_unpaired_HI',
                                 'mbLucid_C_eff_unpaired_HI',
                                 'mbSpBg_unpaired_iso_HI',
                                 'mbRd0_eff_unpaired_iso_HI',
                                 'mbSp_unpaired_iso_HI',
                                 'L1FJ0_NoAlg',
                                 'L1TE0_NoAlg',
                                 'L1TE35_NoAlg',  
 				 'L1TE10_NoAlg',
				 'L1TE20_NoAlg',
				 'L1TE50_NoAlg', 'L1TE65_NoAlg', 'L1TE90_NoAlg',
                                 'L1TE100_NoAlg',
                                 'L1TE115_NoAlg',
                                 'L1MBTS_2_NoAlg',
                                 'L1MBTS_1_1_NoAlg',
                                 'L1MBTS_3_3_NoAlg',
                                 'L1ZDC_NoAlg', 'mbZdc_NoAlg',
                                 'L1ZDC_A_NoAlg',
                                 'L1ZDC_C_NoAlg',
                                 'mbZdc_a_c_L2Zdc_eff',
                                 'mbTe10_L2Zdc_eff',
                                 'mbSpTrk_noiseSup',
                                 'mbSpTrk_noiseSup_unpaired_iso',
                                 'mbSpBg_noiseSup_unpaired_iso',
                                 'mbMbts_2_unpaired_iso_NoAlg',
                                 'mbMbts_1_unpaired_iso_NoAlg',
                                 'VdM_mbSpTrk',
                                 'mbMbts_1_A_ALFA_C_NoAlg',
                                 'mbMbts_1_C_ALFA_A_NoAlg',
                                 'mbMbts_1_C_ALFA_A_UNPAIRED_ISO_NoAlg',
                                 'mbMbts_1_A_ALFA_C_UNPAIRED_ISO_NoAlg',
                                 'mbSpTrk_ALFA_any',
                                 'mbSpTrk_ALFA_SDIFF',
                                 'alfa_any_NoAlg',
                                 'alfa_sdiff_NoAlg',
                                 'mbZdc_LG_eff',
                                 'mbZdc_HG_eff',
                                 'mbZdc_HG_eff_L1MBTS2',
                                 'mbZdc_HG_sideA',
                                 'mbZdc_HG_sideC',
                                 'mbZdc_HG_sideA_L1MBTS2',
                                 'mbZdc_HG_sideC_L1MBTS2',
                                 'mbZdc_LG_sideA',
                                 'mbZdc_LG_sideC',
                                 'mbZdc_LG_sideA_L1MBTS2',
                                 'mbZdc_LG_sideC_L1MBTS2'
                                 
                                 ])
    
    # Everything except non-colliding beam triggers.
    StoredValue   = ['mbSpTrk',
                     'mbTrtTrk',
                     "mbSp_oneD",
                     "mbSp_fwd",
                     "mbSp",
                     'mbMbts_1_NoCut_Time',
                     'mbMbts_1',
                     'mbMbts_2_NoCut_Time',
                     'mbMbts_2',
                     'mbMbts_1_1_NoCut_Time',
                     'mbMbts_1_1',
                     'mb_RM_eff',
                     'mb_RM_calib',
                     'mb_BM_calib',
                     'mb_LD_calib',
                     'mb_M1_calib',
                     'mb_M2_calib',
                     'mb_ZC_calib',
                     'mbBcm',
                     'mbRndm',
                     'mbLucid',
                     'mbZdc',
                     'mbSpBg_unpaired',
                     'mbSpTrk_unpaired',
                     'mbTrtTrk_unpaired',
                     'mbRmMbts_1_unpaired',
                     'mb_RM_calib_unpaired',
                     'mb_M1_calib_unpaired',
                     'mb_M2_calib_unpaired',
                     'mbRmMbts_1_NoCut_Time_unpaired',
                     'mbMbts_1_NoCut_Time_unpaired',
                     'mb_M4_4_calib',
                     'mb_M4_4_calib_firstempty',
                     'mb_M4_4_calib_cosmic',
                     'mb_M1_calib_cosmic', 
                     'mb_M4_4_calib_unpaired',
                     'mb_M2_calib_unpaired',
                     'mb_M1_calib_unpaired', 
                     'mb_LD_A_calib_unpaired',
                     'mb_LD_C_calib_unpaired',
                     'mbZdc_and_cosmic_NoAlg','mbZdc_and_NoAlg',
                     'mbZdc_a_cosmic','mbZdc_a',
                     'mbZdc_c_cosmic','mbZdc_c',
                     'mbZdc_a_c_cosmic_NoAlg','mbZdc_a_c_NoAlg',
                     'mbLucid_comm_cosmic','mbLucid_comm',
                     'mbLucid_a_cosmic','mbLucid_a',
                     'mbLucid_c_cosmic','mbLucid_c',
                     'mbLucid_a_c_cosmic','mbLucid_a_c',
                     'mbLucid_a_c_unpaired',
                     'mbBcm_AtoC_cosmic','mbBcm_AtoC',
                     'mbBcm_ht_cosmic','mbBcm_ht',
                     'mbBcm_mul_1_cosmic','mbBcm_mul_1',
                     'mbBcm_mul_2_cosmic','mbBcm_mul_2',
                     'mbBcm_mul_3_cosmic','mbBcm_mul_3',
                     'mbBcm_mul_4_cosmic','mbBcm_mul_4',
                     'mbBcm_mul_5_cosmic','mbBcm_mul_5',
                     'mbBcm_mul_6_cosmic','mbBcm_mul_6',
                     'mbMbts_a','mbMbts_c',
                     'mbMbts_1_unpaired1','mbMbts_1_unpaired2',
                     'mbMbts_2_unpaired1','mbMbts_2_unpaired2',
                     'mbMbts_1_1_unpaired1','mbMbts_1_1_unpaired2',
                     'mbMbts_4_4_unpaired1','mbMbts_4_4_unpaired2',
                     'mbMbts_1_1_unpaired','mbMbts_1_1_firstempty',
                     'mbMbts_1_firstempty','mbMbts_2_firstempty',
                     'mbMbts_1_empty','mbMbts_2_empty'
                     ]
    
    
_flags.append(signatures)

# create container
class MinBiasSlice(JobPropertyContainer, CommonSliceHelper):
    """ MinBias Slice Flags """

from TriggerJobOpts.TriggerFlags import TriggerFlags
TriggerFlags.add_Container(MinBiasSlice)

# add add common slice flags
TriggerFlags.MinBiasSlice.import_JobProperties('TriggerMenuPython.CommonSliceFlags')

for flag in _flags:
    TriggerFlags.MinBiasSlice.add_JobProperty(flag)
del _flags

# make an alias
MinBiasSliceFlags = TriggerFlags.MinBiasSlice

# add MinBias algs cuts as sub-container

from TrigT2MinBias.TrigT2MinBiasProperties import TrigT2MinBiasProperties
from TrigMinBias.TrigMinBiasProperties import TrigMinBiasProperties
