#include "../MHTFex.h"
#include "../CellFex.h"
#include "../TCFex.h"
#include "../TCPufitFex.h"
#include "../TrkMHTFex.h"
#include "../TrkTCFex.h"
#include "../TCPufitTrkFex.h"
#include "../CellPufitFex.h"
#include "../TCPuetaFex.h"
#include "../MuonFex.h"
#include "../FexSum.h"
#include "../CVFTool.h"
#include "GaudiKernel/DeclareFactoryEntries.h"

DECLARE_ALGORITHM_FACTORY( HLT::MET::CellFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::TCFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::MHTFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::TrkMHTFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::TrkTCFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::TCPufitFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::TCPufitTrkFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::CellPufitFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::TCPuetaFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::MuonFex )
DECLARE_ALGORITHM_FACTORY( HLT::MET::FexSum )
DECLARE_TOOL_FACTORY( CVFTool )

DECLARE_FACTORY_ENTRIES(TrigEFMissingET) {
    DECLARE_ALGORITHM( HLT::MET::CellFex );
    DECLARE_ALGORITHM( HLT::MET::TCFex );
    DECLARE_ALGORITHM( HLT::MET::MHTFex );
    DECLARE_ALGORITHM( HLT::MET::TrkMHTFex );
    DECLARE_ALGORITHM( HLT::MET::TrkTCFex );
    DECLARE_ALGORITHM( HLT::MET::TCPufitFex );
    DECLARE_ALGORITHM( HLT::MET::TCPufitTrkFex );
    DECLARE_ALGORITHM( HLT::MET::CellPufitFex );
    DECLARE_ALGORITHM( HLT::MET::TCPuetaFex );
    DECLARE_ALGORITHM( HLT::MET::MuonFex );
    DECLARE_ALGORITHM( HLT::MET::FexSum );
    DECLARE_TOOL( CVFTool );
}
