
from ROOT import *
gStyle.SetStatColor(0)
gStyle.SetFillColor(38)
gStyle.SetCanvasColor(0)
gStyle.SetPadColor(0)
gStyle.SetPadBorderMode(0)
gStyle.SetCanvasBorderMode(0)
gStyle.SetFrameBorderMode(0)
gStyle.SetOptStat(1110)
gStyle.SetStatH(0.3)
gStyle.SetStatW(0.3)

gStyle.SetTitleFillColor(0)
gStyle.SetTitleY(1.)
gStyle.SetTitleX(.1)
gStyle.SetTitleBorderSize(0)
gStyle.SetHistLineWidth(2)
gStyle.SetFrameFillColor(0)
#gStyle.SetLineWidth(2)
#gStyle.SetTitleColor(0)
#gStyle.SetTitleColor(1)
