# Dear emacs, this is a -*- Makefile -*-
# Author: Attila Krasznahorkay <Attila.Krasznahorkay@cern.ch>
# TrigAnalysisInterfaces makefile for the RootCore environment

PACKAGE          = TrigAnalysisInterfaces
PACKAGE_PRELOAD  =
PACKAGE_CXXFLAGS =
PACKAGE_LDFLAGS  =
PACKAGE_DEP      = AsgTools

include $(ROOTCOREDIR)/Makefile-common
