/*
  Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration
*/

#ifndef EGAMMAMVACALIB_EGAMMAMVACALIBDICT_H
#define EGAMMAMVACALIB_EGAMMAMVACALIBDICT_H


#endif // EGAMMAMVACALIB_EGAMMAMVACALIBDICT_H
