PACKAGE          = PhotonAnalysisUtils
PACKAGE_PRELOAD  = TMVA MLP XMLIO
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = $(shell root-config --libs) -lTMVA -lMLP -lXMLIO
PACKAGE_BINFLAGS = 
PACKAGE_DEP      = 
PACKAGE_NOOPT    = 0

include $(ROOTCOREDIR)/Makefile-common


