/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

#ifndef ISF_FASTCALOSIMPARAMETRIZATION_INTARRAY_H
#define ISF_FASTCALOSIMPARAMETRIZATION_INTARRAY_H
#include "ISF_FastCaloSimEvent/IntArray.h"

#endif // not ISF_FASTCALOSIMPARAMETRIZATION_INTARRAY_H
