!
 SUBROUTINE ADD_ADGE_SZT(SINF0,COSF0,SCUR,ZCUR,TCUR)
 USE M_MB_General_Volumes
 IMPLICIT NONE
 REAL(8), INTENT(IN) :: SINF0, COSF0, SCUR, ZCUR, TCUR
!
   Nadge = Nadge + 1
   XYZadge(1,Nadge) = TCUR*COSF0 - SCUR*SINF0
   XYZadge(2,Nadge) =        - ZCUR
   XYZadge(3,Nadge) = TCUR*SINF0 + SCUR*COSF0
!
 END SUBROUTINE ADD_ADGE_SZT
!
