!
 SUBROUTINE ADD_EDGE_SZT(SINF0,COSF0,ICUR,SCUR,ZCUR,TCUR)
 USE M_MB_General_Volumes
 IMPLICIT NONE
 REAL(8) :: SINF0, COSF0, SCUR, ZCUR, TCUR
 INTEGER :: ICUR
!
   Nedge = Nedge + 1
   CALL ADD_ADGE_SZT(SINF0,COSF0,SCUR,ZCUR,TCUR)
   IvuEdge(Nedge) = ICUR
   IadEdge(Nedge) = Nadge
!
 END SUBROUTINE ADD_EDGE_SZT
!
