!
 SUBROUTINE DEF_CENVOL_IV(IV,X0,Y0,Z0)
 USE M_MB_General_Volumes
 IMPLICIT NONE
!
 INTEGER, INTENT(IN) :: IV
 REAL(8), INTENT(IN) :: X0,Y0,Z0
!
   IF( IV >= 1 .AND. IV <= Nvolu ) CenVolu(1:3,IV) = (/ X0, Y0, Z0 /)
!
 END SUBROUTINE DEF_CENVOL_IV
!
