!
 SUBROUTINE DEFPLV( F0, ICOLOR, NB, NI, XYZI )
 USE M_MB_General_Volumes
 IMPLICIT NONE
 INTEGER  ::  ICOLOR,NB,NI(*)
 REAL(8)  ::  F0,XYZI(3,NB)
 REAL(8) :: XI(NB),YI(NB),ZI(NB)
!
   XI(1:NB)    =  XYZI(1,1:NB)
   IF( I_Atlas_Ref_Syst >= 1 ) THEN
     YI(1:NB) = -XYZI(3,1:NB)
     ZI(1:NB) =  XYZI(2,1:NB)
   ELSE
     YI(1:NB) =  XYZI(2,1:NB)
     ZI(1:NB) =  XYZI(3,1:NB)
   ENDIF
   CALL DEFPLX( F0, ICOLOR, NB, NI, XI,YI,ZI )
!
 END SUBROUTINE DEFPLV
!
