# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

can_be_disabled = [
    'L1_XE25',
    'L1_TE600',
    'L1_2EM5_NL',
    'EF_2mu6_NL',
    'EF_mu10_NL',
    'L1_TAU15',
    'L1_MU0_J15_EMPTY',
    'L1_EM3_MU6', #e5_mu6, not yet used
    'L1_2MU0_MU6',  #mu4mu6 chains
    'L1_EM7',
    'L1_EM12',
    'L1_2TAU6',
    'EF_tau50_medium',
    'EF_tau84_loose',
    'EF_mu10',
    'L1_MU11',
    'L1_MU15',
    'L1_TAU15_XE20',
    'L1_TAU15_XS35',
    'L1_TAU6_J50_XE20',
    'L1_EM14_XE10',
    'L1_MU10_J10',
    'L1_J20',
    'EF_tau16_loose_mu10', # EF_tau16_medium_mu10 is priority II primary
    'L1_EM10_MU6',

    'EF_je135_NoEF',
    'EF_je195_NoEF',
    'EF_je255_NoEF',
    'EF_je300_NoEF',

    'EF_mbRd0_eff',
    'EF_mbRd0_eff_empty',
    'L2_VdM_MBTS_1_1_UNPAIRED_ISO',
    'L2_VdM_RD0_UNPAIRED_ISO',
    'L2_VdM_Monitoring',
    'L2_VdM_MBTS_2_UNPAIRED_ISO',
    'L2_vtxbeamspot_FSTracks_SiTrk_MBTS',
    'L2_vtxbeamspot_allTE_SiTrk_peb_MBTS',
    'L2_vtxbeamspot_activeTE_SiTrk_peb_MBTS',
    'EF_mbTE20_eff',
    'EF_L1MU10_firstempty_NoAlg',
    'EF_mbMbts_2_eff_unpaired_iso',
    'EF_PreS_L1J10_firstempty',
    'EF_mbSpTrkVtxMh_eff',
    'EF_mbSpTrkVtxMh_medium_eff',
    'EF_mbSpTrkVtxMh_tight_eff',

    'L1_ZDC_AND_EMPTY',
    'L1_ZDC_A', 
    'L1_ZDC_C', 
    'L1_L1A_Mon', 
    'L1_LUCID_UNPAIRED_ISO', 
    'L1_LUCID_COMM_UNPAIRED_ISO', 
    'L1_ZDC_A_C_EMPTY', 
    'L1_NIM_S9C1C19', 
    'L1_LUCID_EMPTY', 
    'L1_LUCID_COMM',
    'L1_BPTX1_BGRP0', 
    'L1_ZDC_A_C', 
    'L1_LUCID_A_C', 
    'L1_BGRP7', 
    'L1_MBTS_4_4_EMPTY', 
    'L1_BCM_AC_CA_BGRP0', 
    'L1_LUCID_BGRP7', 
    'L1_MBTS_4_4', 
    'L1_TE700', 
    'L1_MU10_UNPAIRED_ISO', 
    'L1_CALREQ0', 
    'L1_CALREQ1', 
    'L1_ZDC_UNPAIRED_ISO', 
    'L1_LUCID_COMM_EMPTY',
    'L1_LUCID_A_C_UNPAIRED_ISO', 
    'L1_ALFA_BGRP7', 
    'L1_BCM_Wide_UNPAIRED_NONISO', 
    'L1_ZDC_EMPTY', 
    'L1_ZDC_AND', 
    'L1_MBTS_1_1', 
    'L2_mbRd0_Monitoring', 
    'L1_NIM_S9C1C20', 
    'L1_BCM_Wide_EMPTY', 
    'L1_MBTS_2_BGRP7', 
    'L1_BPTX0_BGRP0', 
    'L1_ALFA_EMPTY', 
    'L1_MBLZ', 
    'L1_BCM_HT_BGRP0',
    'L1_LUCID_A_C_UNPAIRED_NONISO',
    'L1_LUCID_A_C_EMPTY',
    'L1_BCM_Wide_UNPAIRED_ISO',
    
    
    'EF_HLTTimeBurner',
    'EF_allL1_NoAlg',

    'L1_MBTS_2',
    'L2_mbMbts_2_Monitoring',
    'EF_mbMbts_2_SpTrkMh',
    'EF_mbMbts_2_SpTrkMh120',
    'L1_TAU6_XE10',
    'L1_JE60',
    'L1_JE200',
    'L1_XS20',
    'L1_XS25',
    'L1_XS35',
    'L1_XS40',
    'L1_EM3_MU0',
    'L1_2J10_J30_JE140',
    #'',
    
    ]
