(find-file "../TrkKalmanFitter/KalmanFitter.h")
(find-file "../TrkKalmanFitter/ForwardKalmanFitter.h")
(find-file "../TrkKalmanFitter/KalmanSmoother.h")
(find-file "../src/KalmanFitter.cxx")
(find-file "../src/ForwardKalmanFitter.cxx")
(find-file "../src/KalmanSmoother.cxx")
(find-file "../src/KalmanOutlierLogic.cxx")
