PACKAGE          = ElectronPhotonSelectorTools
PACKAGE_PRELOAD  = 
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = 
PACKAGE_DEP      = AsgTools  xAODEgamma PATCore PathResolver xAODCaloEvent xAODTracking xAODHIEvent FourMomUtils
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 0
PACKAGE_PEDANTIC = 1
PACKAGE_REFLEX   = 1
include $(ROOTCOREDIR)/Makefile-common
