//Autogenerated VP1 Factory Code Implementation File (Fri Aug 19 13:36:52 CEST 2016)

#include <QtPlugin>
#include "VP1GeometryPlugin/VP1GeometryPlugin_VP1AutoFactory.h"
#include "VP1GeometryPlugin/VP1GeometryChannel.h"

QStringList VP1GeometryPlugin_VP1AutoFactory::channelWidgetsProvided() const
{
  return QStringList()
        << "Geometry"
         ;
}

IVP1ChannelWidget * VP1GeometryPlugin_VP1AutoFactory::getChannelWidget(const QString & channelwidget)
{
  if (channelwidget == "Geometry")
    return new VP1GeometryChannel();

  return 0;
}

