#include "../RoIBResultToAOD.h"
#include "../RoIBResultToxAOD.h"
#include "../MuCTPI_RDOToRoIBResult.h"

DECLARE_ALGORITHM_FACTORY( RoIBResultToxAOD )
DECLARE_ALGORITHM_FACTORY( RoIBResultToAOD )
DECLARE_ALGORITHM_FACTORY( MuCTPI_RDOToRoIBResult )

