from eflowRec.eflowRecFlags import jobproperties

from AthenaCommon.AlgSequence import AlgSequence
topSequence = AlgSequence()

#Jet/MET algorithms - EM input and LC output

from eflowRec.eflowCaloObjectBuilderGetter import eflowCaloObjectBuilderGetter
CaloObjectBuilderGetter = eflowCaloObjectBuilderGetter()

from eflowRec.eflowObjectBuilderToolsGetter import eflowObjectBuilderToolsGetter
ObjectBuilderToolsGetter = eflowObjectBuilderToolsGetter()

from eflowRec.eflowRecConf import eflowVertexInformationSetter
eflowVertexInformationSetter = eflowVertexInformationSetter("eflowVertextInformationSetter_EM")
topSequence += eflowVertexInformationSetter

from eflowRec.eflowRecConf import eflowOverlapRemoval
eflowOverlapRemoval = eflowOverlapRemoval("eflowOverlapRemoval_EM")
topSequence += eflowOverlapRemoval

#Jet/MET algorithms - LC input and LC output    

from eflowRec.eflowCaloObjectBuilderGetter_LC import eflowCaloObjectBuilderGetter_LC
CaloObjectBuilderGetter_LC = eflowCaloObjectBuilderGetter_LC()

from eflowRec.eflowObjectBuilderToolsGetter_LC import eflowObjectBuilderToolsGetter_LC
ObjectBuilderToolsGetter = eflowObjectBuilderToolsGetter_LC()

from eflowRec.eflowRecConf import eflowVertexInformationSetter
eflowVertexInformationSetter_LC = eflowVertexInformationSetter("eflowVertextInformationSetter_LC")
eflowVertexInformationSetter_LC.PFOInputName="neutralJetETMiss_LCPFO_eflowRec"
topSequence += eflowVertexInformationSetter_LC

eflowVertexInformationSetter_LC_NonModified = eflowVertexInformationSetter("eflowVertextInformationSetter_LC_NonModified")
eflowVertexInformationSetter_LC_NonModified.PFOInputName="neutralJetETMiss_LCPFO_NonModified_eflowRec"
topSequence += eflowVertexInformationSetter_LC_NonModified

from eflowRec.eflowRecConf import eflowOverlapRemoval
eflowOverlapRemoval_LC = eflowOverlapRemoval("eflowOverlapRemoval_LC")
eflowOverlapRemoval_LC.PFOInputName="neutralJetETMiss_LCPFO_eflowRec"
eflowOverlapRemoval_LC.ElectronInputName="eflowRec_selectedElectrons_LC"
topSequence += eflowOverlapRemoval_LC

from eflowRec.eflowRecConf import eflowOverlapRemoval
eflowOverlapRemoval_LC_NonModified = eflowOverlapRemoval("eflowOverlapRemoval_LC_NonModified")
eflowOverlapRemoval_LC_NonModified.PFOInputName="neutralJetETMiss_LCPFO_NonModified_eflowRec"
eflowOverlapRemoval_LC_NonModified.ElectronInputName="eflowRec_selectedElectrons_LC"
topSequence += eflowOverlapRemoval_LC_NonModified
