from eflowRec.eflowRecFlags import jobproperties

from AthenaCommon.AlgSequence import AlgSequence
topSequence = AlgSequence()

from eflowRec.eflowTauProcessingToolsGetter import eflowTauProcessingToolsGetter
TauProcessingToolsGetter = eflowTauProcessingToolsGetter()

from eflowRec.eflowRecConf import eflowVertexInformationSetter
eflowVertexInformationSetter_Tau = eflowVertexInformationSetter("eflowVertextInformationSetter_Tau")
eflowVertexInformationSetter_Tau.PFOInputName="neutralTauPFO_eflowRec"
topSequence += eflowVertexInformationSetter_Tau
