SET echo OFF;
drop table MSYS_DATA2TAG; 
drop table MSYS_DATA;
drop table ACUT_DATA2TAG; 
drop table ACUT_DATA;
drop table ALMN_DATA2TAG; 
drop table ALMN_DATA;
drop table ASMP_DATA2TAG; 
drop table ASMP_DATA;
drop table DBAM_DATA2TAG; 
drop table DBAM_DATA;
drop table WCRO_DATA2TAG; 
drop table WCRO_DATA;
drop table WMDT_DATA2TAG; 
drop table WMDT_DATA;
drop table WTGC_DATA2TAG; 
drop table WTGC_DATA;
drop table AGDD_DATA2TAG; 
drop table AGDD_DATA;
drop table AMDC_DATA2TAG; 
drop table AMDC_DATA;
drop table ATLN_DATA2TAG; 
drop table ATLN_DATA;
drop table GGLN_DATA2TAG; 
drop table GGLN_DATA;
drop table WCSC_DATA2TAG; 
drop table WCSC_DATA;
drop table WRPC_DATA2TAG; 
drop table WRPC_DATA;
drop table ATYP_DATA2TAG; 
drop table ATYP_DATA;
drop table WCHV_DATA2TAG; 
drop table WCHV_DATA;
drop table WDED_DATA2TAG; 
drop table WDED_DATA;
drop table WSPA_DATA2TAG; 
drop table WSPA_DATA;
drop table ALIN_DATA2TAG; 
drop table ALIN_DATA;
drop table APTP_DATA2TAG; 
drop table APTP_DATA;
drop table AWLN_DATA2TAG; 
drop table AWLN_DATA;
drop table WCMI_DATA2TAG; 
drop table WCMI_DATA;
drop table WLBI_DATA2TAG; 
drop table WLBI_DATA;
drop table WSUP_DATA2TAG; 
drop table WSUP_DATA;

purge user_recyclebin;
commit;
select * from tab;
select * from user_ts_quotas;
