!
!> \author M.Virchaux
!
 SUBROUTINE CODEIN(IFILI,IL,IW,NN,ID,J,IC,INOF,INOZ,ICT,  IZTPLA)
 USE M_MB_MuGeom
 USE M_MB_CTRABAZ
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: IFILI, IL, IW, NN, ID, J, IC, INOF, INOZ, ICT, IZTPLA
 INTEGER :: IND, JND
!
   IND = J
   CALL MVBITS(ID,0,12,IND, 2)
   CALL MVBITS(NN,0,12,IND,14)
   IF( IW    /= 0 ) IND = IBSET(IND,26)
   IF( IL    /= 0 ) IND = IBSET(IND,27)
   IF( IFILI /= 0 ) IND = IBSET(IND,28)
   INDPLA(IZTPLA) = IND
!
   IF(IL == 0) THEN
     JND = INOZ
     CALL MVBITS(INOF,0, 8,JND, 8)
     CALL MVBITS(IC  ,0,16,JND,16)
     IF(IC <= NCOUBA) THEN
       ICCPLA(IZTPLA) = -1
     ELSEIF(IC <= NCOUCH) THEN
       ICCPLA(IZTPLA) =  1
     ELSE
       ICCPLA(IZTPLA) =  0
     ENDIF
     JNDPLA(IZTPLA) = JND
   ELSE
     JNDPLA(IZTPLA) = ICT
     IF(ICT <= NTRIBA) THEN
       ICCPLA(IZTPLA) = -1
     ELSE
       ICCPLA(IZTPLA) =  1
     ENDIF
   ENDIF
!
 END SUBROUTINE CODEIN
!
!
!
 SUBROUTINE DECOIN(IZTPLA, IFILI,IW01,NN,ID,J,IC,INOF,INOZ,ICT)
 USE M_MB_CTRABAZ
 IMPLICIT NONE
 INTEGER, INTENT(IN)  :: IZTPLA
 INTEGER, INTENT(OUT) :: IFILI, IW01, NN, ID, J, IC, INOF, INOZ, ICT
 INTEGER :: IND, JND
!
   IND = INDPLA(IZTPLA)
   IFILI = IBITS(IND,28, 1)
   IW01  = IBITS(IND,26, 1)
   NN    = IBITS(IND,14,12)
   ID    = IBITS(IND, 2,12)
   J     = IBITS(IND, 0, 2)
!
   IF( BTEST(IND,27) ) THEN
     IC    = 0
     INOF  = 0
     INOZ  = 0
     ICT   = JNDPLA(IZTPLA)
   ELSE
     JND  = JNDPLA(IZTPLA)
     INOZ = IBITS(JND, 0, 8)
     INOF = IBITS(JND, 8, 8)
     IC   = IBITS(JND,16,16)
     ICT   = 0
   ENDIF
!
 END SUBROUTINE DECOIN
!
