!
!> Same as nokcha.F90, but taking angle of cutout into account
!> thus, one more argument TT
!
 LOGICAL FUNCTION NAKCHA(IC,INOZ,IGEOM,ZZ,SS,TT,TOLZ,TOLS)
 USE M_MB_Control
 USE M_MB_MuGeom
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: IC, INOZ, IGEOM
 REAL(8), INTENT(IN) :: ZZ, SS, TT, TOLZ, TOLS
 LOGICAL :: INSIDE
 INTEGER :: JCUT, L
 REAL(8) :: ZZMZ0, DECAL, SWIZZN,SWIZZP, ZA, ZB,SB
!
   NAKCHA = .TRUE.
!
   ZZMZ0 = ZZ - ZCECHAV(IGEOM)
   DECAL = 0.1000D0
   IF( IC <= NCOUBA  ) then
     IF( INOZ < NZMS2 ) DECAL =  MDTnu * DECAL
   ENDIF
   IF( ABS(ZZMZ0-DECAL) > ZLOCHAV(IGEOM)*0.5d0+TOLZ )         RETURN
   CALL Get_Tube_Lateral_Dim(IGEOM,ZZ, SWIZZN,SWIZZP)
   IF( SS > SWIZZP+TOLS )              RETURN
   IF( SS < SWIZZN-TOLS )              RETURN
!
   JCUT = ISTCUTV(IGEOM)
   IF( JCUT > 0 ) THEN
     DO L=1,NBCUT(JCUT)
       ZA = ZZ
       IF( ABS(ANCUT(JCUT,L)) > 1.d-3 )  ZA = ZZ - (TT-TCUTOUT(IGEOM))*TAN(ANCUT(JCUT,L))
       CALL ApplyTol(ZA,SS, ZTCUT(1,JCUT,L),SSCUT(1,JCUT,L), TOLZ,TOLS, ZB,SB)
       IF( INSIDE(ZB,SB,4,ZTCUT(1,JCUT,L),SSCUT(1,JCUT,L)) ) RETURN
     ENDDO
   ENDIF
!
   NAKCHA = .FALSE.
!
 END FUNCTION NAKCHA
!
