#include "TrackCaloClusterRecValidation/TrackCaloClusterRecValidationTool.h"
#include "TrackCaloClusterRecValidation/CalibrationNtupleMakerTool.h"

DECLARE_TOOL_FACTORY(TrackCaloClusterRecValidationTool)
DECLARE_ALGORITHM_FACTORY(CalibrationNtupleMakerTool)

