#!/usr/bin/env python

# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
# Heuristic determination of domains from object type_key

# a : tpye_key of the object
# fileType : ESD AOD DPD (actually not used yet)
def obj_category(a,fileType):
    if a.startswith('IOV'):return 'Once per file'
    if a.startswith('LumiBlock'):return 'Once per file'
    if a.startswith('EventBook'):return 'MetaData'
    if a.startswith('SkimDecision'):return 'MetaData'
    if a.count('Stream'):return 'MetaData'    
    if a.count("Truth") :return 'Truth'
    if a.count("McEvent") :return 'Truth'    
    if a.count("Atlfast") :return 'Truth'    
    if a.count("LVL1") :return 'Trigger'    
    if a.count("Trig") :return 'Trigger'
    if a.count("RODHeader") :return 'Trigger'    
    if a.count("HLT") :return 'Trigger'
    if a.count("RoI") :return 'Trigger'
    if a.count("JEMHit") :return 'Trigger'        
    if a.count('EventInfo'):return 'EID'        
    if a.count('RecoTiming'):return 'EID'
    if a.count('RawInfo'):return 'EID'
    if a.count('Missing'):return 'MET'
    if a.count('MEt'):return 'MET'    
    if a.count('Tau'):return 'Tau'
    if a.count('tau'):return 'Tau'
    if a.count('Metadata'):return 'MetaData'
    if a.count('BCM'): return 'Forward Det'
    if a.count('Jet'):return 'Jet'
    if a.count('InDet'):return 'InDet'
    if a.count('TRT'):return 'InDet'
    if a.count('Pixel'):return 'InDet'        
    if a.count('Electron'):return 'egamma'
    if a.count('Softe'):return 'egamma'    
    if a.count('Photon'):return 'egamma'
    if a.count('egDet'):return 'egamma'        
    if a.count('Muon'):return 'Muon'
    if a.count('Moo'):return 'Muon'
    if a.count('Mdt'):return 'Muon'
    if a.count('Csc'):return 'Muon'    
    if a.count('Rpc'):return 'Muon'            
    if a.count('Muid'):return 'Muon'
    if a.count('TileMu'):return 'Muon'
    if a.count('MuGirl'):return 'Muon'
    if a.count('Staco'):return 'Muon'
    if a.count('MuTag'):return 'Muon'
    if a.count('ThirdChain'):return 'Muon'        
    if a.count('MBoy'):return 'Muon'                
    if a.count('Tile'):return 'Calo'    
    if a.count('LAr'):return 'Calo'
    if a.count('Calo'):return 'Calo'
    if a.count('HICentrality'):return 'Calo'
    if a.count('HIEt'):return 'Calo'        
    if a.count('HIFlow'):return 'Calo'    
    if a.count('Zdc'):return 'Forward Det'
    if a.count('Lucid'):return 'Forward Det'        
    if a.count('EtaPhi'):return 'InDet'            
    if a.startswith('DataHeader'):return 'Once per file'
    if a.count('CPM') or a.count('CTP') or a.count('CMM'):return 'Trigger'
    if a.count("GSF") :return 'egamma'
    if a.count("VxContainer") :return 'InDet'
    if a.count("TrackParticleCandidate") :return 'InDet'            
    if a.count('Track'):return 'EMT'    
    print "WARNING: Could not assign algdomain for",a
    return 'undefined'

