!
!> \author M.Virchaux
!
 SUBROUTINE ADEDMAT( F0, NN, XYZE )
 USE M_MB_COMATI
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: NN
 REAL(8), INTENT(IN) :: F0, XYZE(3,NN)
 REAL(8) :: SINF0, COSF0
!
   IF( NAMATI+NN > KADGE ) THEN
     WRITE(*,'(//" In ADEDMAT of MUONBOY : Parameter KADGE is not big enough  =====>  STOP !!!")')
     STOP
   ENDIF
!
   SINF0 = SIN(F0)
   COSF0 = COS(F0)
   XYZMATI(1,NAMATI+1:NAMATI+NN) = XYZE(1,1:NN)*COSF0 - XYZE(2,1:NN)*SINF0
   XYZMATI(2,NAMATI+1:NAMATI+NN) = XYZE(1,1:NN)*SINF0 + XYZE(2,1:NN)*COSF0
   XYZMATI(3,NAMATI+1:NAMATI+NN) = XYZE(3,1:NN)
   NAMATI = NAMATI + NN
!
 END SUBROUTINE ADEDMAT
!
