!
!> \author M.Virchaux
!
 SUBROUTINE CLOMAT
 USE M_MB_COMATI
 IMPLICIT NONE
 INTEGER :: NM1, N00, NEP, NEC, I1, I2, J1, J2
!
   NM1 = NEMAT1(NPMATI-1) - NEMAT0(NPMATI-1) + 1
   N00 = NEMAT1(NPMATI  ) - NEMAT0(NPMATI  ) + 1
   IF( NM1 <= 2 .OR. NM1 /= N00 ) THEN
     PRINT 1000,NVMATI,NPMATI,NM1,N00
1000 FORMAT(//' In CLOMAT : NVMATI,NPMATI,NM1,N00 =',4I6,'  =====>  STOP !')
     STOP
   ENDIF
!
   NEP = NEMAT0(NPMATI-1) - 1
   NEC = NEMAT0(NPMATI  ) - 1
   DO 10 I1=1,N00
     I2 = MOD(I1,N00) + 1
     DO J1=1,N00
       J2 = MOD(J1,N00) + 1
       IF( IAMATI(NEP+I2) == IAMATI(NEP+J1) .AND. IAMATI(NEP+I1) == IAMATI(NEP+J2) .AND.  &
           IAMATI(NEC+I2) == IAMATI(NEC+J1) .AND. IAMATI(NEC+I1) == IAMATI(NEC+J2) ) GO TO 10
     ENDDO
     NPMATI = NPMATI + 1
     NEMAT0(NPMATI) = NEMATI + 1
     NEMAT1(NPMATI) = NEMATI + 4
     IAMATI(NEMATI+1) = IAMATI(NEP+I1)
     IAMATI(NEMATI+2) = IAMATI(NEC+I1)
     IAMATI(NEMATI+3) = IAMATI(NEC+I2)
     IAMATI(NEMATI+4) = IAMATI(NEP+I2)
     NEMATI = NEMATI + 4
10 CONTINUE
!
   IF( NPMATI > KPLAN ) THEN
     WRITE(*,'(//" In CLOMAT of MUONBOY : Parameter KPLAN is not big enough  =====>  STOP !!!")')
     STOP
   ENDIF
   IF( NEMATI > KEDGE ) THEN
     WRITE(*,'(//" In CLOMAT of MUONBOY : Parameter KEDGE is not big enough  =====>  STOP !!!")')
     STOP
   ENDIF
!
 END SUBROUTINE CLOMAT
!
