!
!> \author M.Virchaux
!
 SUBROUTINE COPYMAT( IV, JTRANS, AAA,IMANAT,JFF,JZZ )
 USE M_MB_COMATI
 IMPLICIT NONE
 CHARACTER(8) :: AAA
 INTEGER :: IV, JTRANS, IMANAT, JFF, JZZ
 INTEGER :: IP
!
   CALL NEWMAT( AAA,IMANAT,JFF,JZZ )
!
   ITRANSMATI(NVMATI) = JTRANS
!
   DO IP=NPMAT0(IV),NPMAT1(IV)
     NPMATI = NPMATI + 1
     IF( NPMATI > KPLAN ) THEN
       PRINT '(//" In COPYMAT : Parameter KPLAN is not big enough  =====>  STOP !")'
       STOP
     ENDIF
     NEMAT0(NPMATI) = NEMAT0(IP)
     NEMAT1(NPMATI) = NEMAT1(IP)
   ENDDO
!
   CALL ENDMAT
!
 END SUBROUTINE COPYMAT
!
