!
!
!
!
! Author : M.Virchaux
!***********************************************************************
 SUBROUTINE DVBARR(F0, IXYZ, XP1,YP1,ZP1, DXP1,DYP1,DZP1, XP2,YP2,ZP2, DXP2,DYP2,DZP2 )
 IMPLICIT NONE
 INTEGER :: IXYZ
 REAL(8) :: F0, XP1, YP1, ZP1, DXP1, DYP1, DZP1
 REAL(8) ::     XP2, YP2, ZP2, DXP2, DYP2, DZP2
!
   CALL DP4MAT(F0, IXYZ, XP1,YP1,ZP1, DXP1,DYP1,DZP1 )
   CALL DP4MAT(F0, IXYZ, XP2,YP2,ZP2, DXP2,DYP2,DZP2 )
   CALL CLOMAT
!
 END
