!
! Author : M.Virchaux
!
 SUBROUTINE GETXYZMAT( IV, IE, XYZ )
 USE M_MB_COMATI
 IMPLICIT NONE
 INTEGER, INTENT(IN)  :: IV, IE
 REAL(8), INTENT(OUT) :: XYZ(3)
 INTEGER :: IA, J
!
   IA = IAMATI(IE)
   IF( ITRANSMATI(IV) >= 1 ) THEN
     J = ITRANSMATI(IV)
     XYZ(1:3) = TRANSMATI(1:3,1,J)*XYZMATI(1,IA) + TRANSMATI(1:3,2,J)*XYZMATI(2,IA)  &
              + TRANSMATI(1:3,3,J)*XYZMATI(3,IA) + TRANSMATI(1:3,4,J)
   ELSE
     XYZ(1:3) = XYZMATI(1:3,IA)
   ENDIF
!
 END SUBROUTINE GETXYZMAT
!
