!
 SUBROUTINE REORDMUSC
 USE M_MB_COMUSC
 IMPLICIT NONE
!
 INTEGER :: NORDRE(KMASC)
!
   IF( NBMASC <= 1 ) RETURN
!
   CALL CROISS(RRMASC,NBMASC,NORDRE)
   CALL REORDO(RRMASC,NORDRE,NBMASC)
   CALL REORDO(X0MASC,NORDRE,NBMASC)
   CALL REORDO(ALMASC,NORDRE,NBMASC)
   CALL REORDO(BLMASC,NORDRE,NBMASC)

   CALL REORDO(XposMASC,NORDRE,NBMASC)
   CALL REORDO(YposMASC,NORDRE,NBMASC)
   CALL REORDO(ZposMASC,NORDRE,NBMASC)
   CALL REORDO(XdirMASC,NORDRE,NBMASC)
   CALL REORDO(YdirMASC,NORDRE,NBMASC)
   CALL REORDO(ZdirMASC,NORDRE,NBMASC)
   CALL REORDO(PmomMASC,NORDRE,NBMASC)
   CALL REORDO(ChgeMASC,NORDRE,NBMASC)
   CALL IEORDO(IValMASC,NORDRE,NBMASC)
!
 END SUBROUTINE REORDMUSC
!
