#! /bin/zsh

# Wrapper script that runs a command in batch

workdir=$1
executable=$2
jobType=$3

export CAFJOBTYPE=$jobType

echo "args = $workdir $executable"
date
source /afs/cern.ch/user/l/larcomm/w0/digitMon/cafEnv
cd $workdir
pwd
printenv
date
$executable
date
