#!/bin/bash

#Script to automatically perform the average of root histograms for the reference plots

if [[ -z $1 ]]
    then
    echo "usage: $0 <process>"
    echo "available processes:"
    ls out
    exit -1
fi

STARTDIR=`pwd`

PROCESS=$1
DIR=out/$PROCESS/root

echo "Average histograms in directory $DIR" 
echo "found `ls $DIR/*.root | wc -l` root files"

cd $DIR
root -q -b ../../../share/make_avg.C+
cd -

mkdir out/average >& /dev/null
mv $DIR/avg_histos.root out/average/avg_histos_${PROCESS}.root
