AllAlgs = False
EvtMax=5
DetDescrVersion="ATLAS-DC3-01" 
PoolESDInput = ["ESD.pool.root"] # change file name and path appropriately
PoolAODOutput = "AOD.FromESD.pool.root" # change file name an dpath
doWriteESD = False
doWriteTAG = False # True to produce Event Tag
readESD = True
doCBNT = False
doHist = False
