#include "GaudiKernel/DeclareFactoryEntries.h"

#include "SUSYTools/SUSYObjDef_xAOD.h"
#include "../SUSYToolsAlg.h"
#include "../ApplySUSYTools.h"

DECLARE_NAMESPACE_TOOL_FACTORY(ST, SUSYObjDef_xAOD)
DECLARE_ALGORITHM_FACTORY(SUSYToolsAlg)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(ST, ApplySUSYTools)

DECLARE_FACTORY_ENTRIES(SUSYTools) {
  DECLARE_NAMESPACE_TOOL(ST, SUSYObjDef_xAOD)
  DECLARE_ALGORITHM(SUSYToolsAlg)
  DECLARE_NAMESPACE_ALGORITHM(ST, ApplySUSYTools)
}
