#include "SUSYTools/SUSYObjDef_xAOD.h"
#include "../SUSYToolsAlg.h"
#include "../ApplySUSYTools.h"

DECLARE_NAMESPACE_TOOL_FACTORY(ST, SUSYObjDef_xAOD)
DECLARE_ALGORITHM_FACTORY(SUSYToolsAlg)
DECLARE_NAMESPACE_ALGORITHM_FACTORY(ST, ApplySUSYTools)

