#!/bin/bash

#copy files in out/average to RTT reference plot location:

targetdir=/afs/cern.ch/atlas/project/RTT/DCubeReference/offline/Generators/HepMCAnalysis_i

PROCESSTABLE=run_scripts/process_table
if [ -z $1 ]
    then
    echo "usage:"
    echo "$0 <process>"
    echo "available processes are:"
    awk '{print $1}' $PROCESSTABLE
    exit -1
fi

JobCoreName=$1

jobcorename=(`awk '{print $1}' $PROCESSTABLE`)
outputname=(`awk '{print $4}' $PROCESSTABLE`)

i=0
OutputName="" 
for JCN in ${jobcorename[@]}
  do
  if [[ ${jobcorename[$i]} == $JobCoreName ]]
      then
      OutputName=${outputname[$i]}
  fi
  i=$(($i+1))
done

if [[ $OutputName == "" ]]
    then
    echo "Process $JobCoreName not found"
    echo "available processes are:"
    awk '{print $1}' $PROCESSTABLE
    exit -1
fi

if [[ ! -e reference/$JobCoreName.root ]]
    then
    echo "reference plot for process $PROCESS not found in reference dir"
    exit -1
fi

refname=${OutputName%.root}_reference.root

diff reference/$JobCoreName.root $targetdir/$refname >& /dev/null
if [[ $? == 0 ]]
    then
    echo "$JobCoreName.root in reference/"
    echo "and $refname in $targetdir"
    echo "coincides, skipping"
    exit
fi

echo "save backup copy:"
echo $refname.bck
mv $targetdir/$refname $targetdir/$refname.bck
cp reference/$JobCoreName.root $targetdir/$refname
