LOAD DATA
INFILE './load_data/mdt_head.dat'
BADFILE './load_data/mdt_head.bad'
DISCARDFILE 'load_data/mdt_head.dsc'
CONTINUEIF NEXT(1)='+'
INTO TABLE mdt_head  APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(IMPLEMENTATION,LOWRUN,UPRUN,LOWTIME,UPTIME,LUMINOSITY,ROOTFILE)
