-- Usage
-- sqlldr provac/provac control=./load_data/mdt_rt.ctl

LOAD DATA
INFILE './load_data/mdt_rt.dat'
BADFILE './load_data/mdt_rt.bad'
DISCARDFILE './load_data/mdt_rt.dsc'
CONTINUEIF NEXT(1)='+'
INTO TABLE mdt_rt  APPEND
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(MDT_RT_ID,
REGION_ID,
HEAD_ID,
LOWRUN,
UPRUN,
HISTOGRAM,
N_SEGS,
AVER_ANGLE,
DELTA_AVER_ANGLE,
AVER_SPREAD,
DELTA_AVER_SPREAD,
CONVERGENCE,
B_AVER,
T_AVER,
HV,
CURR,
GAS,
CALIBFLAG,
VALIDFLAG)
