#!/bin/sh

dir=`pwd`
if [ `basename $dir` != D3PDMakerTest ]; then
  cd ..
  dir=`pwd`
fi
if [ `basename $dir` != D3PDMakerTest ]; then
  echo "Can't find D3PDMakerTest directory."
  exit 1
fi


dodump() {
  src=run/*-$CMTCONFIG/$1
  if [ ! -r $src ]; then
    src=run/$1
  fi
  python  python/dumptuple_any.py --by-branch $src >| test/$2
}


dodump physics.root      physics-esd-d3pd.ref
dodump egamma.root       egamma-aod-d3pd.ref
dodump egamma-17_0.root  egamma-aod-d3pd-17_0.ref
dodump egamma-16_6.root  egamma-aod-d3pd-16_6.ref
dodump egamma-16_0.root  egamma-aod-d3pd-16_0.ref
dodump egamma-15.root    egamma-aod-d3pd-15.ref
