#!/bin/bash

set -e
set -u

options=""
for file in `echo $1 | sed 's/,/ /g'`
do
    options="$options --el-input-file $file"
done

OUTPUT_DIR=output.$$
rm -rf $OUTPUT_DIR
quickana_validate --write-summary $options $OUTPUT_DIR
