###
### example file for testing ObjKeyStore loading mechanism
###

def _fill( item ):
    item.add( {
        'CaloCellContainer'    : [ 'AllCalo' ],
        'CaloCellLinkContainer': [ 'CombinedCluster_Link',
                                   'LArClusterEM_Link',
                                   'LArClusterEM57Nocorr_Link',
                                   'EMTopoCluster_Link',
                                   'egClusterCollection_Link',
                                   'LArClusterEMSofte_Link' ],
        'CaloClusterContainer' : [ 'CombinedCluster',
                                   'LArClusterEM',
                                   'LArClusterEM57Nocorr',
                                   'EMTopoCluster',
                                   'egClusterCollection',
                                   'LArClusterEMSofte' ],
        'CaloShowerContainer'  : [ 'CombinedCluster_Data',
                                   'LArClusterEM_Data',
                                   'LArClusterEM57Nocorr_Data',
                                   'EMTopoCluster_Data',
                                   'egClusterCollection_Data',
                                   'LArClusterEMSofte_Data' ],
        'CaloTowerContainer'   : [ 'CombinedTower', 'LArTowerEM' ],
        'DataVector<INavigable4Momentum>' : [ 'CombinedCluster',
                                              'LArClusterEM',
                                              'LArClusterEM57Nocorr',
                                              'EMTopoCluster' ],
        'DetStatusMap'         : [ 'DetectorStatus' ],
        'JetCollection'        : [ 'Cone7H1TowerJets',
                                   'Cone4H1TowerJets',
                                   'Kt6H1TowerJets',
                                   'Kt4H1TowerJets',
                                   'Cone7H1TopoJets',
                                   'Cone4H1TopoJets',
                                   'Kt6H1TopoJets',
                                   'Kt4H1TopoJets',
                                   'JetTruthParticles',
                                   'Cone7TruthJets',
                                   'Cone4TruthJets',
                                   'Kt6TruthJets',
                                   'Kt4TruthJets' ],
        'egDetailContainer'    : [ 'egDetailContainer',
                                   'SofteDetailContainer',
                                   'egDetailAOD' ],
        'egammaContainer'      : [ 'PhotonCollection',
                                   'ElectronCollection',
                                   'softeCollection',
                                   'ElectronAODCollection',
                                   'PhotonAODCollection' ],
        } )
    return
