#! /usr/bin/env bash

## Any arguments to the script are overrides or options (added at the end)
#if [[ $# -ge 1 ]]; then
#  ARGS=$@
#else
#  ARGS=''
#fi

if [[ x$TESTDATA == x ]]; then
  echo "ERROR: TESTDATA not defined"
  exit 1
fi

DIGIOFFSET1=10
DIGIOFFSET2=20
INPUTFILE=${TESTDATA}/mu_E50_eta0-25_${GEOMETRY}.hits.pool.root
FILENAME=`basename ${INPUTFILE}`
FILEBASE=${FILENAME%.hits.pool.root}
RDOFILE=${FILEBASE}.rdo.pool.root
MINBIASFILE=NONE
CAVERNFILE=NONE
JOBCONFIG=NONE
DBRELEASETARBALL='current'

TRF=Digi_tf.py
which $TRF
if [[ $? -ne 0 ]]; then
  echo "ERROR: $TRF not found"
  exit 2
fi
cmd="skip_if_AthSimulation.sh $TRF --inputHITSFile=$INPUTFILE --outputRDOFile=$RDOFILE --maxEvents=5 --skipEvents=0 --geometryVersion=$GEOMETRY --digiSeedOffset1=$DIGIOFFSET1 --digiSeedOffset2=$DIGIOFFSET2 --conditionsTag=$IOVDBGLOBALTAG --DataRunNumber $DATARUNNUMBER $@"
echo $cmd
$cmd
