# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

test_dicts = [
    {'EBstep': -1, 'signatures': '', 'stream': ['Main'], 'chainParts': [{'bTracking': '', 'L1item': '', 'trigType': 'j', 'bTag': '', 'scan': 'FS', 'dataType': 'TT', 'multiplicity': '1', 'jetCalib': 'subjes', 'bConfig': [], 'extra': '', 'etaRange': '0eta320', 'topo': [], 'calib': 'em', 'dataScouting': '', 'signature': 'Jet', 'threshold': '110', 'addInfo': [], 'chainPartName': 'j110', 'recoAlg': 'a4'}], 'topo': [], 'groups': ['RATE:SingleJet', 'BW:Jets'], 'topoStartFrom': False, 'chainCounter': 318, 'signature': 'Jet', 'L1item': 'L1_J30', 'chainName': 'j110_TT'},
# {'EBstep': -1, 'signatures': '', 'stream': ['Main'], 'chainParts': [{'bTracking': '', 'bTag': '', 'scan': 'FS', 'dataType': 'tc', 'jetCalib': 'subjes', 'etaRange': '0eta320', 'topo': [], 'threshold': '15', 'chainPartName': 'j15', 'recoAlg': 'a4', 'trigType': 'j', 'bConfig': [], 'multiplicity': '1', 'extra': '', 'dataScouting': '', 'signature': 'Jet', 'calib': 'em', 'addInfo': [], 'L1item': ''}, {'bTracking': '', 'bTag': '', 'scan': 'FS', 'dataType': 'tc', 'jetCalib': 'subjes', 'etaRange': '320eta490', 'topo': [], 'threshold': '15', 'chainPartName': 'j15_320eta490', 'recoAlg': 'a4', 'trigType': 'j', 'bConfig': [], 'multiplicity': '1', 'extra': '', 'dataScouting': '', 'signature': 'Jet', 'calib': 'em', 'addInfo': [], 'L1item': ''}], 'topo': [], 'chainCounter': 388, 'groups': ['RATE:SingleJet', 'BW:Jets'], 'signature': 'Jet', 'topoThreshold': None, 'topoStartFrom': False, 'L1item': 'L1_RD0_FILLED', 'chainName': 'j15_j15_320eta490'}
    
# {'EBstep': -1, 'signatures': '', 'stream': ['Main'], 'chainParts': [{'bTracking': '', 'L1item': '', 'trigType': 'j', 'bTag': '', 'scan': 'FS', 'dataType': 'tc', 'multiplicity': '1', 'jetCalib': 'subjes', 'bConfig': [], 'extra': 'test3', 'etaRange': '0eta320', 'topo': [], 'calib': 'em', 'dataScouting': '', 'signature': 'Jet', 'threshold': '200', 'addInfo': [], 'chainPartName': 'j200_jes_FS', 'recoAlg': 'a4'}], 'topo': [], 'groups': ['RATE:SingleJet', 'BW:Jets'], 'topoStartFrom': False, 'chainCounter': 292, 'signature': 'Jet', 'L1item': 'L1_J100', 'chainName': 'j200_jes_FS'},

# {'EBstep': -1, 'signatures': '', 'stream': ['Main'], 'chainParts': [{'bTracking': '', 'L1item': '', 'trigType': 'j', 'bTag': '', 'scan': 'FS', 'dataType': 'tc', 'multiplicity': '1', 'jetCalib': 'sub', 'bConfig': [], 'extra': '', 'etaRange': '0eta320', 'topo': [], 'calib': 'lcw', 'dataScouting': '', 'signature': 'Jet', 'threshold': '0', 'addInfo': [], 'chainPartName': 'j0_a10r_lcw_sub_L1J12', 'recoAlg': 'a10r'}], 'topo': [], 'groups': ['RATE:SingleJet', 'BW:Jets'], 'topoStartFrom': False, 'chainCounter': 278, 'signature': 'Jet', 'L1item': 'L1_J12', 'chainName': 'j0_a10r_lcw_sub_L1J12'},


#     {'EBstep': -1, 'signatures': '', 'stream': ['Main'], 'chainParts': [{'bTracking': '', 'bTag': '', 'extra': '', 'dataType': 'tc', 'jetCalib': 'subjes', 'etaRange': '0eta320', 'topo': [], 'threshold': '400', 'chainPartName': 'ht400', 'recoAlg': 'a4', 'trigType': 'ht', 'bConfig': [], 'multiplicity': '1', 'scan': 'FS', 'L1item': '', 'signature': 'HT', 'calib': 'em', 'addInfo': [], 'dataScouting': ''}], 'topo': [], 'chainCounter': 432, 'groups': ['RATE:MultiJet', 'BW:Jets'], 'signature': 'HT', 'topoStartFrom': False, 'L1item': 'L1_HT150-J20s5.ETA30', 'chainName': 'ht400'},
]
