# -- CUT FROM THIS POINT UPWARDS --
# This dump was automatically generated by myopt
# User fwinkl (Frank WINKLMEIER (PH)) at Wed Apr  2 13:58:10 2008

# All options should be inside the 'option' dictionary
# The keys being the long name of the options and the
# values, the new default to be attributed.
option = {}

# ================================
# 'Data' options 
# ================================

# python-list of input files
files = [ "myBS._0001.data",
          "myBS._0002.data"]

#path = "/afs/cern.ch/atlas/project/trigger/pesa-sw/validation/RTT/data/BS/"
path = "/castor/cern.ch/grid/atlas/atlasgroupdisk/trig-daq/user/igrabows/EnhancedMinBiasBS/"
option['file'] = []
for f in files:
  option['file'] += [path + f]

