#include "InDetCompetingRIOsOnTrackTool/CompetingTRT_DriftCirclesOnTrackTool.h"
#include "InDetCompetingRIOsOnTrackTool/CompetingPixelClustersOnTrackTool.h"
#include "InDetCompetingRIOsOnTrackTool/CompetingSCT_ClustersOnTrackTool.h"

DECLARE_NAMESPACE_TOOL_FACTORY( InDet, CompetingTRT_DriftCirclesOnTrackTool )
DECLARE_NAMESPACE_TOOL_FACTORY( InDet, CompetingPixelClustersOnTrackTool )
DECLARE_NAMESPACE_TOOL_FACTORY( InDet, CompetingSCT_ClustersOnTrackTool )

