#include "ALFA_SimEv/ALFA_HitCollection.h"
#include "ALFA_SimEv/ALFA_Hit.h"
#include "ALFA_SimEv/ALFA_ODHitCollection.h"
#include "ALFA_SimEv/ALFA_ODHit.h"

DECLARE_ALGORITHM_FACTORY(ALFA_Hit)
DECLARE_ALGORITHM_FACTORY(ALFA_HitCollection)
DECLARE_ALGORITHM_FACTORY(ALFA_ODHit)
DECLARE_ALGORITHM_FACTORY(ALFA_ODHitCollection)

