#include "ALFA_SimEv/ALFA_HitCollection.h"
#include "ALFA_SimEv/ALFA_Hit.h"
#include "ALFA_SimEv/ALFA_ODHitCollection.h"
#include "ALFA_SimEv/ALFA_ODHit.h"
#include "GaudiKernel/DeclareFactoryEntries.h"

DECLARE_ALGORITHM_FACTORY(ALFA_Hit)
DECLARE_ALGORITHM_FACTORY(ALFA_HitCollection)
DECLARE_ALGORITHM_FACTORY(ALFA_ODHit)
DECLARE_ALGORITHM_FACTORY(ALFA_ODHitCollection)

DECLARE_FACTORY_ENTRIES(ALFA_SimEv) {
DECLARE_ALGORITHM(ALFA_Hit)
DECLARE_ALGORITHM(ALFA_HitCollection)
DECLARE_ALGORITHM(ALFA_ODHit)
DECLARE_ALGORITHM(ALFA_ODHitCollection)
}
 