# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addService

addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosInnerWheelCalibrationCalculator","EMECPosInnerWheelCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegInnerWheelCalibrationCalculator","EMECNegInnerWheelCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosOuterWheelCalibrationCalculator","EMECPosOuterWheelCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegOuterWheelCalibrationCalculator","EMECNegOuterWheelCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosBackOuterBarretteCalibrationCalculator","EMECPosBackOuterBarretteCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegBackOuterBarretteCalibrationCalculator","EMECNegBackOuterBarretteCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPresamplerCalibrationCalculator","EMECPresamplerCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEndcapCryostatCalibrationCalculator","EndcapCryostatCalibrationCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEndcapCryostatCalibrationLArCalculator","EndcapCryostatCalibrationLArCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEndcapCryostatCalibrationMixedCalculator","EndcapCryostatCalibrationMixedCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECSupportCalibrationCalculator","EMECSupportCalibrationCalculator")

addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosInnerWheelCalculator","EMECPosInnerWheelCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegInnerWheelCalculator","EMECNegInnerWheelCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosOuterWheelCalculator","EMECPosOuterWheelCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegOuterWheelCalculator","EMECNegOuterWheelCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosBackOuterBarretteCalculator","EMECPosBackOuterBarretteCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegBackOuterBarretteCalculator","EMECNegBackOuterBarretteCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosInnerWheelCorrOffCalculator","EMECPosInnerWheelCorrOffCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegInnerWheelCorrOffCalculator","EMECNegInnerWheelCorrOffCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosOuterWheelCorrOffCalculator","EMECPosOuterWheelCorrOffCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegOuterWheelCorrOffCalculator","EMECNegOuterWheelCorrOffCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPosBackOuterBarretteCorrOffCalculator","EMECPosBackOuterBarretteCorrOffCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECNegBackOuterBarretteCorrOffCalculator","EMECNegBackOuterBarretteCorrOffCalculator")
addService("LArG4EC.LArG4ECConfigLegacy.getEMECPresamplerCalculator","EMECPresamplerCalculator")

addService("LArG4EC.LArG4ECConfigLegacy.getEMECPresamplerGeometry","EMECPresamplerGeometry")
