# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addTool
addTool("G4AtlasTools.G4AtlasToolsConfigLegacy.getFastSimulationMasterTool","FastSimulationMasterTool")
addTool("G4AtlasTools.G4AtlasToolsConfigLegacy.getEmptyFastSimulationMasterTool","EmptyFastSimulationMasterTool")
addTool("G4AtlasTools.G4AtlasToolsConfigLegacy.getEmptySensitiveDetectorMasterTool","EmptySensitiveDetectorMasterTool")
addTool("G4AtlasTools.G4AtlasToolsConfigLegacy.getSensitiveDetectorMasterTool","SensitiveDetectorMasterTool")

addTool("G4AtlasTools.G4GeometryConfigLegacy.getBeamPipeGeoDetectorTool", 'BeamPipe')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getPixelGeoDetectorTool", 'Pixel')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getSCTGeoDetectorTool", 'SCT')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getTRTGeoDetectorTool", 'TRT')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getIDetServicesMatGeoDetectorTool", 'IDetServicesMat')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getLArMgrGeoDetectorTool", 'LArMgr')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getTileGeoDetectorTool", 'Tile')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getLucidGeoDetectorTool", 'Lucid')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getALFAGeoDetectorTool", 'ALFA')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getZDCGeoDetectorTool", 'ZDC')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getAFPGeoDetectorTool", 'AFP')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getFwdRegionGeoDetectorTool", 'FwdRegion')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getMuonGeoDetectorTool", 'Muon')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getCavernInfraGeoDetectorTool", 'CavernInfra')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getIDETEnvelope", "IDET")
addTool("G4AtlasTools.G4GeometryConfigLegacy.getCALOEnvelope", "CALO")
addTool("G4AtlasTools.G4GeometryConfigLegacy.getForwardRegionEnvelope", 'ForwardRegion')
addTool("G4AtlasTools.G4GeometryConfigLegacy.getMUONEnvelope", "MUONQ02") #FIXME rename to MUON when safe
addTool("G4AtlasTools.G4GeometryConfigLegacy.getCosmicShortCut", "CosmicShortCut")
addTool("G4AtlasTools.G4GeometryConfigLegacy.getATLAS", "Atlas")
addTool("G4AtlasTools.G4GeometryConfigLegacy.getCavernWorld", "Cavern")
addTool("G4AtlasTools.G4GeometryConfigLegacy.getG4AtlasDetectorConstructionTool", "G4AtlasDetectorConstructionTool")
addTool("G4AtlasTools.G4GeometryConfigLegacy.getMaterialDescriptionTool", "MaterialDescriptionTool")
addTool("G4AtlasTools.G4GeometryConfigLegacy.getVoxelDensityTool", "VoxelDensityTool")

addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_Beampipe1", "TileTB_BeamPipe1")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_Beampipe2", "TileTB_BeamPipe2")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_MYLAREQUIV", "TileTB_MYLAREQUIV")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_S1", "TileTB_S1")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_S2", "TileTB_S2")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_S3", "TileTB_S3")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_CALOEnvelope", "TileTB_CALO")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getTileTB_WorldEnvelope", "TileTB_World")
addTool("G4AtlasTools.G4TestBeamGeometryConfigLegacy.getLArTB_WorldEnvelope", "LArTB_World")

addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getBeampipeFwdCutPhysicsRegionTool", 'BeampipeFwdCutPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getFWDBeamLinePhysicsRegionTool", 'FWDBeamLinePhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getFwdRegionPhysicsRegionTool", 'FwdRegionPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getPixelPhysicsRegionTool", 'PixelPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getSCTPhysicsRegionTool", 'SCTPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getTRTPhysicsRegionTool", 'TRTPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getTRT_ArPhysicsRegionTool", 'TRT_ArPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getTRT_KrPhysicsRegionTool", 'TRT_KrPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getCALOPhysicsRegionTool", 'CALOPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getEMBPhysicsRegionTool", 'EMBPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getEMECPhysicsRegionTool", 'EMECPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getHECPhysicsRegionTool", 'HECPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getFCALPhysicsRegionTool", 'FCALPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getEMECParaPhysicsRegionTool", 'EMECParaPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getFCALParaPhysicsRegionTool", 'FCALParaPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getFCAL2ParaPhysicsRegionTool", 'FCAL2ParaPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getPreSampLArPhysicsRegionTool", 'PreSampLArPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getDeadMaterialPhysicsRegionTool", 'DeadMaterialPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getDriftWallPhysicsRegionTool", 'DriftWallPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getDriftWall1PhysicsRegionTool", 'DriftWall1PhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getDriftWall2PhysicsRegionTool", 'DriftWall2PhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getMuonSystemFastPhysicsRegionTool", 'MuonSystemFastPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getMuonPhysicsRegionTool", "MuonPhysicsRegionTool")
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getSX1PhysicsRegionTool", 'SX1PhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getBedrockPhysicsRegionTool", 'BedrockPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getCavernShaftsConcretePhysicsRegionTool", 'CavernShaftsConcretePhysicsRegionTool')
##addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getCavernShaftsAirPhysicsRegionTool", 'CavernShaftsAirPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfigLegacy.getSCTSiliconPhysicsRegionTool", 'SCTSiliconPhysicsRegionTool')

addTool("G4AtlasTools.G4FieldConfigLegacy.getATLASFieldManagerTool", 'ATLASFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getTightMuonsATLASFieldManagerTool", 'TightMuonsATLASFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getClassicFieldManagerTool", 'ClassicFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getBeamPipeFieldManagerTool", 'BeamPipeFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getInDetFieldManagerTool", 'InDetFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getMuonsOnlyInCaloFieldManagerTool", 'MuonsOnlyInCaloFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getMuonFieldManagerTool", 'MuonFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ1FwdFieldMangerTool", 'Q1FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ2FwdFieldMangerTool", 'Q2FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ3FwdFieldMangerTool", 'Q3FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getD1FwdFieldMangerTool", 'D1FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getD2FwdFieldMangerTool", 'D2FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ4FwdFieldMangerTool", 'Q4FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ5FwdFieldMangerTool", 'Q5FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ6FwdFieldMangerTool", 'Q6FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ7FwdFieldMangerTool", 'Q7FwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ1HKickFwdFieldMangerTool", 'Q1HKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ1VKickFwdFieldMangerTool", 'Q1VKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ2HKickFwdFieldMangerTool", 'Q2HKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ2VKickFwdFieldMangerTool", 'Q2VKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ3HKickFwdFieldMangerTool", 'Q3HKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ3VKickFwdFieldMangerTool", 'Q3VKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ4VKickAFwdFieldMangerTool", 'Q4VKickAFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ4HKickFwdFieldMangerTool", 'Q4HKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ4VKickBFwdFieldMangerTool", 'Q4VKickBFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ5HKickFwdFieldMangerTool", 'Q5HKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getQ6VKickFwdFieldMangerTool", 'Q6VKickFwdFieldManager')
addTool("G4AtlasTools.G4FieldConfigLegacy.getFwdRegionFieldMangerTool", 'FwdRegionFieldManager')
