# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addTool
addTool("G4AtlasTools.G4AtlasToolsConfig.getFastSimulationMasterTool","FastSimulationMasterTool")
addTool("G4AtlasTools.G4AtlasToolsConfig.getEmptyFastSimulationMasterTool","EmptyFastSimulationMasterTool")
addTool("G4AtlasTools.G4AtlasToolsConfig.getEmptySensitiveDetectorMasterTool","EmptySensitiveDetectorMasterTool")
addTool("G4AtlasTools.G4AtlasToolsConfig.getSensitiveDetectorMasterTool","SensitiveDetectorMasterTool")
addTool("G4AtlasTools.G4AtlasToolsConfig.getPhysicsListToolBase","PhysicsListToolBase")

addTool("G4AtlasTools.G4GeometryConfig.getBeamPipeGeoDetectorTool", 'BeamPipe')
addTool("G4AtlasTools.G4GeometryConfig.getPixelGeoDetectorTool", 'Pixel')
addTool("G4AtlasTools.G4GeometryConfig.getSCTGeoDetectorTool", 'SCT')
addTool("G4AtlasTools.G4GeometryConfig.getTRTGeoDetectorTool", 'TRT')
addTool("G4AtlasTools.G4GeometryConfig.getIDetServicesMatGeoDetectorTool", 'IDetServicesMat')
addTool("G4AtlasTools.G4GeometryConfig.getLArMgrGeoDetectorTool", 'LArMgr')
addTool("G4AtlasTools.G4GeometryConfig.getTileGeoDetectorTool", 'Tile')
addTool("G4AtlasTools.G4GeometryConfig.getLucidGeoDetectorTool", 'Lucid')
addTool("G4AtlasTools.G4GeometryConfig.getALFAGeoDetectorTool", 'ALFA')
addTool("G4AtlasTools.G4GeometryConfig.getZDCGeoDetectorTool", 'ZDC')
addTool("G4AtlasTools.G4GeometryConfig.getAFPGeoDetectorTool", 'AFP')
addTool("G4AtlasTools.G4GeometryConfig.getFwdRegionGeoDetectorTool", 'FwdRegion')
addTool("G4AtlasTools.G4GeometryConfig.getMuonGeoDetectorTool", 'Muon')
addTool("G4AtlasTools.G4GeometryConfig.getCavernInfraGeoDetectorTool", 'CavernInfra')
addTool("G4AtlasTools.G4GeometryConfig.getIDETEnvelope", "IDET")
addTool("G4AtlasTools.G4GeometryConfig.getCALOEnvelope", "CALO")
addTool("G4AtlasTools.G4GeometryConfig.getForwardRegionEnvelope", 'ForwardRegion')
addTool("G4AtlasTools.G4GeometryConfig.getMUONEnvelope", "MUONQ02") #FIXME rename to MUON when safe
addTool("G4AtlasTools.G4GeometryConfig.getCosmicShortCut", "CosmicShortCut")
addTool("G4AtlasTools.G4GeometryConfig.getATLAS", "Atlas")
addTool("G4AtlasTools.G4GeometryConfig.getCavernWorld", "Cavern")
addTool("G4AtlasTools.G4GeometryConfig.getG4AtlasDetectorConstructionTool", "G4AtlasDetectorConstructionTool")

addTool("G4AtlasTools.G4TestBeamGeometryConfig.getTileTB_CALOEnvelope", "TileTB_CALO")
addTool("G4AtlasTools.G4TestBeamGeometryConfig.getTileTB_WorldEnvelope", "TileTB_World")
addTool("G4AtlasTools.G4TestBeamGeometryConfig.getLArTB_WorldEnvelope", "LArTB_World")

addTool("G4AtlasTools.G4PhysicsRegionConfig.getBeampipeFwdCutPhysicsRegionTool", 'BeampipeFwdCutPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getFWDBeamLinePhysicsRegionTool", 'FWDBeamLinePhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getFwdRegionPhysicsRegionTool", 'FwdRegionPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getPixelPhysicsRegionTool", 'PixelPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getSCTPhysicsRegionTool", 'SCTPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getTRTPhysicsRegionTool", 'TRTPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getTRT_ArPhysicsRegionTool", 'TRT_ArPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getTRT_KrPhysicsRegionTool", 'TRT_KrPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getEMBPhysicsRegionTool", 'EMBPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getEMECPhysicsRegionTool", 'EMECPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getHECPhysicsRegionTool", 'HECPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getFCALPhysicsRegionTool", 'FCALPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getEMECParaPhysicsRegionTool", 'EMECParaPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getFCALParaPhysicsRegionTool", 'FCALParaPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getFCAL2ParaPhysicsRegionTool", 'FCAL2ParaPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getPreSampLArPhysicsRegionTool", 'PreSampLArPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getDeadMaterialPhysicsRegionTool", 'DeadMaterialPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getDriftWallPhysicsRegionTool", 'DriftWallPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getDriftWall1PhysicsRegionTool", 'DriftWall1PhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getDriftWall2PhysicsRegionTool", 'DriftWall2PhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getMuonSystemFastPhysicsRegionTool", 'MuonSystemFastPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getMuonPhysicsRegionTool", "MuonPhysicsRegionTool")
addTool("G4AtlasTools.G4PhysicsRegionConfig.getSX1PhysicsRegionTool", 'SX1PhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getBedrockPhysicsRegionTool", 'BedrockPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getCavernShaftsConcretePhysicsRegionTool", 'CavernShaftsConcretePhysicsRegionTool')
##addTool("G4AtlasTools.G4PhysicsRegionConfig.getCavernShaftsAirPhysicsRegionTool", 'CavernShaftsAirPhysicsRegionTool')
addTool("G4AtlasTools.G4PhysicsRegionConfig.getSCTSiliconPhysicsRegionTool", 'SCTSiliconPhysicsRegionTool')
