#!/bin/csh -f 
#
set thisdir = ${0:gh}
cd $thisdir 
set thisdir = $cwd
cd -
#
# define default CLIDDB if not defined by user
#
if( ! $?CLIDDB )then
    setenv CLIDDB ${thisdir}/clid.db
endif
if( ! -f $CLIDDB )then
    echo "You must point to a CLID database with CLIDDB."
endif
#
# make sure Python is good version - try CERN default if not
#
set isgp = `python -c 'import sys;print (sys.hexversion >= 0x20000f0)'`
if( 0 == ${isgp} )then
    set path = ( /usr/local/bin $path )
    rehash
    set isgp = `python -c 'import sys;print (sys.hexversion >= 0x20000f0)'`
    if( 0 == ${isgp} )then
        echo "clid ERROR -- Cannot find good Python (2.0.0 or higher)."
        echo "              Please change PATH and try again."
        exit 0
    endif
endif
#
# 
${thisdir}/clid.py $*
#
