TrigBjetValidation_Histos : 	TrigBjetValidation_Histos.cpp
				g++ -g -Wall -o $@ $@.cpp Ntuple.cpp RoIBase.cpp RoI.cpp `root-config --cflags` `root-config --glibs` -lMinuit
clean 			  :		
				rm -rf *.o *~  TrigBjetValidation_Histos

