!
 CHARACTER(800) FUNCTION COMPOS_CAR800(L,NAM)
 IMPLICIT NONE
 CHARACTER (len=*) :: NAM(*)
 INTEGER           :: L,K
!
   COMPOS_CAR800 = TRIM(NAM(1)) // '/'
   DO K=2,L
     IF( LEN_TRIM(NAM(K)) <= 0 ) CYCLE
     COMPOS_CAR800 = TRIM(COMPOS_CAR800) // TRIM(NAM(K)) // '/'
   ENDDO
!
 END
!
