!
 LOGICAL FUNCTION IS_IT_REMOVED(CAR80)
 USE M_MB_Xml
 IMPLICIT NONE
 CHARACTER(80), INTENT(IN) :: CAR80
 INTEGER       :: I
!
   IS_IT_REMOVED = .False.
   DO I=2,Nb_xml_vis
     IF( CAR80 /= Nam_xml_vis(I) ) CYCLE
     IS_IT_REMOVED = .True.
     EXIT
   ENDDO
!
 END FUNCTION IS_IT_REMOVED
!
