/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

// Generated by runAnalyzeRate.py
#include <vector>
#include <string>
#include "Log.h"
void runAnalyzeRate() {
  gSystem->Load("TrigJpsiRootAnalysis_cpp.so");
  TrigJpsiRootAnalysis analysis(INFO, "/net/s3_datac/scheiric/data/output_TrigDiMuonCalib/2010-06-25/rootfiles/");
  analysis.analyzeRate("L2_MU4_DiMu_FS", " TrackCollName=\"MuidMuonCollectionTracks\"  MuonCollName=\"MuidMuonCollection\" ", "HypoNMuHits(3) HypoNMuHits(3) DoNMuHitsScan(1) DoChi2Scan(1) HypoCheckOS(1) Level1(L2_mu0_missingRoi) JpsiMass(2000,5000) JpsiChi2Prob(0.05) TrkChi2OnNdf(3.5) MuonPt(2800) MuonE(3000) MuonPixHits(1) MuonSctHits(6) MuonTypes(ONE_COMB) ");
}
