# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

AntiKt10UFOCSSKRecursiveSoftDropBeta100Zcut5NinfJetsCPContent = [
"AntiKt10UFOCSSKRecursiveSoftDropBeta100Zcut5NinfJets",
"AntiKt10UFOCSSKRecursiveSoftDropBeta100Zcut5NinfJetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt10UFOCSSKRecursiveSoftDropBeta100Zcut5NinfJetsAux.ECF1.ECF2.ECF3.Tau1_wta.Tau2_wta.Tau3_wta.Split12.Split23.Qw.PlanarFlow.FoxWolfram2.FoxWolfram0.Angularity.Aplanarity.KtDR.ZCut12",
"AntiKt10UFOCSSKRecursiveSoftDropBeta100Zcut5NinfJetsAux.Parent.DetectorEta.DetectorY",
"AntiKt10UFOCSSKRecursiveSoftDropBeta100Zcut5NinfJetsAux.R10TruthLabel_R21Consolidated.R10TruthLabel_R21Precision.R10TruthLabel_R21Precision_2022v1",
"AntiKt10UFOCSSKJets",
"AntiKt10UFOCSSKJetsAux.NumTrkPt500",
"AntiKt10TruthRecursiveSoftDropBeta100Zcut5NinfJets.pt.eta.phi.m.ECF1.ECF2.ECF3.Tau2_wta.Tau3_wta.Qw.GhostCHadronsFinalCount.GhostBHadronsFinalCount",
]
