# Copyright (C) 2002-2020 CERN for the benefit of the ATLAS collaboration

AntiKt10TrackCaloClusterTrimmedPtFrac5SmallR20JetsCPContent = [
"AntiKt10TrackCaloClusterTrimmedPtFrac5SmallR20Jets",
"AntiKt10TrackCaloClusterTrimmedPtFrac5SmallR20JetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt10TrackCaloClusterTrimmedPtFrac5SmallR20JetsAux.ECF1.ECF2.ECF3.Tau1_wta.Tau2_wta.Tau3_wta.Split12.Split23.Qw.PlanarFlow.FoxWolfram2.FoxWolfram0.Angularity.Aplanarity.KtDR.ZCut12",
"AntiKt10TrackCaloClusterTrimmedPtFrac5SmallR20JetsAux.NTrimSubjets.Parent.DetectorEta.DetectorY",
"AntiKt10TrackCaloClusterTrimmedPtFrac5SmallR20JetsAux.GhostAntiKt2TrackJet.GhostCHadronsFinalCount.GhostBHadronsFinalCount",
"AntiKt10TrackCaloClusterTrimmedPtFrac5SmallR20JetsAux.R10TruthLabel_R21Consolidated.R10TruthLabel_R21Precision",
"AntiKt10TrackCaloClusterJets",
"AntiKt10TrackCaloClusterJetsAux.GhostAntiKt2TrackJet.GhostVR30Rmax4Rmin02TrackJet.NumTrkPt500",
"AntiKt10TruthTrimmedPtFrac5SmallR20Jets.pt.eta.phi.m.ECF1.ECF2.ECF3.Tau2_wta.Tau3_wta.Qw.GhostCHadronsFinalCount.GhostBHadronsFinalCount",
]
