# Copyright (C) 2002-2020 CERN for the benefit of the ATLAS collaboration

AntiKt10LCTopoTrimmedPtFrac5SmallR20JetsCPContent = [
"AntiKt10LCTopoTrimmedPtFrac5SmallR20Jets",
"AntiKt10LCTopoTrimmedPtFrac5SmallR20JetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt10LCTopoTrimmedPtFrac5SmallR20JetsAux.ECF1.ECF2.ECF3.Tau1_wta.Tau2_wta.Tau3_wta.Split12.Split23.Qw.PlanarFlow.FoxWolfram2.FoxWolfram0.Angularity.Aplanarity.KtDR.ZCut12",
"AntiKt10LCTopoTrimmedPtFrac5SmallR20JetsAux.NTrimSubjets.Parent.TrackSumPt.TrackSumMass.DetectorEta.DetectorY",
"AntiKt10LCTopoTrimmedPtFrac5SmallR20JetsAux.GhostAntiKt2TrackJet.GhostCHadronsFinalCount.GhostBHadronsFinalCount",
"AntiKt10LCTopoTrimmedPtFrac5SmallR20JetsAux.R10TruthLabel_R21Consolidated",
"AntiKt10LCTopoJets",
"AntiKt10LCTopoJetsAux.GhostAntiKt2TrackJet.GhostVR30Rmax4Rmin02TrackJet.GhostVR30Rmax4Rmin02TrackJetGhostTag.GhostVR30Rmax4Rmin02TrackJet_BTagging201810.GhostVR30Rmax4Rmin02TrackJet_BTagging201810GhostTag.GhostVR30Rmax4Rmin02TrackJet_BTagging201903.NumTrkPt500",
"AntiKt10TruthTrimmedPtFrac5SmallR20Jets.pt.eta.phi.m.ECF1.ECF2.ECF3.Tau2_wta.Tau3_wta.Qw.GhostCHadronsFinalCount.GhostBHadronsFinalCount",
]
