# Copyright (C) 2002-2020 CERN for the benefit of the ATLAS collaboration

AntiKt10TrackCaloClusterJetsCPContent = [
"AntiKt10TrackCaloClusterJets",
"AntiKt10TrackCaloClusterJetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt10TrackCaloClusterJetsAux.DetectorEta.DetectorY",
"AntiKt10TrackCaloClusterJetsAux.GhostBHadronsFinalCount.GhostHBosonsCount.GhostTQuarksFinalCount.GhostTrack.GhostWBosonsCount.GhostZBosonsCount",
"AntiKt10TrackCaloClusterJetsAux.GhostVR30Rmax4Rmin02TrackJet.GhostVR30Rmax4Rmin02TrackJetGhostTag.GhostVR30Rmax4Rmin02TrackJet_BTagging201810.GhostVR30Rmax4Rmin02TrackJet_BTagging201810GhostTag.GhostVR30Rmax4Rmin02TrackJet_BTagging201903",
"AntiKt10TrackCaloClusterJetsAux.HadronConeExclExtendedTruthLabelID.HadronConeExclTruthLabelID.NumTrkPt500.SumPtTrkPt500",
]
