# Copyright (C) 2002-2020 CERN for the benefit of the ATLAS collaboration

AntiKt10EMPFlowCSSKSoftDropBeta100Zcut10JetsCPContent = [
"AntiKt10EMPFlowCSSKSoftDropBeta100Zcut10Jets",
"AntiKt10EMPFlowCSSKSoftDropBeta100Zcut10JetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt10EMPFlowCSSKSoftDropBeta100Zcut10JetsAux.DetectorEta.DetectorY"
]
