# Copyright (C) 2002-2019 CERN for the benefit of the ATLAS collaboration

AntiKt10UFOCHSJetsCPContent = [
    "AntiKt10UFOCHSJets",
    "AntiKt10UFOCHSJetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m.PartonTruthLabelID.DetectorEta.DetectorY.GhostBHadronsFinalCount.GhostHBosonsCount.GhostTQuarksFinalCount.GhostTrack.GhostWBosonsCount.GhostZBosonsCount.GhostVR30Rmax4Rmin02TrackJet.GhostVR30Rmax4Rmin02TrackJetGhostTag.GhostVR30Rmax4Rmin02TrackJet_BTagging201903.HadronConeExclExtendedTruthLabelID.HadronConeExclTruthLabelID.NumTrkPt500.SumPtTrkPt500"
]
