# Copyright (C) 2002-2020 CERN for the benefit of the ATLAS collaboration

AntiKt10LCTopoJetsCPContent = [
"AntiKt10LCTopoJets",
"AntiKt10LCTopoJetsAux.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m",
"AntiKt10LCTopoJetsAux.PartonTruthLabelID.DetectorEta.DetectorY",
"AntiKt10LCTopoJetsAux.GhostBHadronsFinalCount.GhostHBosonsCount.GhostTQuarksFinalCount.GhostTrack.GhostWBosonsCount.GhostZBosonsCount",
"AntiKt10LCTopoJetsAux.GhostVR30Rmax4Rmin02TrackJet.GhostVR30Rmax4Rmin02TrackJetGhostTag.GhostVR30Rmax4Rmin02TrackJet_BTagging201810.GhostVR30Rmax4Rmin02TrackJet_BTagging201810GhostTag.GhostVR30Rmax4Rmin02TrackJet_BTagging201903",
"AntiKt10LCTopoJetsAux.HadronConeExclExtendedTruthLabelID.HadronConeExclTruthLabelID.NumTrkPt500.SumPtTrkPt500",
]
