# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

METCPContent = [
"AntiKt4LCTopoJets",
"AntiKt4LCTopoJetsAux.pt.eta.phi.m.JetConstitScaleMomentum_pt.JetConstitScaleMomentum_eta.JetConstitScaleMomentum_phi.JetConstitScaleMomentum_m.GhostTrack.JVF",
"Electrons",
"ElectronsAux.trackParticleLinks.pt.phi",
"GSFConversionVertices",
"GSFConversionVerticesAux.trackParticleLinks",
"GSFTrackParticles",
"GSFTrackParticlesAux.originalTrackParticle",
"InDetTrackParticles",
"InDetTrackParticlesAux.phi.d0.z0.theta.qOverP.vz.numberOfPixelHits.numberOfSCTHits",
"METMap_RefFinal",
"METMap_RefFinalAux.metLink.objectLinks.wpx.wpy.wet",
"MET_Reference_AntiKt4LCTopo",
"MET_Reference_AntiKt4LCTopoAux.mpx.mpy.sumet.name.source",
"Muons",
"MuonsAux.pt.phi.inDetTrackParticleLink",
"Photons",
"PhotonsAux.pt.phi.vertexLinks",
"PrimaryVertices",
"PrimaryVerticesAux.z",
"TauJets",
"TauJetsAux.pt.phi.trackLinks.otherTrackLinks.jetLink",
]
