# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

## Hit-track matching cut-cone constants. Generated by TrigDiMuonRootCalib

Cone_Endcap_mdt_inner_dEta_c0=1.31139
Cone_Endcap_mdt_inner_dEta_c1=0.454728

Cone_Endcap_mdt_middle_dEta_c0=108.977
Cone_Endcap_mdt_middle_dEta_c1=0.896695

Cone_Barrel_mdt_inner_dEta_c0=5.49691
Cone_Barrel_mdt_inner_dEta_c1=0.608204

Cone_Barrel_mdt_middle_dEta_c0=43.9614
Cone_Barrel_mdt_middle_dEta_c1=0.801908

Cone_rpc_middle_dEta_c0=10.3862
Cone_rpc_middle_dEta_c1=0.632877

Cone_rpc_middle_dPhi_c0=116.531
Cone_rpc_middle_dPhi_c1=0.91477

Cone_tgc_wire_inner_dEta_c0=9.6       # old parametrization
Cone_tgc_wire_inner_dEta_c1=0.7472

Cone_tgc_wire_middle_dEta_c0=66.288
Cone_tgc_wire_middle_dEta_c1=0.842429

Cone_tgc_strip_inner_dPhi_c0=24.11    # old param
Cone_tgc_strip_inner_dPhi_c1=0.85588

Cone_tgc_strip_middle_dPhi_c0=15.5733
Cone_tgc_strip_middle_dPhi_c1=0.636304

Cone_tgc_strip_middle2_dPhi_c0=39.0207
Cone_tgc_strip_middle2_dPhi_c1=0.806018

