#!/bin/python

# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
##-----------------------------------------------------------
##
## runConvertChain.py
##
## Configuration script for TriggerJpsiAnalysis
## Creates ROOT macro with desired configuration,
##
## author: Daniel Scheirich <scheiric@cern.ch>
## Part of TriggerJpsiAnalysis in TrigBphysValidation package
##
##-----------------------------------------------------------
import string, os

##-----------------------------------------------------------
## Basic settings
##-----------------------------------------------------------

chain        = "L2_MU4_DiMu"  # name of the chain that should be analyzed
outputLevel  = "INFO"                 # output level: "DEBUG", "INFO", "WARNING", "ERROR"
execute      = True                   # execute macro

##-----------------------------------------------------------
## More settings
##-----------------------------------------------------------
## add flags to the settings string to activate features
##    gaus+const                        fit J/psi mass with Gaussian + constant
##    gaus+pol1                         fit J/psi mass with Gaussian + linear polynomial
##    fitMin=2000 fitMax=5000           defines fit range
##    massBinLo=8 massBinHi=13          bins berween which efficiency is calculated

settings     = "gaus+pol1 fitMin=2000 fitMax=5000 massBinLo=8 massBinHi=13"
settings    += ' ConstantsFile=\\"constants.py\\" '
settings    += ' OutputFile=\\"'+chain+'.09.root\\" '

##-----------------------------------------------------------
## Input files
##-----------------------------------------------------------
## You can either specify list of files explicitly using inFileNames
## or you can load entire directory using dirPath vatiable

## list of input files created by TriggerJpsiAnalysis algorithm
inFileNames  = [ ]
inFileNames += [ "/net/s3_datac/scheiric/data/output_TrigDiMuonCalib/2010-06-25/rootfiles/user.scheiric.14.data10_7TeV_MuonswBeam.00154810.TrigDiMuonCalib.bphys.root" ]
#inFileNames += [ "/net/s3_datac/scheiric/data/output_TrigDiMuonCalib/2010-06-25/rootfiles/user.scheiric.14.data10_7TeV_MuonswBeam.00155112.TrigDiMuonCalib.bphys.root" ]

## directory containing root files created by TriggerJpsiAnalysis algorithm
#dirPath       = "/net/s3_datac/scheiric/data/output_TrigDiMuonCalib/2010-06-25/rootfiles"

##-----------------------------------------
## Main script -- DO NOT EDIT !
##-----------------------------------------
## Jpsi selection cuts
import jpsiCuts

## add J/psi cuts
cutStr = ""
for cut in jpsiCuts.cuts:
  cutStr += cut + " "

## generate root macro

macro   = ""
macro   += "// Generated by runConvertChain.py\n"
macro   += "#include <vector>\n"
macro   += "#include <string>\n"
macro   += "#include \"Log.h\"\n"
macro   += "void runConvertChain() {\n"
macro   += "  gSystem->Load(\"TrigDiMuonRootCalib_cpp.so\");\n"
if('dirPath' in dir()):
  macro   += "  TrigDiMuonRootCalib analysis(" + outputLevel + ", \"" + dirPath + "\");\n"

else:
  macro   += "  std::vector<std::string> files;\n"
  for file in inFileNames :
    macro += "  files.push_back( \"" + file + "\" );\n"
  macro   += "  TrigDiMuonRootCalib analysis(" + outputLevel + ", files);\n"

macro   += "  analysis.convertChain(\""+ chain +"\", \""+ settings +"\", \""+ cutStr +"\");\n"
macro   += "}\n"

## create macro
f = open("runConvertChain.C","w")
f.write(macro)
f.close()

## execute root macro
if(execute) :
  os.system( "root -l runConvertChain.C" )

## end of script



