# Author: Max Baak (mbaak@cern.ch)

PACKAGE          = GoodRunsLists
PACKAGE_PRELOAD  = Tree TreePlayer XMLParser XMLIO
PACKAGE_TRYDEP   = AsgTools xAODEventInfo PathResolver AsgAnalysisInterfaces
PACKAGE_CXXFLAGS = -I/usr/include/libxml2
PACKAGE_BINFLAGS = -lxml2
PACKAGE_PEDANTIC = 1
PACKAGE_REFLEX   = 1

include $(ROOTCOREDIR)/Makefile-common
