#! /bin/bash
#
#   Use xmllint to concatenate all files into one big file suitable for storage in the geometry data base as a blob.
#

# We need a link to the dtd here since ITkStrip.gmx refers to it here.
if [ ! -f "geomodel.dtd" ]
then
   ln ../../../geomodel.dtd geomodel.dtd
fi

#
#
#
upToDate=`svn status -q`
if [ -z "$upToDate" ]
then
  # Get any newer files, and at the same time change my revision to the newest
  svn update
  xmllint --noent --valid ITkStrip.gmx > LTF_StripBlobRev`svn info | grep Revision | cut --field=2 --delimiter=" "`.xml
else
  echo "The following files have been modified and not yet committed. Do an svn commit first!"
  echo $upToDate
fi