# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration 

SUSY8SmartContent = [
        "AntiKt4EMTopoJets",
        "AntiKt4EMPFlowJets",
        "Electrons",
	"InDetTrackParticles",
        "Muons",
        "Photons",
        "MET_Reference_AntiKt4EMTopo",
        "MET_Reference_AntiKt4EMPFlow",
        "PrimaryVertices"
]
	
SUSY8ExtraVariables = [
        "TauJets.pt",
        "TauJets.eta",
        "TauJets.phi",
        "TauJets.m",
	"AntiKt4TruthJets.eta",
	"AntiKt4TruthJets.m",
	"AntiKt4TruthJets.phi",
	"AntiKt4TruthJets.pt",
	"AntiKt4TruthJets.ConeTruthLabelID",
	"AntiKt4TruthJets.HadronConeExclTruthLabelID",
	"AntiKt4TruthJets.PartonTruthLabelID",
	"AntiKt4TruthJets.TruthLabelDeltaR_B",
	"AntiKt4TruthJets.TruthLabelDeltaR_C",
	"AntiKt4TruthJets.TruthLabelDeltaR_T",
	"AntiKt4TruthJets.TruthLabelID",
	"InDetTrackParticles.SUSY8_CaloCellE",
        "InDetTrackParticles.SUSY8_CaloCellEta",
        "InDetTrackParticles.SUSY8_CaloCellGain",
        "InDetTrackParticles.SUSY8_CaloCellID",
        "InDetTrackParticles.SUSY8_CaloCellPhi",
        "InDetTrackParticles.SUSY8_CaloCellProvenance",
        "InDetTrackParticles.SUSY8_CaloCellQuality",
        "InDetTrackParticles.SUSY8_CaloCellR",
        "InDetTrackParticles.SUSY8_CaloCellSampling",
        "InDetTrackParticles.SUSY8_CaloCellTime",
        "InDetTrackParticles.SUSY8_CaloCellX",
        "InDetTrackParticles.SUSY8_CaloCellY",
        "InDetTrackParticles.SUSY8_CaloCellZ",
        "InDetTrackParticles.SUSY8_CaloCelldEta",
        "InDetTrackParticles.SUSY8_CaloCelldPhi",
        "InDetTrackParticles.SUSY8_CaloCelldR",
        "InDetTrackParticles.SUSY8_CaloCelldX",
        "InDetTrackParticles.SUSY8_CaloCelldY",
        "InDetTrackParticles.SUSY8_CaloCelldZ",
        "InDetTrackParticles.numberOfIBLOverflowsdEdx",
        "InDetTrackParticles.numberOfPixelSplitHits",
        "InDetTrackParticles.numberOfUsedHitsdEdx",
        "InDetTrackParticles.pixeldEdx",
        "InDetTrackParticles.TRTdEdx",
        "InDetTrackParticles.TRTdEdxUsedHits"
]
	
SUSY8AllVariablesContent = [
        "CombinedMuonTrackParticles",
        "CombinedStauTrackParticles",
        "METAssoc_AntiKt4EMTopo",
        "MET_Calo",
        "MET_Core_AntiKt4EMTopo",
        "MET_EMTopo",
        "MET_LocHadTopo",
        "MET_Track",                          
        #"MET_Truth",                          
        "MSonlyTracklets",                    
        "MuonSegments",                       
        "MuonSpectrometerTrackParticles",     
        "SlowMuons",                          
        "Staus"
        #"TruthEvents",
        #"TruthParticles",
        #"TruthVertices"
]
