!
!> Sorts real*8 array TT in the order given in the integer array NORDRE
!
 PURE SUBROUTINE REORDO(TT,NORDRE,NLONG)
 IMPLICIT NONE
 REAL(8), INTENT(INOUT) :: TT(*)
 INTEGER, INTENT(IN)    :: NORDRE(*), NLONG
!
    TT(1:NLONG) = TT(NORDRE(1:NLONG))
!
 END SUBROUTINE REORDO
!
!
!> Sorts integer array II in the order given in the integer array NORDRE
!
 PURE SUBROUTINE IEORDO(II,NORDRE,NLONG)
 IMPLICIT NONE
 INTEGER, INTENT(INOUT) :: II(*)
 INTEGER, INTENT(IN)    :: NORDRE(*), NLONG
!
    II(1:NLONG) = II(NORDRE(1:NLONG))
!
 END SUBROUTINE IEORDO
!
