#!/usr/bin/env bash

# Send an email reporting any failed jobs in last 24 hours

logdir=/afs/cern.ch/user/a/atlidbs/cron/log/`date '+%Y-%m'`
mkdir -p $logdir
log=$logdir/`date '+check-failed-%G-%m-%d-%H-%M.log'`
touch $log

source /afs/cern.ch/user/a/atlidbs/cron/cronsetup.sh   >> $log 2>&1
cd /afs/cern.ch/user/a/atlidbs/jobs

taskman.py --runtaskname DB_BEAMSPOT notifyFailed 86400 
