#!/usr/bin/env bash

# Make lists of runs per period

logdir=/afs/cern.ch/user/a/atlidbs/cron/log/`date '+%Y-%m'`
mkdir -p $logdir
log=$logdir/`date '+make-periods-%G-%m-%d-%H-%M.log'`
touch $log

source /afs/cern.ch/user/a/atlidbs/cron/cronsetup.sh   >> $log 2>&1
cd /afs/cern.ch/user/a/atlidbs/jobs

periodInfo.py -c /afs/cern.ch/user/a/atlidbs/private/atlidbs-only/ami.conf >> $log 2>&1

echo "" >> $log 2>&1
echo "Running getLatestRuns.py ..." >> $log 2>&1
getLatestRuns.py 2419200 LastMonth >> $log 2>&1
getLatestRuns.py 604800 LastWeek >> $log 2>&1

echo "" >> $log 2>&1
echo "Making plot for last week" >> $log 2>&1
plotdir=/afs/cern.ch/user/a/atlidbs/nt/webplots/
plotname=$plotdir/summary-weekly-tmp
beamspotnt.py -b -f /afs/cern.ch/user/a/atlidbs/nt/cool/beamspotnt-COOL-Current.root -o $plotname.eps,$plotname.pdf,$plotname.gif --perioddef /afs/cern.ch/user/a/atlidbs/nt/DataPeriods --period data_latest.LastWeek --timeaxis summary >> $log 2>&1
mv $plotname.eps $plotdir/summary-weekly.eps >> $log 2>&1
mv $plotname.pdf $plotdir/summary-weekly.pdf >> $log 2>&1
mv $plotname.gif $plotdir/summary-weekly.gif >> $log 2>&1

echo "" >> $log 2>&1
echo "Making plot for last month" >> $log 2>&1
plotnameW=$plotdir/summary-monthly-tmp
beamspotnt.py -b -f /afs/cern.ch/user/a/atlidbs/nt/cool/beamspotnt-COOL-Current.root -o $plotnameW.eps,$plotnameW.pdf,$plotnameW.gif --perioddef /afs/cern.ch/user/a/atlidbs/nt/DataPeriods --period data_latest.LastMonth --timeaxis summary >> $log 2>&1
mv $plotnameW.eps $plotdir/summary-monthly.eps >> $log 2>&1
mv $plotnameW.pdf $plotdir/summary-monthly.pdf >> $log 2>&1
mv $plotnameW.gif $plotdir/summary-monthly.gif >> $log 2>&1

