####################
## File configLumi_run219305.py: autogenerated configuration file from command
##/afs/cern.ch/atlas/software/builds/nightlies/devval/AtlasSimulation/rel_3/InstallArea/share/bin/RunDepTaskMaker.py --externalDict={0.000001: 37.0, 0.25: 731.0, 0.5: 225.0, 0.15: 554.0, 0.2: 746.0, 0.4: 398.0, 0.8: 6.0, 0.3: 637.0, 0.6: 84.0, 0.1: 366.0, 0.45: 286.0, 0.35: 545.0, 0.05: 91.0, 0.7: 39.0, 0.55: 176.0, 0.65: 54.0, 0.75: 25.0} --lumimethod=EXTERNAL --nMC=1 --trigger=L1_MBTS_2 --outfile=configLumi_run219305.py overlap_grl_219305.275-219305.766.xml
## Created on Tue Mar 19 14:56:49 2013
####################
#Run-dependent digi job configuration file.
#RunDependentSimData/OverrideRunLBLumiDigitConfig.py

#We need to be able to adjust for different dataset sizes.
if not 'ScaleTaskLength' in dir():   ScaleTaskLength = 1
_evts = lambda x: int(ScaleTaskLength * x)

if not 'logging' in dir(): import logging
digilog = logging.getLogger('Digi_trf')
digilog.info('doing RunLumiOverride configuration from file.')
JobMaker=[
   {'run':219305, 'lb':275, 'starttstamp':1360705402, 'dt':0.000, 'evts':_evts(37), 'mu':0.000001, 'force_new':False}, #edited to avoid mu=0 bug
   {'run':219305, 'lb':276, 'starttstamp':1360705463, 'dt':0.000, 'evts':_evts(731), 'mu':0.250, 'force_new':False},
   {'run':219305, 'lb':277, 'starttstamp':1360705512, 'dt':0.000, 'evts':_evts(84), 'mu':0.600, 'force_new':False},
   {'run':219305, 'lb':278, 'starttstamp':1360705573, 'dt':0.000, 'evts':_evts(746), 'mu':0.200, 'force_new':False},
   {'run':219305, 'lb':279, 'starttstamp':1360705637, 'dt':0.000, 'evts':_evts(225), 'mu':0.500, 'force_new':False},
   {'run':219305, 'lb':280, 'starttstamp':1360705699, 'dt':0.000, 'evts':_evts(6), 'mu':0.800, 'force_new':False},
   {'run':219305, 'lb':281, 'starttstamp':1360705760, 'dt':0.000, 'evts':_evts(637), 'mu':0.300, 'force_new':False},
   {'run':219305, 'lb':282, 'starttstamp':1360705821, 'dt':0.000, 'evts':_evts(554), 'mu':0.150, 'force_new':False},
   {'run':219305, 'lb':283, 'starttstamp':1360705882, 'dt':0.000, 'evts':_evts(398), 'mu':0.400, 'force_new':False},
   {'run':219305, 'lb':284, 'starttstamp':1360705943, 'dt':0.000, 'evts':_evts(25), 'mu':0.750, 'force_new':False},
   {'run':219305, 'lb':285, 'starttstamp':1360706004, 'dt':0.000, 'evts':_evts(286), 'mu':0.450, 'force_new':False},
   {'run':219305, 'lb':286, 'starttstamp':1360706065, 'dt':0.000, 'evts':_evts(545), 'mu':0.350, 'force_new':False},
   {'run':219305, 'lb':287, 'starttstamp':1360706126, 'dt':0.000, 'evts':_evts(91), 'mu':0.050, 'force_new':False},
   {'run':219305, 'lb':288, 'starttstamp':1360706187, 'dt':0.000, 'evts':_evts(366), 'mu':0.100, 'force_new':False},
   {'run':219305, 'lb':289, 'starttstamp':1360706248, 'dt':0.000, 'evts':_evts(39), 'mu':0.700, 'force_new':False},
   {'run':219305, 'lb':290, 'starttstamp':1360706309, 'dt':0.000, 'evts':_evts(176), 'mu':0.550, 'force_new':False},
   {'run':219305, 'lb':291, 'starttstamp':1360706370, 'dt':0.000, 'evts':_evts(54), 'mu':0.650, 'force_new':False},
#--> end hiding
]

include('RunDependentSimData/configCommon.py')

#cleanup python memory
if not "RunDMC_testing_configuration" in dir():
    del JobMaker
