####################
## File configLumi_Run180164_9LB.py: autogenerated configuration file from command
##/afs/cern.ch/user/a/ayana/scratch0/devval/InstallArea/share/bin/RunDepTaskMaker.py --externalDict={3.75:.0276, 4.25:.1241, 4.75:.1681, 5.25:.2261, 5.75:.2075, 6.25:.1538, 6.75:.0730, 7.25:.0153, 7.75:.0045} --lumimethod=EXTERNAL --outfile=configLumi_Run180164_9LB.py run180164.xml
## Created on Thu Jun 30 19:35:39 2011
####################
#Run-dependent digi job configuration file.
#SimuJobTransforms/ConfigLumi_preOptions.py

#We need to be able to adjust for different dataset sizes.
if not 'ScaleTaskLength' in dir():   ScaleTaskLength = 1
_evts = lambda x: int(ScaleTaskLength * x)

if not 'logging' in dir(): import logging
digilog = logging.getLogger('Digi_trf')
digilog.info('doing RunLumiOverride configuration from file.')
JobMaker=[
   {'run':180164, 'lb':67, 'starttstamp':1303554669, 'dt':0.000, 'evts':_evts(276), 'mu':3.750, 'force_new':False},
   {'run':180164, 'lb':68, 'starttstamp':1303554730, 'dt':0.000, 'evts':_evts(1241), 'mu':4.250, 'force_new':False},
   {'run':180164, 'lb':69, 'starttstamp':1303554791, 'dt':0.000, 'evts':_evts(730), 'mu':6.750, 'force_new':False},
   {'run':180164, 'lb':70, 'starttstamp':1303554852, 'dt':0.000, 'evts':_evts(1681), 'mu':4.750, 'force_new':False},
   {'run':180164, 'lb':71, 'starttstamp':1303554913, 'dt':0.000, 'evts':_evts(153), 'mu':7.250, 'force_new':False},
   {'run':180164, 'lb':73, 'starttstamp':1303555035, 'dt':0.000, 'evts':_evts(45), 'mu':7.750, 'force_new':False},
   {'run':180164, 'lb':74, 'starttstamp':1303555062, 'dt':0.000, 'evts':_evts(2075), 'mu':5.750, 'force_new':False},
   {'run':180164, 'lb':75, 'starttstamp':1303555090, 'dt':0.000, 'evts':_evts(1538), 'mu':6.250, 'force_new':False},
   {'run':180164, 'lb':76, 'starttstamp':1303555151, 'dt':0.000, 'evts':_evts(2261), 'mu':5.250, 'force_new':False},
#--> end hiding
]

include('RunDependentSimData/configCommon.py')

del JobMaker
