####################
## File configLumi_calibXfer.py: autogenerated configuration file from command
##/afs/cern.ch/atlas/software/releases/17.0.6/AtlasSimulation/17.0.6/InstallArea/share/bin/RunDepTaskMaker.py --externalDict={1.0: 665.0, 2.0: 665.0, 3.0: 131.0, 4.0: 131.0, 5.0: 131.0, 6.0: 131.0, 7.0: 131.0, 8.0: 131.0, 9.0: 131.0, 10.0: 131.0, 11.0: 131.0, 12.0: 131.0, 13.0: 131.0, 14.0: 131.0, 15.0: 131.0, 16.0: 131.0, 17.0: 131.0, 18.0: 131.0, 19.0: 131.0, 20.0: 131.0, 21.0: 131.0, 22.0: 131.0, 23.0: 131.0, 24.0: 131.0, 25.0: 131.0, 26.0: 131.0, 27.0: 131.0, 28.0: 131.0, 29.0: 131.0, 30.0: 131.0} --lumimethod=EXTERNAL --nMC=1 --trigger=L1_MBTS_2 --outfile=configLumi_calibXfer.py run195847.xml
## Created on Tue Mar 20 18:23:22 2012
####################
#Run-dependent digi job configuration file.
#RunDependentSimData/OverrideRunLBLumiDigitConfig.py

#We need to be able to adjust for different dataset sizes.
if not 'ScaleTaskLength' in dir():   ScaleTaskLength = 1
_evts = lambda x: int(ScaleTaskLength * x)

if not 'logging' in dir(): import logging
digilog = logging.getLogger('Digi_trf')
digilog.info('doing RunLumiOverride configuration from file.')
JobMaker=[
   {'run':195847, 'lb':1, 'starttstamp':1328039085, 'dt':0.000, 'evts':_evts(665), 'mu':1.000, 'force_new':False},
   {'run':195847, 'lb':2, 'starttstamp':1328039152, 'dt':0.000, 'evts':_evts(665), 'mu':2.000, 'force_new':False},
   {'run':195847, 'lb':3, 'starttstamp':1328039213, 'dt':0.000, 'evts':_evts(131), 'mu':3.000, 'force_new':False},
   {'run':195847, 'lb':4, 'starttstamp':1328039274, 'dt':0.000, 'evts':_evts(131), 'mu':4.000, 'force_new':False},
   {'run':195847, 'lb':5, 'starttstamp':1328039335, 'dt':0.000, 'evts':_evts(131), 'mu':5.000, 'force_new':False},
   {'run':195847, 'lb':6, 'starttstamp':1328039396, 'dt':0.000, 'evts':_evts(131), 'mu':6.000, 'force_new':False},
   {'run':195847, 'lb':7, 'starttstamp':1328039457, 'dt':0.000, 'evts':_evts(131), 'mu':7.000, 'force_new':False},
   {'run':195847, 'lb':8, 'starttstamp':1328039518, 'dt':0.000, 'evts':_evts(131), 'mu':8.000, 'force_new':False},
   {'run':195847, 'lb':9, 'starttstamp':1328039579, 'dt':0.000, 'evts':_evts(131), 'mu':9.000, 'force_new':False},
   {'run':195847, 'lb':10, 'starttstamp':1328039640, 'dt':0.000, 'evts':_evts(131), 'mu':10.000, 'force_new':False},
   {'run':195847, 'lb':11, 'starttstamp':1328039701, 'dt':0.000, 'evts':_evts(131), 'mu':11.000, 'force_new':False},
   {'run':195847, 'lb':12, 'starttstamp':1328039762, 'dt':0.000, 'evts':_evts(131), 'mu':12.000, 'force_new':False},
   {'run':195847, 'lb':13, 'starttstamp':1328039823, 'dt':0.000, 'evts':_evts(131), 'mu':13.000, 'force_new':False},
   {'run':195847, 'lb':14, 'starttstamp':1328039884, 'dt':0.000, 'evts':_evts(131), 'mu':14.000, 'force_new':False},
   {'run':195847, 'lb':15, 'starttstamp':1328039945, 'dt':0.000, 'evts':_evts(131), 'mu':15.000, 'force_new':False},
   {'run':195847, 'lb':16, 'starttstamp':1328040006, 'dt':0.000, 'evts':_evts(131), 'mu':16.000, 'force_new':False},
   {'run':195847, 'lb':17, 'starttstamp':1328040067, 'dt':0.000, 'evts':_evts(131), 'mu':17.000, 'force_new':False},
   {'run':195847, 'lb':18, 'starttstamp':1328040128, 'dt':0.000, 'evts':_evts(131), 'mu':18.000, 'force_new':False},
   {'run':195847, 'lb':19, 'starttstamp':1328040189, 'dt':0.000, 'evts':_evts(131), 'mu':19.000, 'force_new':False},
   {'run':195847, 'lb':20, 'starttstamp':1328040250, 'dt':0.000, 'evts':_evts(131), 'mu':20.000, 'force_new':False},
   {'run':195847, 'lb':21, 'starttstamp':1328040311, 'dt':0.000, 'evts':_evts(131), 'mu':21.000, 'force_new':False},
   {'run':195847, 'lb':22, 'starttstamp':1328040372, 'dt':0.000, 'evts':_evts(131), 'mu':22.000, 'force_new':False},
   {'run':195847, 'lb':23, 'starttstamp':1328040433, 'dt':0.000, 'evts':_evts(131), 'mu':23.000, 'force_new':False},
   {'run':195847, 'lb':24, 'starttstamp':1328040494, 'dt':0.000, 'evts':_evts(131), 'mu':24.000, 'force_new':False},
   {'run':195847, 'lb':25, 'starttstamp':1328040555, 'dt':0.000, 'evts':_evts(131), 'mu':25.000, 'force_new':False},
   {'run':195847, 'lb':26, 'starttstamp':1328040616, 'dt':0.000, 'evts':_evts(131), 'mu':26.000, 'force_new':False},
   {'run':195847, 'lb':27, 'starttstamp':1328040677, 'dt':0.000, 'evts':_evts(131), 'mu':27.000, 'force_new':False},
   {'run':195847, 'lb':28, 'starttstamp':1328040738, 'dt':0.000, 'evts':_evts(131), 'mu':28.000, 'force_new':False},
   {'run':195847, 'lb':29, 'starttstamp':1328040799, 'dt':0.000, 'evts':_evts(131), 'mu':29.000, 'force_new':False},
   {'run':195847, 'lb':30, 'starttstamp':1328040860, 'dt':0.000, 'evts':_evts(131), 'mu':30.000, 'force_new':False},
#--> end hiding
]

include('RunDependentSimData/configCommon.py')

#cleanup python memory
if not "RunDMC_testing_configuration" in dir():
    del JobMaker
