####################
## File configLumi_run195847_mu27.py: autogenerated configuration file from command
##/afs/cern.ch/atlas/software/builds/AtlasSimulation/17.0.5/InstallArea/share/bin/RunDepTaskMaker.py --externalDict={27.0: 5000.0} --lumimethod=EXTERNAL --nMC=1 --trigger=L1_MBTS_2 --outfile=configLumi_run195847_mu27.py run195847.xml
## Created on Tue Aug 28 22:47:00 2012
####################
#Run-dependent digi job configuration file.
#RunDependentSimData/OverrideRunLBLumiDigitConfig.py

#We need to be able to adjust for different dataset sizes.
if not 'ScaleTaskLength' in dir():   ScaleTaskLength = 1
_evts = lambda x: int(ScaleTaskLength * x)

if not 'logging' in dir(): import logging
digilog = logging.getLogger('Digi_trf')
digilog.info('doing RunLumiOverride configuration from file.')
JobMaker=[
   {'run':195847, 'lb':1, 'starttstamp':1328039085, 'dt':0.000, 'evts':_evts(5000), 'mu':27.000, 'force_new':False},
#--> end hiding
]

include('RunDependentSimData/configCommon.py')

#cleanup python memory
if not "RunDMC_testing_configuration" in dir():
    del JobMaker
