####################
## File all191.py: autogenerated configuration file from command
##/afs/cern.ch/user/a/ayana/scratch0/MC11/InstallArea/share/bin/RunDepTaskMaker.py --externalDict={23.5: 250, 25.5: 250, 32.5: 250, 28.5: 250, 29.5: 250, 24.5: 250, 32.0: 250, 31.0: 250, 30.5: 250, 31.5: 250, 27.5: 250, 23.0: 250, 24.0: 250, 25.0: 250, 26.0: 250, 27.0: 250, 28.0: 250, 29.0: 250, 30.0: 250, 26.5: 250} --lumimethod=EXTERNAL --nMC=1 --trigger=L1_MBTS_2 --outfile=all191.py 191628.xml
## Created on Wed Dec 14 22:10:09 2011
####################
#Run-dependent digi job configuration file.
#RunDependentSimData/OverrideRunLBLumiDigitConfig.py

#We need to be able to adjust for different dataset sizes.
if not 'ScaleTaskLength' in dir():   ScaleTaskLength = 1
_evts = lambda x: int(ScaleTaskLength * x)

if not 'logging' in dir(): import logging
digilog = logging.getLogger('Digi_trf')
digilog.info('doing RunLumiOverride configuration from file.')
JobMaker=[
   {'run':191628, 'lb':126, 'starttstamp':1319552726, 'dt':0.000, 'evts':_evts(250), 'mu':23.000, 'force_new':False},
   {'run':191628, 'lb':127, 'starttstamp':1319552787, 'dt':0.000, 'evts':_evts(250), 'mu':23.500, 'force_new':False},
   {'run':191628, 'lb':128, 'starttstamp':1319552848, 'dt':0.000, 'evts':_evts(250), 'mu':24.000, 'force_new':False},
   {'run':191628, 'lb':129, 'starttstamp':1319552909, 'dt':0.000, 'evts':_evts(250), 'mu':24.500, 'force_new':False},
   {'run':191628, 'lb':130, 'starttstamp':1319552970, 'dt':0.000, 'evts':_evts(250), 'mu':25.000, 'force_new':False},
   {'run':191628, 'lb':131, 'starttstamp':1319553031, 'dt':0.000, 'evts':_evts(250), 'mu':25.500, 'force_new':False},
   {'run':191628, 'lb':132, 'starttstamp':1319553092, 'dt':0.000, 'evts':_evts(250), 'mu':26.000, 'force_new':False},
   {'run':191628, 'lb':133, 'starttstamp':1319553153, 'dt':0.000, 'evts':_evts(250), 'mu':26.500, 'force_new':False},
   {'run':191628, 'lb':134, 'starttstamp':1319553214, 'dt':0.000, 'evts':_evts(250), 'mu':27.000, 'force_new':False},
   {'run':191628, 'lb':135, 'starttstamp':1319553275, 'dt':0.000, 'evts':_evts(250), 'mu':27.500, 'force_new':False},
   {'run':191628, 'lb':136, 'starttstamp':1319553336, 'dt':0.000, 'evts':_evts(250), 'mu':28.000, 'force_new':False},
   {'run':191628, 'lb':137, 'starttstamp':1319553397, 'dt':0.000, 'evts':_evts(250), 'mu':28.500, 'force_new':False},
   {'run':191628, 'lb':138, 'starttstamp':1319553458, 'dt':0.000, 'evts':_evts(250), 'mu':29.000, 'force_new':False},
   {'run':191628, 'lb':139, 'starttstamp':1319553519, 'dt':0.000, 'evts':_evts(250), 'mu':29.500, 'force_new':False},
   {'run':191628, 'lb':140, 'starttstamp':1319553580, 'dt':0.000, 'evts':_evts(250), 'mu':30.000, 'force_new':False},
   {'run':191628, 'lb':141, 'starttstamp':1319553641, 'dt':0.000, 'evts':_evts(250), 'mu':30.500, 'force_new':False},
   {'run':191628, 'lb':142, 'starttstamp':1319553702, 'dt':0.000, 'evts':_evts(250), 'mu':31.000, 'force_new':False},
   {'run':191628, 'lb':143, 'starttstamp':1319553763, 'dt':0.000, 'evts':_evts(250), 'mu':31.500, 'force_new':False},
   {'run':191628, 'lb':144, 'starttstamp':1319553824, 'dt':0.000, 'evts':_evts(250), 'mu':32.000, 'force_new':False},
   {'run':191628, 'lb':145, 'starttstamp':1319553885, 'dt':0.000, 'evts':_evts(250), 'mu':32.500, 'force_new':False},
#--> end hiding
]

include('RunDependentSimData/configCommon.py')

#cleanup python memory
if not "RunDMC_testing_configuration" in dir():
    del JobMaker
