####################
## File all190.py: autogenerated configuration file from command
##/afs/cern.ch/user/a/ayana/scratch0/MC11/InstallArea/share/bin/RunDepTaskMaker.py --externalDict={20.5: 250, 21.5: 250, 28.5: 250, 29.5: 250, 22.5: 250, 28.0: 250, 24.5: 250, 27.5: 250, 25.5: 250, 20.0: 250, 21.0: 250, 22.0: 250, 23.0: 250, 24.0: 250, 25.0: 250, 26.0: 250, 27.0: 250, 26.5: 250, 29.0: 250, 23.5: 250} --lumimethod=EXTERNAL --nMC=1 --trigger=L1_MBTS_2 --outfile=all190.py 190728.xml
## Created on Wed Dec 14 22:10:16 2011
####################
#Run-dependent digi job configuration file.
#RunDependentSimData/OverrideRunLBLumiDigitConfig.py

#We need to be able to adjust for different dataset sizes.
if not 'ScaleTaskLength' in dir():   ScaleTaskLength = 1
_evts = lambda x: int(ScaleTaskLength * x)

if not 'logging' in dir(): import logging
digilog = logging.getLogger('Digi_trf')
digilog.info('doing RunLumiOverride configuration from file.')
JobMaker=[
   {'run':190728, 'lb':108, 'starttstamp':1318253359, 'dt':0.000, 'evts':_evts(250), 'mu':20.000, 'force_new':False},
   {'run':190728, 'lb':109, 'starttstamp':1318253421, 'dt':0.000, 'evts':_evts(250), 'mu':20.500, 'force_new':False},
   {'run':190728, 'lb':110, 'starttstamp':1318253481, 'dt':0.000, 'evts':_evts(250), 'mu':21.000, 'force_new':False},
   {'run':190728, 'lb':111, 'starttstamp':1318253542, 'dt':0.000, 'evts':_evts(250), 'mu':21.500, 'force_new':False},
   {'run':190728, 'lb':112, 'starttstamp':1318253603, 'dt':0.000, 'evts':_evts(250), 'mu':22.000, 'force_new':False},
   {'run':190728, 'lb':113, 'starttstamp':1318253663, 'dt':0.000, 'evts':_evts(250), 'mu':22.500, 'force_new':False},
   {'run':190728, 'lb':114, 'starttstamp':1318253724, 'dt':0.000, 'evts':_evts(250), 'mu':23.000, 'force_new':False},
   {'run':190728, 'lb':115, 'starttstamp':1318253785, 'dt':0.000, 'evts':_evts(250), 'mu':23.500, 'force_new':False},
   {'run':190728, 'lb':116, 'starttstamp':1318253797, 'dt':0.000, 'evts':_evts(250), 'mu':24.000, 'force_new':False},
   {'run':190728, 'lb':117, 'starttstamp':1318253857, 'dt':0.000, 'evts':_evts(250), 'mu':24.500, 'force_new':False},
   {'run':190728, 'lb':118, 'starttstamp':1318253918, 'dt':0.000, 'evts':_evts(250), 'mu':25.000, 'force_new':False},
   {'run':190728, 'lb':119, 'starttstamp':1318253979, 'dt':0.000, 'evts':_evts(250), 'mu':25.500, 'force_new':False},
   {'run':190728, 'lb':120, 'starttstamp':1318254041, 'dt':0.000, 'evts':_evts(250), 'mu':26.000, 'force_new':False},
   {'run':190728, 'lb':121, 'starttstamp':1318254101, 'dt':0.000, 'evts':_evts(250), 'mu':26.500, 'force_new':False},
   {'run':190728, 'lb':122, 'starttstamp':1318254162, 'dt':0.000, 'evts':_evts(250), 'mu':27.000, 'force_new':False},
   {'run':190728, 'lb':123, 'starttstamp':1318254173, 'dt':0.000, 'evts':_evts(250), 'mu':27.500, 'force_new':False},
   {'run':190728, 'lb':124, 'starttstamp':1318254234, 'dt':0.000, 'evts':_evts(250), 'mu':28.000, 'force_new':False},
   {'run':190728, 'lb':125, 'starttstamp':1318254295, 'dt':0.000, 'evts':_evts(250), 'mu':28.500, 'force_new':False},
   {'run':190728, 'lb':126, 'starttstamp':1318254356, 'dt':0.000, 'evts':_evts(250), 'mu':29.000, 'force_new':False},
   {'run':190728, 'lb':127, 'starttstamp':1318254417, 'dt':0.000, 'evts':_evts(250), 'mu':29.500, 'force_new':False},
#--> end hiding
]

include('RunDependentSimData/configCommon.py')

#cleanup python memory
if not "RunDMC_testing_configuration" in dir():
    del JobMaker
