# Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration
####################
## File configLumi_run300000_mc20d.py: autogenerated configuration file from command
##athena/Simulation/RunDependentSim/RunDependentSimComps/share/RunDepProfileGenerator.py -r 300000 -s 1500000000 -c 2000 -o configLumi_run300000_mc20d.py -e {0.5:1,1.5:1,2.5:1,3.5:1,4.5:1,5.5:1,6.5:1,7.5:1,8.5:1,9.5:1,10.5:1,11.5:1,12.5:3,13.5:4,14.5:6,15.5:9,16.5:12,17.5:16,18.5:21,19.5:27,20.5:32,21.5:38,22.5:44,23.5:49,24.5:54,25.5:57,26.5:60,27.5:63,28.5:65,29.5:67,30.5:69,31.5:69,32.5:70,33.5:69,34.5:67,35.5:65,36.5:62,37.5:58,38.5:54,39.5:50,40.5:46,41.5:42,42.5:38,43.5:35,44.5:32,45.5:30,46.5:27,47.5:27,48.5:27,49.5:27,50.5:28,51.5:30,52.5:32,53.5:33,54.5:33,55.5:33,56.5:31,57.5:29,58.5:26,59.5:23,60.5:20,61.5:16,62.5:13,63.5:10,64.5:7,65.5:5,66.5:3,67.5:2,68.5:1,69.5:1,70.5:1,71.5:1,72.5:1,73.5:1,74.5:1,75.5:1,76.5:1,77.5:1,78.5:1,79.5:1,80.5:1,81.5:1,82.5:1,83.5:1,84.5:1,85.5:1,86.5:1,87.5:1,88.5:1,89.5:1,90.5:1,91.5:0,92.5:0,93.5:0,94.5:0,95.5:0,96.5:0,97.5:0,98.5:0,99.5:0}
## Created on Wed Apr 21 16:09:50 2021
####################
#Run-dependent digi job configuration file.
#RunDependentSimData/OverrideRunLBLumiDigitConfig.py

#We need to be able to adjust for different dataset sizes.
if not 'ScaleTaskLength' in dir():   ScaleTaskLength = 1
_evts = lambda x: int(ScaleTaskLength * x)

if not 'logging' in dir(): import logging
digilog = logging.getLogger('Digi_trf')
digilog.info('doing RunLumiOverride configuration from file.')
JobMaker=[
  {'run':300000, 'lb':1, 'starttstamp':1500000000, 'evts':_evts(1), 'mu':0.500},
  {'run':300000, 'lb':2, 'starttstamp':1500000060, 'evts':_evts(1), 'mu':1.500},
  {'run':300000, 'lb':3, 'starttstamp':1500000120, 'evts':_evts(1), 'mu':2.500},
  {'run':300000, 'lb':4, 'starttstamp':1500000180, 'evts':_evts(1), 'mu':3.500},
  {'run':300000, 'lb':5, 'starttstamp':1500000240, 'evts':_evts(1), 'mu':4.500},
  {'run':300000, 'lb':6, 'starttstamp':1500000300, 'evts':_evts(1), 'mu':5.500},
  {'run':300000, 'lb':7, 'starttstamp':1500000360, 'evts':_evts(1), 'mu':6.500},
  {'run':300000, 'lb':8, 'starttstamp':1500000420, 'evts':_evts(1), 'mu':7.500},
  {'run':300000, 'lb':9, 'starttstamp':1500000480, 'evts':_evts(1), 'mu':8.500},
  {'run':300000, 'lb':10, 'starttstamp':1500000540, 'evts':_evts(1), 'mu':9.500},
  {'run':300000, 'lb':11, 'starttstamp':1500000600, 'evts':_evts(1), 'mu':10.500},
  {'run':300000, 'lb':12, 'starttstamp':1500000660, 'evts':_evts(1), 'mu':11.500},
  {'run':300000, 'lb':13, 'starttstamp':1500000720, 'evts':_evts(3), 'mu':12.500},
  {'run':300000, 'lb':14, 'starttstamp':1500000780, 'evts':_evts(4), 'mu':13.500},
  {'run':300000, 'lb':15, 'starttstamp':1500000840, 'evts':_evts(6), 'mu':14.500},
  {'run':300000, 'lb':16, 'starttstamp':1500000900, 'evts':_evts(9), 'mu':15.500},
  {'run':300000, 'lb':17, 'starttstamp':1500000960, 'evts':_evts(12), 'mu':16.500},
  {'run':300000, 'lb':18, 'starttstamp':1500001020, 'evts':_evts(16), 'mu':17.500},
  {'run':300000, 'lb':19, 'starttstamp':1500001080, 'evts':_evts(21), 'mu':18.500},
  {'run':300000, 'lb':20, 'starttstamp':1500001140, 'evts':_evts(27), 'mu':19.500},
  {'run':300000, 'lb':21, 'starttstamp':1500001200, 'evts':_evts(32), 'mu':20.500},
  {'run':300000, 'lb':22, 'starttstamp':1500001260, 'evts':_evts(38), 'mu':21.500},
  {'run':300000, 'lb':23, 'starttstamp':1500001320, 'evts':_evts(44), 'mu':22.500},
  {'run':300000, 'lb':24, 'starttstamp':1500001380, 'evts':_evts(49), 'mu':23.500},
  {'run':300000, 'lb':25, 'starttstamp':1500001440, 'evts':_evts(54), 'mu':24.500},
  {'run':300000, 'lb':26, 'starttstamp':1500001500, 'evts':_evts(57), 'mu':25.500},
  {'run':300000, 'lb':27, 'starttstamp':1500001560, 'evts':_evts(60), 'mu':26.500},
  {'run':300000, 'lb':28, 'starttstamp':1500001620, 'evts':_evts(63), 'mu':27.500},
  {'run':300000, 'lb':29, 'starttstamp':1500001680, 'evts':_evts(65), 'mu':28.500},
  {'run':300000, 'lb':30, 'starttstamp':1500001740, 'evts':_evts(67), 'mu':29.500},
  {'run':300000, 'lb':31, 'starttstamp':1500001800, 'evts':_evts(69), 'mu':30.500},
  {'run':300000, 'lb':32, 'starttstamp':1500001860, 'evts':_evts(69), 'mu':31.500},
  {'run':300000, 'lb':33, 'starttstamp':1500001920, 'evts':_evts(70), 'mu':32.500},
  {'run':300000, 'lb':34, 'starttstamp':1500001980, 'evts':_evts(69), 'mu':33.500},
  {'run':300000, 'lb':35, 'starttstamp':1500002040, 'evts':_evts(67), 'mu':34.500},
  {'run':300000, 'lb':36, 'starttstamp':1500002100, 'evts':_evts(65), 'mu':35.500},
  {'run':300000, 'lb':37, 'starttstamp':1500002160, 'evts':_evts(62), 'mu':36.500},
  {'run':300000, 'lb':38, 'starttstamp':1500002220, 'evts':_evts(58), 'mu':37.500},
  {'run':300000, 'lb':39, 'starttstamp':1500002280, 'evts':_evts(54), 'mu':38.500},
  {'run':300000, 'lb':40, 'starttstamp':1500002340, 'evts':_evts(50), 'mu':39.500},
  {'run':300000, 'lb':41, 'starttstamp':1500002400, 'evts':_evts(46), 'mu':40.500},
  {'run':300000, 'lb':42, 'starttstamp':1500002460, 'evts':_evts(42), 'mu':41.500},
  {'run':300000, 'lb':43, 'starttstamp':1500002520, 'evts':_evts(38), 'mu':42.500},
  {'run':300000, 'lb':44, 'starttstamp':1500002580, 'evts':_evts(35), 'mu':43.500},
  {'run':300000, 'lb':45, 'starttstamp':1500002640, 'evts':_evts(32), 'mu':44.500},
  {'run':300000, 'lb':46, 'starttstamp':1500002700, 'evts':_evts(30), 'mu':45.500},
  {'run':300000, 'lb':47, 'starttstamp':1500002760, 'evts':_evts(27), 'mu':46.500},
  {'run':300000, 'lb':48, 'starttstamp':1500002820, 'evts':_evts(27), 'mu':47.500},
  {'run':300000, 'lb':49, 'starttstamp':1500002880, 'evts':_evts(27), 'mu':48.500},
  {'run':300000, 'lb':50, 'starttstamp':1500002940, 'evts':_evts(27), 'mu':49.500},
  {'run':300000, 'lb':51, 'starttstamp':1500003000, 'evts':_evts(28), 'mu':50.500},
  {'run':300000, 'lb':52, 'starttstamp':1500003060, 'evts':_evts(30), 'mu':51.500},
  {'run':300000, 'lb':53, 'starttstamp':1500003120, 'evts':_evts(32), 'mu':52.500},
  {'run':300000, 'lb':54, 'starttstamp':1500003180, 'evts':_evts(33), 'mu':53.500},
  {'run':300000, 'lb':55, 'starttstamp':1500003240, 'evts':_evts(33), 'mu':54.500},
  {'run':300000, 'lb':56, 'starttstamp':1500003300, 'evts':_evts(33), 'mu':55.500},
  {'run':300000, 'lb':57, 'starttstamp':1500003360, 'evts':_evts(31), 'mu':56.500},
  {'run':300000, 'lb':58, 'starttstamp':1500003420, 'evts':_evts(29), 'mu':57.500},
  {'run':300000, 'lb':59, 'starttstamp':1500003480, 'evts':_evts(26), 'mu':58.500},
  {'run':300000, 'lb':60, 'starttstamp':1500003540, 'evts':_evts(23), 'mu':59.500},
  {'run':300000, 'lb':61, 'starttstamp':1500003600, 'evts':_evts(20), 'mu':60.500},
  {'run':300000, 'lb':62, 'starttstamp':1500003660, 'evts':_evts(16), 'mu':61.500},
  {'run':300000, 'lb':63, 'starttstamp':1500003720, 'evts':_evts(13), 'mu':62.500},
  {'run':300000, 'lb':64, 'starttstamp':1500003780, 'evts':_evts(10), 'mu':63.500},
  {'run':300000, 'lb':65, 'starttstamp':1500003840, 'evts':_evts(7), 'mu':64.500},
  {'run':300000, 'lb':66, 'starttstamp':1500003900, 'evts':_evts(5), 'mu':65.500},
  {'run':300000, 'lb':67, 'starttstamp':1500003960, 'evts':_evts(3), 'mu':66.500},
  {'run':300000, 'lb':68, 'starttstamp':1500004020, 'evts':_evts(2), 'mu':67.500},
  {'run':300000, 'lb':69, 'starttstamp':1500004080, 'evts':_evts(1), 'mu':68.500},
  {'run':300000, 'lb':70, 'starttstamp':1500004140, 'evts':_evts(1), 'mu':69.500},
  {'run':300000, 'lb':71, 'starttstamp':1500004200, 'evts':_evts(1), 'mu':70.500},
  {'run':300000, 'lb':72, 'starttstamp':1500004260, 'evts':_evts(1), 'mu':71.500},
  {'run':300000, 'lb':73, 'starttstamp':1500004320, 'evts':_evts(1), 'mu':72.500},
  {'run':300000, 'lb':74, 'starttstamp':1500004380, 'evts':_evts(1), 'mu':73.500},
  {'run':300000, 'lb':75, 'starttstamp':1500004440, 'evts':_evts(1), 'mu':74.500},
  {'run':300000, 'lb':76, 'starttstamp':1500004500, 'evts':_evts(1), 'mu':75.500},
  {'run':300000, 'lb':77, 'starttstamp':1500004560, 'evts':_evts(1), 'mu':76.500},
  {'run':300000, 'lb':78, 'starttstamp':1500004620, 'evts':_evts(1), 'mu':77.500},
  {'run':300000, 'lb':79, 'starttstamp':1500004680, 'evts':_evts(1), 'mu':78.500},
  {'run':300000, 'lb':80, 'starttstamp':1500004740, 'evts':_evts(1), 'mu':79.500},
  {'run':300000, 'lb':81, 'starttstamp':1500004800, 'evts':_evts(1), 'mu':80.500},
  {'run':300000, 'lb':82, 'starttstamp':1500004860, 'evts':_evts(1), 'mu':81.500},
  {'run':300000, 'lb':83, 'starttstamp':1500004920, 'evts':_evts(1), 'mu':82.500},
  {'run':300000, 'lb':84, 'starttstamp':1500004980, 'evts':_evts(1), 'mu':83.500},
  {'run':300000, 'lb':85, 'starttstamp':1500005040, 'evts':_evts(1), 'mu':84.500},
  {'run':300000, 'lb':86, 'starttstamp':1500005100, 'evts':_evts(1), 'mu':85.500},
  {'run':300000, 'lb':87, 'starttstamp':1500005160, 'evts':_evts(1), 'mu':86.500},
  {'run':300000, 'lb':88, 'starttstamp':1500005220, 'evts':_evts(1), 'mu':87.500},
  {'run':300000, 'lb':89, 'starttstamp':1500005280, 'evts':_evts(1), 'mu':88.500},
  {'run':300000, 'lb':90, 'starttstamp':1500005340, 'evts':_evts(1), 'mu':89.500},
  {'run':300000, 'lb':91, 'starttstamp':1500005400, 'evts':_evts(1), 'mu':90.500},
#--> end hiding
]

include('RunDependentSimData/configCommon.py')

#cleanup python memory
if not "RunDMC_testing_configuration" in dir():
    del JobMaker
