   std::vector<std::string> Keys;
   for (size_t i=0; i<5; ++i)
       Keys.push_back( "key_" + std::to_string(i) );
   std::vector<SGTObj_ATNGGE*> VEC_ATNGGE;
   std::vector<const SGTObj_ATNGGE*> CVEC_ATNGGE;
   CVEC_ATNGGE.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_ATNGGE.push_back( new SGTObj_ATNGGE(i) );
   std::vector<SGTObj_BJBLBR*> VEC_BJBLBR;
   std::vector<const SGTObj_BJBLBR*> CVEC_BJBLBR;
   CVEC_BJBLBR.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_BJBLBR.push_back( new SGTObj_BJBLBR(i) );
   std::vector<SGTObj_BKTYOQ*> VEC_BKTYOQ;
   std::vector<const SGTObj_BKTYOQ*> CVEC_BKTYOQ;
   CVEC_BKTYOQ.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_BKTYOQ.push_back( new SGTObj_BKTYOQ(i) );
   std::vector<SGTObj_DPGYLG*> VEC_DPGYLG;
   std::vector<const SGTObj_DPGYLG*> CVEC_DPGYLG;
   CVEC_DPGYLG.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_DPGYLG.push_back( new SGTObj_DPGYLG(i) );
   std::vector<SGTObj_EYDAJG*> VEC_EYDAJG;
   std::vector<const SGTObj_EYDAJG*> CVEC_EYDAJG;
   CVEC_EYDAJG.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_EYDAJG.push_back( new SGTObj_EYDAJG(i) );
   std::vector<SGTObj_EYMPLC*> VEC_EYMPLC;
   std::vector<const SGTObj_EYMPLC*> CVEC_EYMPLC;
   CVEC_EYMPLC.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_EYMPLC.push_back( new SGTObj_EYMPLC(i) );
   std::vector<SGTObj_FXFSTX*> VEC_FXFSTX;
   std::vector<const SGTObj_FXFSTX*> CVEC_FXFSTX;
   CVEC_FXFSTX.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_FXFSTX.push_back( new SGTObj_FXFSTX(i) );
   std::vector<SGTObj_HARVAQ*> VEC_HARVAQ;
   std::vector<const SGTObj_HARVAQ*> CVEC_HARVAQ;
   CVEC_HARVAQ.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_HARVAQ.push_back( new SGTObj_HARVAQ(i) );
   std::vector<SGTObj_HCVLPV*> VEC_HCVLPV;
   std::vector<const SGTObj_HCVLPV*> CVEC_HCVLPV;
   CVEC_HCVLPV.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_HCVLPV.push_back( new SGTObj_HCVLPV(i) );
   std::vector<SGTObj_JWKFRN*> VEC_JWKFRN;
   std::vector<const SGTObj_JWKFRN*> CVEC_JWKFRN;
   CVEC_JWKFRN.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_JWKFRN.push_back( new SGTObj_JWKFRN(i) );
   std::vector<SGTObj_NLDRUX*> VEC_NLDRUX;
   std::vector<const SGTObj_NLDRUX*> CVEC_NLDRUX;
   CVEC_NLDRUX.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_NLDRUX.push_back( new SGTObj_NLDRUX(i) );
   std::vector<SGTObj_OBMCVK*> VEC_OBMCVK;
   std::vector<const SGTObj_OBMCVK*> CVEC_OBMCVK;
   CVEC_OBMCVK.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_OBMCVK.push_back( new SGTObj_OBMCVK(i) );
   std::vector<SGTObj_PVVIGB*> VEC_PVVIGB;
   std::vector<const SGTObj_PVVIGB*> CVEC_PVVIGB;
   CVEC_PVVIGB.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_PVVIGB.push_back( new SGTObj_PVVIGB(i) );
   std::vector<SGTObj_QKXILL*> VEC_QKXILL;
   std::vector<const SGTObj_QKXILL*> CVEC_QKXILL;
   CVEC_QKXILL.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_QKXILL.push_back( new SGTObj_QKXILL(i) );
   std::vector<SGTObj_RBLMAX*> VEC_RBLMAX;
   std::vector<const SGTObj_RBLMAX*> CVEC_RBLMAX;
   CVEC_RBLMAX.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_RBLMAX.push_back( new SGTObj_RBLMAX(i) );
   std::vector<SGTObj_RKACSQ*> VEC_RKACSQ;
   std::vector<const SGTObj_RKACSQ*> CVEC_RKACSQ;
   CVEC_RKACSQ.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_RKACSQ.push_back( new SGTObj_RKACSQ(i) );
   std::vector<SGTObj_RNPHXT*> VEC_RNPHXT;
   std::vector<const SGTObj_RNPHXT*> CVEC_RNPHXT;
   CVEC_RNPHXT.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_RNPHXT.push_back( new SGTObj_RNPHXT(i) );
   std::vector<SGTObj_ROZIAH*> VEC_ROZIAH;
   std::vector<const SGTObj_ROZIAH*> CVEC_ROZIAH;
   CVEC_ROZIAH.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_ROZIAH.push_back( new SGTObj_ROZIAH(i) );
   std::vector<SGTObj_SDRAZA*> VEC_SDRAZA;
   std::vector<const SGTObj_SDRAZA*> CVEC_SDRAZA;
   CVEC_SDRAZA.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_SDRAZA.push_back( new SGTObj_SDRAZA(i) );
   std::vector<SGTObj_ZLDXKA*> VEC_ZLDXKA;
   std::vector<const SGTObj_ZLDXKA*> CVEC_ZLDXKA;
   CVEC_ZLDXKA.resize(5);
   for (size_t i=0; i<5; ++i)
       VEC_ZLDXKA.push_back( new SGTObj_ZLDXKA(i) );
