   for (size_t i=0; i<5; ++i) {
      pSG->record(VEC_ATNGGE[i], Keys[i]).ignore();
      pSG->record(VEC_BJBLBR[i], Keys[i]).ignore();
      pSG->record(VEC_BKTYOQ[i], Keys[i]).ignore();
      pSG->record(VEC_DPGYLG[i], Keys[i]).ignore();
      pSG->record(VEC_EYDAJG[i], Keys[i]).ignore();
      pSG->record(VEC_EYMPLC[i], Keys[i]).ignore();
      pSG->record(VEC_FXFSTX[i], Keys[i]).ignore();
      pSG->record(VEC_HARVAQ[i], Keys[i]).ignore();
      pSG->record(VEC_HCVLPV[i], Keys[i]).ignore();
      pSG->record(VEC_JWKFRN[i], Keys[i]).ignore();
      pSG->record(VEC_NLDRUX[i], Keys[i]).ignore();
      pSG->record(VEC_OBMCVK[i], Keys[i]).ignore();
      pSG->record(VEC_PVVIGB[i], Keys[i]).ignore();
      pSG->record(VEC_QKXILL[i], Keys[i]).ignore();
      pSG->record(VEC_RBLMAX[i], Keys[i]).ignore();
      pSG->record(VEC_RKACSQ[i], Keys[i]).ignore();
      pSG->record(VEC_RNPHXT[i], Keys[i]).ignore();
      pSG->record(VEC_ROZIAH[i], Keys[i]).ignore();
      pSG->record(VEC_SDRAZA[i], Keys[i]).ignore();
      pSG->record(VEC_ZLDXKA[i], Keys[i]).ignore();
   }
