   for (size_t i=0; i<5; ++i) {
      pSG->retrieve(CVEC_ATNGGE[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_BJBLBR[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_BKTYOQ[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_DPGYLG[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_EYDAJG[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_EYMPLC[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_FXFSTX[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_HARVAQ[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_HCVLPV[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_JWKFRN[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_NLDRUX[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_OBMCVK[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_PVVIGB[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_QKXILL[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_RBLMAX[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_RKACSQ[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_RNPHXT[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_ROZIAH[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_SDRAZA[i], Keys[i]).ignore();
      pSG->retrieve(CVEC_ZLDXKA[i], Keys[i]).ignore();
   }
