--
-- Create roles for various privileges and 
--   the associated group roles
-- J. Cranshaw 29.06.05
--
CREATE ROLE ATLAS_TAGS_ROME_WRITE;
CREATE ROLE ATLAS_TAGS_ROME_EDIT;
CREATE ROLE ATLAS_TAGS_ROME_INSERT;
CREATE ROLE ATLAS_TAGS_ROME_UPDATE;
CREATE ROLE ATLAS_TAGS_ROME_SELECT;
CREATE ROLE ATLAS_TAGS_ROME_DELETE;

GRANT ATLAS_TAGS_ROME_SELECT TO ATLAS_TAGS_ROME_WRITE;
GRANT ATLAS_TAGS_ROME_INSERT TO ATLAS_TAGS_ROME_WRITE;

GRANT ATLAS_TAGS_ROME_SELECT TO ATLAS_TAGS_ROME_EDIT;
GRANT ATLAS_TAGS_ROME_INSERT TO ATLAS_TAGS_ROME_EDIT;
GRANT ATLAS_TAGS_ROME_UPDATE TO ATLAS_TAGS_ROME_EDIT;
GRANT ATLAS_TAGS_ROME_DELETE TO ATLAS_TAGS_ROME_EDIT;
