/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

#ifndef MUONCOMPETINGRIOSONTRACK_MUONCOMPETINGRIOSONTRACKDICT_H
#define MUONCOMPETINGRIOSONTRACK_MUONCOMPETINGRIOSONTRACKDICT_H

#include "MuonCompetingRIOsOnTrack/CompetingMuonClustersOnTrack.h"

#endif // not MUONCOMPETINGRIOSONTRACK_MUONCOMPETINGRIOSONTRACKDICT_H
