#include "TrigFTKTrackConverter/TrigFTKTrackConverter.h"
#include "TrigFTKTrackConverter/TrigFTKClusterConverterTool.h"
#include "TrigFTKTrackConverter/TrigFTKUncertiantyTool.h"

DECLARE_TOOL_FACTORY(TrigFTKTrackConverter)
DECLARE_TOOL_FACTORY(TrigFTKClusterConverterTool)
DECLARE_TOOL_FACTORY(TrigFTKUncertiantyTool)

