## autogenerated at [2007-05-23 15:57:05.198354]

## create a method being executed at import time
def _fill( item ):
    item.add( {
        'DetStatusMap': ['DetectorStatus']
        })
    return
## EOF ##
