# $Id: Helpers.py 472095 2011-12-02 10:27:01Z krasznaa $

PACKAGE          = JetAnalysisEDM
PACKAGE_PRELOAD  = Tree TreePlayer
# Add the option -DACTIVATE_BRANCHES if your analysis framework
# disables all branches by default.
# Remove the COLLECT_D3PD_READING_STATISTICS option to gain a bit
# of performance...
PACKAGE_CXXFLAGS = -g # -std=c++11
PACKAGE_LDFLAGS  = -g    # -std=c++11 
PACKAGE_DEP      =
PACKAGE_LIBFLAGS =  
PACKAGE_BINFLAGS = -lGenVector
include $(ROOTCOREDIR)/Makefile-common
