# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = EventLoopGrid
PACKAGE_PRELOAD  = 
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  = -lpthread
PACKAGE_BINFLAGS = 
PACKAGE_DEP      = EventLoop SampleHandler RootCoreUtils
PACKAGE_NOOPT    = 0
PACKAGE_PEDANTIC = 1

include $(ROOTCOREDIR)/Makefile-common
