# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

import PyLCGDict
PyLCGDict.loadDict('SealDictDict')
PyLCGDict.loadDict('AthenaPoolTestDataDict')
PyLCGDict.loadDict('EventInfoDict')
PyLCGDict.loadDict('GaudiKernelDict')
PyLCGDict.loadDict('SGToolsDict')
PyLCGDict.loadDict('StoreGateDict')

#PyLCGDict.loadDict('AthExStoreGateExampleDict')
#PyLCGDict.loadDict('AthenaPoolExampleDataDict')
#PyLCGDict.loadDict('AthenaPoolTestDataDict')
#PyLCGDict.loadDict('AtlfastEventDict')
#PyLCGDict.loadDict('CaloEventDict')
#PyLCGDict.loadDict('CaloSimEventDict')
#PyLCGDict.loadDict('DetDescrConditionsDict')
#PyLCGDict.loadDict('DetDescrDict')
#PyLCGDict.loadDict('EventInfoDict')
#PyLCGDict.loadDict('EventKernelDict')
#PyLCGDict.loadDict('FourMomDict')
#PyLCGDict.loadDict('GeneratorObjectsDict')
#PyLCGDict.loadDict('IOVDbTestConditionsDict')
#PyLCGDict.loadDict('IdDict')
#PyLCGDict.loadDict('IdDictDetDescr')
#PyLCGDict.loadDict('IdDictDetDescrCnv')
#PyLCGDict.loadDict('IdDictParser')
#PyLCGDict.loadDict('IdDictTest')
#PyLCGDict.loadDict('InDetPriVxDict')
#PyLCGDict.loadDict('InDetRawDataDict')
#PyLCGDict.loadDict('InDetSimDataDict')
#PyLCGDict.loadDict('InDetSimEventDict')
#PyLCGDict.loadDict('JetEventDict')
#PyLCGDict.loadDict('LArCondDataDict')
#PyLCGDict.loadDict('LArRawEventDict')
#PyLCGDict.loadDict('LArRecEventDict')
#PyLCGDict.loadDict('LArSimEventDict')
#PyLCGDict.loadDict('MCTruthDict')
#PyLCGDict.loadDict('MissingETEventDict')
#PyLCGDict.loadDict('MooTrackContainerDict')
#PyLCGDict.loadDict('MuonDigitContainerDict')
#PyLCGDict.loadDict('MuonRDODict')
#PyLCGDict.loadDict('MuonSimDataDict')
#PyLCGDict.loadDict('MuonSimEventDict')
#PyLCGDict.loadDict('MuonTBConditionsDict')
#PyLCGDict.loadDict('NavFourMomDict')
#PyLCGDict.loadDict('NavigationDict')
##PyLCGDict.loadDict('NovaBlobDict')
#PyLCGDict.loadDict('ParticleEventDict')
#PyLCGDict.loadDict('SGToolsDict')
#PyLCGDict.loadDict('SimpleBTagDict')
#PyLCGDict.loadDict('SimpleTrackDict')
#PyLCGDict.loadDict('StoreGateDict')
#PyLCGDict.loadDict('TileEventDict')
#PyLCGDict.loadDict('TileSimEventDict')
#PyLCGDict.loadDict('TrackParticleDict')
#PyLCGDict.loadDict('TrigT1ResultDict')
#PyLCGDict.loadDict('TrkEventUtilsDict')
#PyLCGDict.loadDict('TrkParametersDict')
#PyLCGDict.loadDict('TrkPrepRawDataDict')
#PyLCGDict.loadDict('TrkRIO_OnTrackDict')
#PyLCGDict.loadDict('TrkSurfacesDict')
#PyLCGDict.loadDict('TrkTrackDict')
#PyLCGDict.loadDict('TrkTrackSummaryDict')
#PyLCGDict.loadDict('VxVertexDict')
#PyLCGDict.loadDict('egammaEventDict')
#PyLCGDict.loadDict('iPatTrackContainerDict')
#

gbl = PyLCGDict.makeNamespace('')
for c in gbl.seal.reflect.Class.forNames() : print c.name()


