print "***** WARNING ******************************************************************"
print " The file TrkRIO_OnTrackCreator/RIO_OnTrackErrorScaling.py"
print "          is currently obsolete."
print " To use scaled errors in the track fit and reconstruction, submit the scaling"
print " values as tag to COOL. Instructions are in the TrkRIO_OnTrackCreator package."
print "********************************************************************************"
