#include "TrackVertexAssociationTool/LooseTrackVertexAssociationTool.h"
#include "TrackVertexAssociationTool/TightTrackVertexAssociationTool.h"
#include "TrackVertexAssociationTool/BaseTrackVertexAssociationTool.h"
#include "TrackVertexAssociationTool/ElectronTrackVertexAssociationTool.h"
#include "TrackVertexAssociationTool/MuonTrackVertexAssociationTool.h"

#include "../TrackVertexAssoTestAlg.h"

using namespace xAOD;

DECLARE_NAMESPACE_TOOL_FACTORY(CP,LooseTrackVertexAssociationTool)
DECLARE_NAMESPACE_TOOL_FACTORY(CP,TightTrackVertexAssociationTool)
DECLARE_NAMESPACE_TOOL_FACTORY(CP,BaseTrackVertexAssociationTool)
DECLARE_NAMESPACE_TOOL_FACTORY(CP,ElectronTrackVertexAssociationTool)
DECLARE_NAMESPACE_TOOL_FACTORY(CP,MuonTrackVertexAssociationTool)
DECLARE_ALGORITHM_FACTORY(TrackVertexAssoTestAlg)

