# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

BPhysTriggerContent = [
"HLT_xAOD__TrigBphysContainer_EFBMuMuFex",
"HLT_xAOD__TrigBphysContainer_EFBMuMuFexAux.",
"HLT_xAOD__TrigBphysContainer_EFBMuMuXFex",
"HLT_xAOD__TrigBphysContainer_EFBMuMuXFexAux.",
"HLT_xAOD__TrigBphysContainer_EFTrackMass",
"HLT_xAOD__TrigBphysContainer_EFTrackMassAux.",
"HLT_xAOD__TrigBphysContainer_EFMultiMuFex",
"HLT_xAOD__TrigBphysContainer_EFMultiMuFexAux.",
"HLT_xAOD__TrigBphysContainer_L2BMuMuFex",
"HLT_xAOD__TrigBphysContainer_L2BMuMuFexAux.",
"HLT_xAOD__TrackParticleContainer_InDetTrigTrackingxAODCnv_Muon_EFID",
"HLT_xAOD__TrackParticleContainer_InDetTrigTrackingxAODCnv_Muon_EFIDAux.",
"HLT_xAOD__TrackParticleContainer_InDetTrigTrackingxAODCnv_Muon_IDTrig",
"HLT_xAOD__TrackParticleContainer_InDetTrigTrackingxAODCnv_Muon_IDTrigAux."
#"HLT_xAOD__TrackParticleContainer_InDetTrigTrackingxAODCnv_Bphysics_IDTrig",
#"HLT_xAOD__TrackParticleContainer_InDetTrigTrackingxAODCnv_Bphysics_IDTrigAux.pt.eta.phi.d0.z0"
]
