# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

EGammaTriggerContent = ['xAOD::CaloClusterContainer#HLT_xAOD__CaloClusterContainer_TrigCaloClusterMaker',
'xAOD::CaloClusterContainer#HLT_xAOD__CaloClusterContainer_TrigCaloClusterMaker_slw',
'xAOD::CaloClusterContainer#HLT_xAOD__CaloClusterContainer_TrigEFCaloCalibFex',
'xAOD::PhotonContainer#HLT_xAOD__PhotonContainer_egamma_Photons',
'xAOD::PhotonAuxContainer#HLT_xAOD__PhotonContainer_egamma_PhotonsAux.',
'xAOD::ElectronContainer#HLT_xAOD__ElectronContainer_egamma_Electrons',
'xAOD::ElectronAuxContainer#HLT_xAOD__ElectronContainer_egamma_ElectronsAux.',
'xAOD::CaloClusterAuxContainer#HLT_xAOD__CaloClusterContainer_TrigCaloClusterMakerAux.',
'xAOD::CaloClusterAuxContainer#HLT_xAOD__CaloClusterContainer_TrigCaloClusterMaker_slwAux.',
'xAOD::CaloClusterAuxContainer#HLT_xAOD__CaloClusterContainer_TrigEFCaloCalibFexAux.',
'xAOD::TrigEMClusterAuxContainer#HLT_xAOD__TrigEMClusterContainer_TrigT2CaloEgammaAux.',
'xAOD::EmTauRoIAuxContainer#HLT_xAOD__EmTauRoIContainer_L1TopoEMAux.',
'xAOD::EmTauRoIAuxContainer#HLT_xAOD__EmTauRoIContainer_L1TopoTauAux.',
'xAOD::EmTauRoIAuxContainer#LVL1EmTauRoIsAux.',
'xAOD::TrigPhotonContainer#HLT_xAOD__TrigPhotonContainer_L2PhotonFex',
'xAOD::TrigEMClusterContainer#HLT_xAOD__TrigEMClusterContainer_TrigT2CaloEgamma',
'xAOD::PhotonAuxContainer#HLT_xAOD__PhotonContainer_egamma_PhotonsAux.',
'xAOD::PhotonAuxContainer#PhotonsAux.',
'xAOD::TrigElectronContainer#HLT_xAOD__TrigElectronContainer_L2ElectronFex',
'xAOD::TrigElectronContainer#HLT_xAOD__TrigElectronContainer_L2IDCaloFex',
'xAOD::TrigPhotonAuxContainer#HLT_xAOD__TrigPhotonContainer_L2PhotonFexAux.',
'xAOD::EmTauRoIContainer#HLT_xAOD__EmTauRoIContainer_L1TopoEM',
'xAOD::EmTauRoIContainer#HLT_xAOD__EmTauRoIContainer_L1TopoTau',
'xAOD::EmTauRoIContainer#LVL1EmTauRoIs',
'TrigEMClusterContainer#HLT_TrigEMClusterContainer_TrigT2CaloCosmic',
'xAOD::TrigElectronAuxContainer#HLT_xAOD__TrigElectronContainer_L2ElectronFexAux.',
'xAOD::TrigElectronAuxContainer#HLT_xAOD__TrigElectronContainer_L2IDCaloFexAux.']
