# Copyright (C) 2002-2021 CERN for the benefit of the ATLAS collaboration

EventInfoContent = [
"EventInfo",
"EventInfoAux.beamPosZ.sctFlags.trtFlags.coreFlags.lumiFlags.muonFlags.beamPosX.beamPosY.beamStatus.beamTiltXZ.beamTiltYZ.pixelFlags.larFlags.runNumber.beamPosSigmaXY.beamPosSigmaX.beamPosSigmaY.beamPosSigmaZ.forwardDetFlags.eventTypeBitmask.DFCommonJets_isBadBatman.DFCommonJets_eventClean_LooseBad.mcChannelNumber.DFCommonJets_eventClean_LooseBadLLP.tileFlags.lumiBlock.timeStamp.actualInteractionsPerCrossing.averageInteractionsPerCrossing.eventNumber.detDescrTags.bcid.mcEventNumber.hardScatterVertexLink.beamSpotWeight.pileUpMixtureIDLowBits.pileUpMixtureIDHighBits.mcEventWeights"]
