# Copyright (C) 2002-2018 CERN for the benefit of the ATLAS collaboration

FullListOfSmartContainers = [
   "Electrons",
   "Photons",
   "Muons",
   "TauJets",
   "TauMVATESJets",
   "MET_Reference_AntiKt4LCTopo",
   "MET_Reference_AntiKt4EMTopo",
   "MET_Reference_AntiKt4EMPFlow",
   "AntiKt4TruthJets",
   "AntiKt4TruthWZJets",
   "AntiKt4TruthDressedWZJets",
   "AntiKt2LCTopoJets",
   "AntiKt4LCTopoJets",
   "AntiKt6LCTopoJets",
   "AntiKt4EMTopoJets",
   "AntiKt10LCTopoTrimmedPtFrac5SmallR20Jets",
   "AntiKt4EMPFlowJets",
   "AntiKt2LCTopoJets",
   "AntiKt3LCTopoJets",
   "AntiKt5LCTopoJets",
   "AntiKt6LCTopoJets",
   "AntiKt7LCTopoJets",
   "AntiKt8LCTopoJets",
   "BTagging_AntiKt4LCTopo",
   "BTagging_AntiKt4EMTopo",
   "BTagging_AntiKt4EMPFlow",
   "BTagging_AntiKt2Track",
   "BTagging_AntiKt3Track",
   "BTagging_AntiKt4Track",
   "BTagging_AntiKtVR30Rmax4Rmin02Track",
   "InDetTrackParticles",
   "PrimaryVertices",
   "HLT_xAOD__MuonContainer_MuonEFInfo",
   "HLT_xAOD__PhotonContainer_egamma_Photons",
   "HLT_xAOD__JetContainer_a4tcemsubjesFS",
   "HLT_xAOD__TrigMissingETContainer_TrigEFMissingET",
   "HLT_xAOD__TauJetContainer_TrigTauRecMerged",
   "HLT_xAOD__BTaggingContainer_HLTBjetFex",
   "HLT_xAOD__TrigBphysContainer_EFBMuMuFex",
   "HLT_xAOD__TrigVertexCountsContainer_vertexcounts"
]  

     
