# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

InDetTrackParticlesCPContent = [
"InDetTrackParticles",
"InDetTrackParticlesAux.phi.d0.z0.theta.qOverP.definingParametersCovMatrix.chiSquared.numberDoF.numberOfInnermostPixelLayerHits.numberOfPixelHits.numberOfPixelHoles.numberOfPixelSharedHits.numberOfPixelDeadSensors.numberOfSCTHits.numberOfSCTHoles.numberOfSCTSharedHits.numberOfSCTDeadSensors.vertexLink.numberOfNextToInnermostPixelLayerHits.truthParticleLink.expectInnermostPixelLayerHit.expectNextToInnermostPixelLayerHit"
]
