!
!> \author J.F.Laporte
!
 SUBROUTINE GETMUPAR(IKIND,VPAR)
 USE M_MB_Fit, ONLY : VTHETAPHI, VPERIGEE
 IMPLICIT NONE
 INTEGER, INTENT(IN)  :: IKIND
 REAL(8), INTENT(OUT) :: VPAR(*)
!
   IF(IKIND /= 3) THEN
     VPAR(1:5) = VTHETAPHI(1:5)
   ELSE
     VPAR(1:5) = VPERIGEE(1:5)
   ENDIF
!
 END SUBROUTINE GETMUPAR
!
