!
!> Set VDEB
!> \author J.F.Laporte
!
 SUBROUTINE SETVDEB(IKIND,VPAR)
 USE M_MB_Fit, ONLY : VTHETAPHI, VPERIGEE
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: IKIND
 REAL(8), INTENT(IN) :: VPAR(*)
!
   IF(IKIND /= 3) THEN
      VTHETAPHI(1:5) = VPAR(1:5)
      CALL GIVDEB2(1)
   ELSE
     VPERIGEE(1:5) = VPAR(1:5)
     CALL GIVDEB3(1)
   ENDIF
!
 END SUBROUTINE SETVDEB
!
