from FastCaloSim.FastCaloSimConf import FastShowerCellBuilderTool
theFastShowerCellBuilderTool=FastShowerCellBuilderTool()

theFastShowerCellBuilderTool.DoSimulWithInnerDetectorTruthOnly=True
theFastShowerCellBuilderTool.ID_cut_off_r=[1150]
theFastShowerCellBuilderTool.ID_cut_off_z=[3490]
theFastShowerCellBuilderTool.DoSimulWithInnerDetectorV14TruthCuts=True
