from IOVDbSvc.CondDB import conddb;
conddb.blockFolder("/Indet/Beampos");
conddb.blockFolder("/Indet/PixelDist");
conddb.blockFolder("/LAR/ElecCalibFlat/DAC2uA");
conddb.blockFolder("/LAR/ElecCalibFlat/HVScaleCorr");
conddb.blockFolder("/LAR/ElecCalibFlat/MphysOverMcal");
conddb.blockFolder("/LAR/ElecCalibFlat/OFC");
conddb.blockFolder("/LAR/ElecCalibFlat/Pedestal");
conddb.blockFolder("/LAR/ElecCalibFlat/Ramp");
conddb.blockFolder("/LAR/ElecCalibFlat/Shape");
conddb.blockFolder("/LAR/ElecCalibFlat/uA2MeV");
conddb.blockFolder("/LAR/Identifier/CalibIdMap");
conddb.blockFolder("/LAR/Identifier/FebRodMap"); 
conddb.blockFolder("/LAR/Identifier/OnOffIdMap");
conddb.blockFolder("/LAR/Identifier/LArTTCellMapAtlas");
