from IOVDbSvc.CondDB import conddb;
conddb.blockFolder("/MDT/RTBLOB");
conddb.blockFolder("/MDT/T0BLOB"); 
conddb.blockFolder("/PIXEL/PixdEdx"); 
conddb.blockFolder("/SCT/DAQ/Calibration/NPtGainDefects"); 
conddb.blockFolder("/SCT/DAQ/Calibration/NoiseOccupancyDefects"); 
conddb.blockFolder("/SCT/DAQ/Config/Chip"); 
conddb.blockFolder("/SCT/DAQ/Config/MUR"); 
conddb.blockFolder("/SCT/DAQ/Config/Module"); 
conddb.blockFolder("/SCT/Derived/Monitoring"); 
conddb.blockFolder("/TRT/Calib/PID"); 
conddb.blockFolder("/TRT/Calib/PID_RToT"); 
conddb.blockFolder("/TRT/Calib/PID_RToTver_New"); 
conddb.blockFolder("/TRT/Calib/PID_vector"); 
conddb.blockFolder("/TRT/Calib/PIDver_New"); 
conddb.blockFolder("/TRT/Calib/ToT/ToTValue"); 
conddb.blockFolder("/TRT/Calib/ToT/ToTVectors");
conddb.blockFolder("/LAR/ElecCalibMC/MinBiasAverage");
