from IOVDbSvc.CondDB import conddb;
conddb.blockFolder("/Indet/PixelDist");  
conddb.blockFolder("/Indet/TrkErrorScaling");  
conddb.blockFolder("/LAR/ElecCalibFlat/HVScaleCorr");  
conddb.blockFolder("/LAR/Identifier/CalibIdMap");  
conddb.blockFolder("/LAR/Identifier/FebRodMap"); 
conddb.blockFolder("/LAR/Identifier/OnOffIdMap");  
conddb.blockFolder("/LAR/Identifier/LArTTCellMapAtlas");
conddb.blockFolder("/MUONALIGN/ERRS");  
conddb.blockFolder("/PIXEL/CablingMap");  
conddb.blockFolder("/PIXEL/PixReco"); 
conddb.blockFolder("/PIXEL/PixdEdx");  
conddb.blockFolder("/PIXEL/PixCalib");
conddb.blockFolder("/PIXEL/PixelClustering/PixelClusNNCalib");  
conddb.blockFolder("/TRT/Calib/HTCalib");  
conddb.blockFolder("/TRT/Calib/PID");  
conddb.blockFolder("/TRT/Calib/PID_RToT");  
conddb.blockFolder("/TRT/Calib/PID_RToTver_New");  
conddb.blockFolder("/TRT/Calib/PID_vector");  
conddb.blockFolder("/TRT/Calib/PIDver_New");  
conddb.blockFolder("/TRT/Calib/RT");  
conddb.blockFolder("/TRT/Calib/T0");  
conddb.blockFolder("/TRT/Calib/ToT/ToTValue");  
conddb.blockFolder("/TRT/Calib/ToT/ToTVectors");  
conddb.blockFolder("/TRT/Calib/ToTCalib");  
conddb.blockFolder("/TRT/Calib/errors2d");  
conddb.blockFolder("/TRT/Calib/slopes");  

