#! /usr/bin/env bash

## Any arguments are considered overrides, and will be added at the end
export TRF_ECHO=True;
Generate_tf.py --ecmEnergy=8000 --runNumber=110200 --maxEvents=10 \
    --jobConfig=$JODIR/share/tests/MC14.110200.McAtNloHerwigpp_CT10ME_CTEQ6L1MPI_ttbar_LeptonFilter.py \
    --inputGeneratorFile=$TESTDATA/group.phys-gener.mcatnlo409.110200.ttbar_8TeV.TXT.mc12_v1._00001.tar.gz \
    --outputEVNTFile=test_mcatnloherwigpp_ttbar_leptonfilter.EVNT.pool.root \
    $@
