#! /usr/bin/env bash

## Any arguments are considered overrides, and will be added at the end
export TRF_ECHO=True;
Generate_tf.py --ecmEnergy=13000 --runNumber=361225 --maxEvents=10 \
    --jobConfig=$JODIR15/share/DSID361xxx/MC15.361225.Herwigpp_UEEE4_CTEQ6L1_MinBias.py  \
    --outputEVNTFile=test_herwigpp_minbias_inelastic.EVNT.pool.root \
    $@
