#! /usr/bin/env bash

## Any arguments are considered overrides, and will be added at the end
export TRF_ECHO=True;
Generate_tf.py --ecmEnergy=8000 --runNumber=429686 --maxEvents=10 \
    --jobConfig=$JODIR15/share/DSID429xxx/MC15.429686.McAtNloHerwig7_CT10_H7UE_MMHT2014lo_ttbar_LeptonFilter.py \
    --inputGeneratorFile=$TESTDATA/group.phys-gener.mcatnlo409.110200.ttbar_8TeV.TXT.mc12_v1._00001.tar.gz \
    --outputEVNTFile=test_mcatnloherwigpp_ttbar_leptonfilter.EVNT.pool.root \
    $@
