#! /usr/bin/env bash

## Any arguments are considered overrides, and will be added at the end
export TRF_ECHO=True;
Generate_tf.py --ecmEnergy=8000 --runNumber=117680 --maxEvents=2 \
    --jobConfig=$JODIR/share/tests/MC14.117680.AlpgenPythia_P2011C_WenuNp0.py \
    --outputEVNTFile=test_AlpgenPythia_WenuNp0.EVNT.pool.root \
    --inputGeneratorFile=$TESTDATA/group.phys-gener.alpgen214.107680.WenuNp0_CTEQ6L1_8TeV.TXT.mc12_v1._00001.tar.gz \
    $@
