#! /usr/bin/env bash

## Any arguments are considered overrides, and will be added at the end
export TRF_ECHO=True;
Generate_tf.py --ecmEnergy=8000 --runNumber=147818 --maxEvents=10 \
    --jobConfig=$JODIR/share/tests/MC14.147818.Pythia8_AU2CTEQ6L1_Ztautau.py  \
    --outputEVNTFile=test_Ztautau.EVNT.pool.root \
    $@
