#! /usr/bin/env bash

## Any arguments are considered overrides, and will be added at the end
export TRF_ECHO=True;
rm *;
DISPLAY='' \
Generate_tf.py --ecmEnergy=13000 --runNumber=410066 --maxEvents=10 \
    --jobConfig=$JODIR15/share/DSID410xxx/MC15.410066.MadGraphPythia8EvtGen_A14NNPDF23LO_ttW_Np0.py \
    --outputEVNTFile=test_mgpythia8_ttW.EVNT.pool.root \
    $@
