#! /usr/bin/env bash

## Any arguments are considered overrides, and will be added at the end
export TRF_ECHO=True;
Generate_tf.py --ecmEnergy=8000 --runNumber=119994 --maxEvents=10 \
    --jobConfig=$JODIR/share/tests/MC14.119994.Pythia8_A2MSTW2008LO_minbias_inelastic.py \
    --outputEVNTFile=test_minbias_inelastic.EVNT.pool.root \
    $@
