# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

InDetTrackParticlesCPContent = [
"InDetTrackParticles",
"InDetTrackParticlesAux.phi.theta.qOverP.z0.d0.chiSquared.numberDoF.expectInnermostPixelLayerHit.expectNextToInnermostPixelLayerHit.numberOfInnermostPixelLayerHits.numberOfNextToInnermostPixelLayerHits.numberOfPixelHits.numberOfPixelHoles.numberOfPixelSharedHits.numberOfPixelDeadSensors.numberOfSCTHits.numberOfSCTHoles.numberOfSCTSharedHits.numberOfSCTDeadSensors.definingParametersCovMatrix"
]
