# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

InDetSiSPSeededTracksParticlesCPContent = [
"InDetSiSPSeededTracksParticles",
"InDetSiSPSeededTracksParticlesAux.phi.theta.qOverP.chiSquared.numberDoF.numberOfInnermostPixelLayerHits.numberOfPixelHits.numberOfPixelHoles.numberOfPixelSharedHits.numberOfPixelDeadSensors.numberOfSCTHits.numberOfSCTHoles.numberOfSCTSharedHits.numberOfSCTDeadSensors.definingParametersCovMatrixDiag.definingParametersCovMatrixOffDiag"
]