# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

InDetPlusPseudoTrackParticlesCPContent = [
"InDetPlusPseudoTrackParticles",
"InDetPlusPseudoTrackParticlesAux.phi.theta.qOverP.chiSquared.numberDoF.numberOfInnermostPixelLayerHits.numberOfPixelHits.numberOfPixelHoles.numberOfPixelSharedHits.numberOfPixelDeadSensors.numberOfSCTHits.numberOfSCTHoles.numberOfSCTSharedHits.numberOfSCTDeadSensors.definingParametersCovMatrixDiag.definingParametersCovMatrixOffDiag"
]