# Copyright (C) 2002-2020 CERN for the benefit of the ATLAS collaboration

LowPtRoITrackParticlesCPContent = [
"LowPtRoITrackParticles",
"LowPtRoITrackParticlesAux.phi.theta.qOverP.z0.d0.chiSquared.numberDoF.expectInnermostPixelLayerHit.expectNextToInnermostPixelLayerHit.numberOfInnermostPixelLayerHits.numberOfNextToInnermostPixelLayerHits.numberOfPixelHits.numberOfPixelHoles.numberOfPixelSharedHits.numberOfPixelDeadSensors.numberOfSCTHits.numberOfSCTHoles.numberOfSCTSharedHits.numberOfSCTDeadSensors.definingParametersCovMatrix.truthMatchProbability.pixeldEdx.numberOfUsedHitsdEdx.numberOfIBLOverflowsdEdx"
]
