#!/bin/bash

if [ $# -ne 1 ] ; then
    echo "Usage: ./run_MRV_RTT_macro release (v12000601, v13003001, ...)"
    exit
fi

rel=$1

cat > do_macro << EOF
{
std::string macro_path = gROOT->GetMacroPath();
macro_path = macro_path+":$TestArea/MuonSpectrometer/MuonValidation/MuonRecValidator/test";
gROOT->SetMacroPath(macro_path.c_str());

gROOT->ProcessLine(".L MuonRecValidator_RTT_macro.C");
MuonRecValidator_RTT_macro("trig1_misal1_valid1", "005145", "PythiaZmumu", "AOD", "$rel");
}
EOF
root.exe -b -q do_macro 
rm -f do_macro
