#include "InDetTruthTools/PRD_MultiTruthBuilder.h"
#include "InDetTruthTools/PRD_TruthTrajectorySorterID.h"
#include "InDetTruthTools/PRD_TruthTrajectoryManipulatorID.h"
#include "InDetTruthTools/PRD_TruthTrajectorySelectorID.h"

DECLARE_NAMESPACE_TOOL_FACTORY(InDet, PRD_MultiTruthBuilder)
DECLARE_NAMESPACE_TOOL_FACTORY(InDet, PRD_TruthTrajectorySorterID)
DECLARE_NAMESPACE_TOOL_FACTORY(InDet, PRD_TruthTrajectoryManipulatorID)
DECLARE_NAMESPACE_TOOL_FACTORY(InDet, PRD_TruthTrajectorySelectorID)

