/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

{
//=========Macro generated from canvas: c_jpsi_dR/c_jpsi_dR
//=========  (Thu Jun 24 16:32:02 2010) by ROOT version5.26/00
   TCanvas *c_jpsi_dR = new TCanvas("c_jpsi_dR", "c_jpsi_dR",15,34,700,500);
   gStyle->SetOptFit(1);
   c_jpsi_dR->Range(-0.3037975,-108.3158,1.594937,568.6579);
   c_jpsi_dR->SetFillColor(0);
   c_jpsi_dR->SetBorderMode(0);
   c_jpsi_dR->SetBorderSize(2);
   c_jpsi_dR->SetTickx(1);
   c_jpsi_dR->SetTicky(1);
   c_jpsi_dR->SetLeftMargin(0.16);
   c_jpsi_dR->SetRightMargin(0.05);
   c_jpsi_dR->SetTopMargin(0.08);
   c_jpsi_dR->SetBottomMargin(0.16);
   c_jpsi_dR->SetFrameBorderMode(0);
   c_jpsi_dR->SetFrameBorderMode(0);
   
   TH1F *jpsi_dR_1 = new TH1F("jpsi_dR_1","J/#psi",10,0,1.5);
   jpsi_dR_1->SetBinContent(1,2);
   jpsi_dR_1->SetBinContent(2,16);
   jpsi_dR_1->SetBinContent(3,92);
   jpsi_dR_1->SetBinContent(4,207);
   jpsi_dR_1->SetBinContent(5,245);
   jpsi_dR_1->SetBinContent(6,102);
   jpsi_dR_1->SetBinContent(7,17);
   jpsi_dR_1->SetBinError(1,1.414214);
   jpsi_dR_1->SetBinError(2,4);
   jpsi_dR_1->SetBinError(3,9.591663);
   jpsi_dR_1->SetBinError(4,14.38749);
   jpsi_dR_1->SetBinError(5,15.65248);
   jpsi_dR_1->SetBinError(6,10.0995);
   jpsi_dR_1->SetBinError(7,4.123106);
   jpsi_dR_1->SetMinimum(0);
   jpsi_dR_1->SetMaximum(514.5);
   jpsi_dR_1->SetEntries(681);
   jpsi_dR_1->SetStats(0);
   jpsi_dR_1->SetLineWidth(2);
   jpsi_dR_1->SetMarkerStyle(20);
   jpsi_dR_1->SetMarkerSize(1.2);
   jpsi_dR_1->GetXaxis()->SetTitle(" #DeltaR");
   jpsi_dR_1->GetXaxis()->SetLabelFont(42);
   jpsi_dR_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_dR_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_dR_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_dR_1->GetXaxis()->SetTitleFont(42);
   jpsi_dR_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_dR_1->GetYaxis()->SetLabelFont(42);
   jpsi_dR_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_dR_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_dR_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_dR_1->GetYaxis()->SetTitleFont(42);
   jpsi_dR_1->GetZaxis()->SetLabelFont(42);
   jpsi_dR_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_dR_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_dR_1->GetZaxis()->SetTitleFont(42);
   jpsi_dR_1->Draw("");
   
   TH1F *jpsi_dR_trk_1 = new TH1F("jpsi_dR_trk_1","J/#psi",10,0,1.5);
   jpsi_dR_trk_1->SetBinContent(1,1);
   jpsi_dR_trk_1->SetBinContent(2,13);
   jpsi_dR_trk_1->SetBinContent(3,87);
   jpsi_dR_trk_1->SetBinContent(4,198);
   jpsi_dR_trk_1->SetBinContent(5,234);
   jpsi_dR_trk_1->SetBinContent(6,101);
   jpsi_dR_trk_1->SetBinContent(7,17);
   jpsi_dR_trk_1->SetMinimum(0);
   jpsi_dR_trk_1->SetMaximum(351);
   jpsi_dR_trk_1->SetEntries(651);
   jpsi_dR_trk_1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   jpsi_dR_trk_1->SetFillColor(ci);
   jpsi_dR_trk_1->SetLineWidth(2);
   jpsi_dR_trk_1->SetMarkerStyle(20);
   jpsi_dR_trk_1->SetMarkerSize(1.2);
   jpsi_dR_trk_1->GetXaxis()->SetTitle(" #DeltaR");
   jpsi_dR_trk_1->GetXaxis()->SetLabelFont(42);
   jpsi_dR_trk_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_dR_trk_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_dR_trk_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_dR_trk_1->GetXaxis()->SetTitleFont(42);
   jpsi_dR_trk_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_dR_trk_1->GetYaxis()->SetLabelFont(42);
   jpsi_dR_trk_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_dR_trk_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_dR_trk_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_dR_trk_1->GetYaxis()->SetTitleFont(42);
   jpsi_dR_trk_1->GetZaxis()->SetLabelFont(42);
   jpsi_dR_trk_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_dR_trk_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_dR_trk_1->GetZaxis()->SetTitleFont(42);
   jpsi_dR_trk_1->Draw("same");
   
   TH1F *jpsi_dR_fex_1 = new TH1F("jpsi_dR_fex_1","J/#psi",10,0,1.5);
   jpsi_dR_fex_1->SetBinContent(1,1);
   jpsi_dR_fex_1->SetBinContent(2,13);
   jpsi_dR_fex_1->SetBinContent(3,84);
   jpsi_dR_fex_1->SetBinContent(4,175);
   jpsi_dR_fex_1->SetBinContent(5,193);
   jpsi_dR_fex_1->SetBinContent(6,84);
   jpsi_dR_fex_1->SetBinContent(7,9);
   jpsi_dR_fex_1->SetMinimum(0);
   jpsi_dR_fex_1->SetMaximum(289.5);
   jpsi_dR_fex_1->SetEntries(559);
   jpsi_dR_fex_1->SetStats(0);

   ci = TColor::GetColor("#00ff00");
   jpsi_dR_fex_1->SetFillColor(ci);
   jpsi_dR_fex_1->SetLineWidth(2);
   jpsi_dR_fex_1->SetMarkerStyle(20);
   jpsi_dR_fex_1->SetMarkerSize(1.2);
   jpsi_dR_fex_1->GetXaxis()->SetTitle(" #DeltaR");
   jpsi_dR_fex_1->GetXaxis()->SetLabelFont(42);
   jpsi_dR_fex_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_dR_fex_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_dR_fex_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_dR_fex_1->GetXaxis()->SetTitleFont(42);
   jpsi_dR_fex_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_dR_fex_1->GetYaxis()->SetLabelFont(42);
   jpsi_dR_fex_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_dR_fex_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_dR_fex_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_dR_fex_1->GetYaxis()->SetTitleFont(42);
   jpsi_dR_fex_1->GetZaxis()->SetLabelFont(42);
   jpsi_dR_fex_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_dR_fex_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_dR_fex_1->GetZaxis()->SetTitleFont(42);
   jpsi_dR_fex_1->Draw("same");
   
   TH1F *jpsi_dR_muID_1 = new TH1F("jpsi_dR_muID_1","J/#psi",10,0,1.5);
   jpsi_dR_muID_1->SetBinContent(1,1);
   jpsi_dR_muID_1->SetBinContent(2,12);
   jpsi_dR_muID_1->SetBinContent(3,77);
   jpsi_dR_muID_1->SetBinContent(4,160);
   jpsi_dR_muID_1->SetBinContent(5,180);
   jpsi_dR_muID_1->SetBinContent(6,76);
   jpsi_dR_muID_1->SetBinContent(7,8);
   jpsi_dR_muID_1->SetMinimum(0);
   jpsi_dR_muID_1->SetMaximum(270);
   jpsi_dR_muID_1->SetEntries(514);
   jpsi_dR_muID_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   jpsi_dR_muID_1->SetFillColor(ci);
   jpsi_dR_muID_1->SetLineWidth(2);
   jpsi_dR_muID_1->SetMarkerStyle(20);
   jpsi_dR_muID_1->SetMarkerSize(1.2);
   jpsi_dR_muID_1->GetXaxis()->SetTitle(" #DeltaR");
   jpsi_dR_muID_1->GetXaxis()->SetLabelFont(42);
   jpsi_dR_muID_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_dR_muID_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_dR_muID_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_dR_muID_1->GetXaxis()->SetTitleFont(42);
   jpsi_dR_muID_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_dR_muID_1->GetYaxis()->SetLabelFont(42);
   jpsi_dR_muID_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_dR_muID_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_dR_muID_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_dR_muID_1->GetYaxis()->SetTitleFont(42);
   jpsi_dR_muID_1->GetZaxis()->SetLabelFont(42);
   jpsi_dR_muID_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_dR_muID_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_dR_muID_1->GetZaxis()->SetTitleFont(42);
   jpsi_dR_muID_1->Draw("same");
   
   TLegend *leg = new TLegend(0.55,0.65,0.9,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("jpsi_dR_1","Offline J/#psi","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("jpsi_dR_trk_1","After Tracking","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("jpsi_dR_fex_1","After FEX","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("jpsi_dR_muID_1","After Hypo","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *jpsi_dR_1__4 = new TH1F("jpsi_dR_1__4","J/#psi",10,0,1.5);
   jpsi_dR_1__4->SetBinContent(1,2);
   jpsi_dR_1__4->SetBinContent(2,16);
   jpsi_dR_1__4->SetBinContent(3,92);
   jpsi_dR_1__4->SetBinContent(4,207);
   jpsi_dR_1__4->SetBinContent(5,245);
   jpsi_dR_1__4->SetBinContent(6,102);
   jpsi_dR_1__4->SetBinContent(7,17);
   jpsi_dR_1__4->SetBinError(1,1.414214);
   jpsi_dR_1__4->SetBinError(2,4);
   jpsi_dR_1__4->SetBinError(3,9.591663);
   jpsi_dR_1__4->SetBinError(4,14.38749);
   jpsi_dR_1__4->SetBinError(5,15.65248);
   jpsi_dR_1__4->SetBinError(6,10.0995);
   jpsi_dR_1__4->SetBinError(7,4.123106);
   jpsi_dR_1__4->SetMinimum(0);
   jpsi_dR_1__4->SetMaximum(514.5);
   jpsi_dR_1__4->SetEntries(681);
   jpsi_dR_1__4->SetDirectory(0);
   jpsi_dR_1__4->SetStats(0);
   jpsi_dR_1__4->SetLineWidth(2);
   jpsi_dR_1__4->SetMarkerStyle(20);
   jpsi_dR_1__4->SetMarkerSize(1.2);
   jpsi_dR_1__4->GetXaxis()->SetTitle(" #DeltaR");
   jpsi_dR_1__4->GetXaxis()->SetLabelFont(42);
   jpsi_dR_1__4->GetXaxis()->SetLabelSize(0.05);
   jpsi_dR_1__4->GetXaxis()->SetTitleSize(0.05);
   jpsi_dR_1__4->GetXaxis()->SetTitleOffset(1.4);
   jpsi_dR_1__4->GetXaxis()->SetTitleFont(42);
   jpsi_dR_1__4->GetYaxis()->SetTitle("No. of candidates");
   jpsi_dR_1__4->GetYaxis()->SetLabelFont(42);
   jpsi_dR_1__4->GetYaxis()->SetLabelSize(0.05);
   jpsi_dR_1__4->GetYaxis()->SetTitleSize(0.05);
   jpsi_dR_1__4->GetYaxis()->SetTitleOffset(1.4);
   jpsi_dR_1__4->GetYaxis()->SetTitleFont(42);
   jpsi_dR_1__4->GetZaxis()->SetLabelFont(42);
   jpsi_dR_1__4->GetZaxis()->SetLabelSize(0.05);
   jpsi_dR_1__4->GetZaxis()->SetTitleSize(0.05);
   jpsi_dR_1__4->GetZaxis()->SetTitleFont(42);
   jpsi_dR_1__4->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.5205747,0.9390678,0.5894253,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *text = pt->AddText("J/#psi");
   pt->Draw();
   c_jpsi_dR->Modified();
   c_jpsi_dR->cd();
   c_jpsi_dR->SetSelected(c_jpsi_dR);
}
