/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

{
//=========Macro generated from canvas: c_jpsi_eta/c_jpsi_eta
//=========  (Thu Jun 24 16:31:43 2010) by ROOT version5.26/00
   TCanvas *c_jpsi_eta = new TCanvas("c_jpsi_eta", "c_jpsi_eta",15,34,700,500);
   gStyle->SetOptFit(1);
   c_jpsi_eta->Range(-4.21519,-45.97894,3.379747,241.3895);
   c_jpsi_eta->SetFillColor(0);
   c_jpsi_eta->SetBorderMode(0);
   c_jpsi_eta->SetBorderSize(2);
   c_jpsi_eta->SetTickx(1);
   c_jpsi_eta->SetTicky(1);
   c_jpsi_eta->SetLeftMargin(0.16);
   c_jpsi_eta->SetRightMargin(0.05);
   c_jpsi_eta->SetTopMargin(0.08);
   c_jpsi_eta->SetBottomMargin(0.16);
   c_jpsi_eta->SetFrameBorderMode(0);
   c_jpsi_eta->SetFrameBorderMode(0);
   
   TH1F *jpsi_eta_1 = new TH1F("jpsi_eta_1","J/#psi",10,-3,3);
   jpsi_eta_1->SetBinContent(1,7);
   jpsi_eta_1->SetBinContent(2,74);
   jpsi_eta_1->SetBinContent(3,90);
   jpsi_eta_1->SetBinContent(4,104);
   jpsi_eta_1->SetBinContent(5,73);
   jpsi_eta_1->SetBinContent(6,93);
   jpsi_eta_1->SetBinContent(7,78);
   jpsi_eta_1->SetBinContent(8,102);
   jpsi_eta_1->SetBinContent(9,49);
   jpsi_eta_1->SetBinContent(10,11);
   jpsi_eta_1->SetBinError(1,2.645751);
   jpsi_eta_1->SetBinError(2,8.602325);
   jpsi_eta_1->SetBinError(3,9.486833);
   jpsi_eta_1->SetBinError(4,10.19804);
   jpsi_eta_1->SetBinError(5,8.544004);
   jpsi_eta_1->SetBinError(6,9.643651);
   jpsi_eta_1->SetBinError(7,8.831761);
   jpsi_eta_1->SetBinError(8,10.0995);
   jpsi_eta_1->SetBinError(9,7);
   jpsi_eta_1->SetBinError(10,3.316625);
   jpsi_eta_1->SetMinimum(0);
   jpsi_eta_1->SetMaximum(218.4);
   jpsi_eta_1->SetEntries(681);
   jpsi_eta_1->SetStats(0);
   jpsi_eta_1->SetLineWidth(2);
   jpsi_eta_1->SetMarkerStyle(20);
   jpsi_eta_1->SetMarkerSize(1.2);
   jpsi_eta_1->GetXaxis()->SetTitle(" sub-leading muon #eta");
   jpsi_eta_1->GetXaxis()->SetLabelFont(42);
   jpsi_eta_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_eta_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_eta_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_eta_1->GetXaxis()->SetTitleFont(42);
   jpsi_eta_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_eta_1->GetYaxis()->SetLabelFont(42);
   jpsi_eta_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_eta_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_eta_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_eta_1->GetYaxis()->SetTitleFont(42);
   jpsi_eta_1->GetZaxis()->SetLabelFont(42);
   jpsi_eta_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_eta_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_eta_1->GetZaxis()->SetTitleFont(42);
   jpsi_eta_1->Draw("");
   
   TH1F *jpsi_eta_trk_1 = new TH1F("jpsi_eta_trk_1","J/#psi",10,-3,3);
   jpsi_eta_trk_1->SetBinContent(1,7);
   jpsi_eta_trk_1->SetBinContent(2,69);
   jpsi_eta_trk_1->SetBinContent(3,89);
   jpsi_eta_trk_1->SetBinContent(4,101);
   jpsi_eta_trk_1->SetBinContent(5,68);
   jpsi_eta_trk_1->SetBinContent(6,85);
   jpsi_eta_trk_1->SetBinContent(7,73);
   jpsi_eta_trk_1->SetBinContent(8,100);
   jpsi_eta_trk_1->SetBinContent(9,49);
   jpsi_eta_trk_1->SetBinContent(10,10);
   jpsi_eta_trk_1->SetMinimum(0);
   jpsi_eta_trk_1->SetMaximum(151.5);
   jpsi_eta_trk_1->SetEntries(651);
   jpsi_eta_trk_1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   jpsi_eta_trk_1->SetFillColor(ci);
   jpsi_eta_trk_1->SetLineWidth(2);
   jpsi_eta_trk_1->SetMarkerStyle(20);
   jpsi_eta_trk_1->SetMarkerSize(1.2);
   jpsi_eta_trk_1->GetXaxis()->SetTitle(" sub-leading muon #eta");
   jpsi_eta_trk_1->GetXaxis()->SetLabelFont(42);
   jpsi_eta_trk_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_eta_trk_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_eta_trk_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_eta_trk_1->GetXaxis()->SetTitleFont(42);
   jpsi_eta_trk_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_eta_trk_1->GetYaxis()->SetLabelFont(42);
   jpsi_eta_trk_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_eta_trk_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_eta_trk_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_eta_trk_1->GetYaxis()->SetTitleFont(42);
   jpsi_eta_trk_1->GetZaxis()->SetLabelFont(42);
   jpsi_eta_trk_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_eta_trk_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_eta_trk_1->GetZaxis()->SetTitleFont(42);
   jpsi_eta_trk_1->Draw("same");
   
   TH1F *jpsi_eta_fex_1 = new TH1F("jpsi_eta_fex_1","J/#psi",10,-3,3);
   jpsi_eta_fex_1->SetBinContent(1,5);
   jpsi_eta_fex_1->SetBinContent(2,66);
   jpsi_eta_fex_1->SetBinContent(3,81);
   jpsi_eta_fex_1->SetBinContent(4,78);
   jpsi_eta_fex_1->SetBinContent(5,58);
   jpsi_eta_fex_1->SetBinContent(6,69);
   jpsi_eta_fex_1->SetBinContent(7,62);
   jpsi_eta_fex_1->SetBinContent(8,85);
   jpsi_eta_fex_1->SetBinContent(9,46);
   jpsi_eta_fex_1->SetBinContent(10,9);
   jpsi_eta_fex_1->SetMinimum(0);
   jpsi_eta_fex_1->SetMaximum(127.5);
   jpsi_eta_fex_1->SetEntries(559);
   jpsi_eta_fex_1->SetStats(0);

   ci = TColor::GetColor("#00ff00");
   jpsi_eta_fex_1->SetFillColor(ci);
   jpsi_eta_fex_1->SetLineWidth(2);
   jpsi_eta_fex_1->SetMarkerStyle(20);
   jpsi_eta_fex_1->SetMarkerSize(1.2);
   jpsi_eta_fex_1->GetXaxis()->SetTitle(" sub-leading muon #eta");
   jpsi_eta_fex_1->GetXaxis()->SetLabelFont(42);
   jpsi_eta_fex_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_eta_fex_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_eta_fex_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_eta_fex_1->GetXaxis()->SetTitleFont(42);
   jpsi_eta_fex_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_eta_fex_1->GetYaxis()->SetLabelFont(42);
   jpsi_eta_fex_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_eta_fex_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_eta_fex_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_eta_fex_1->GetYaxis()->SetTitleFont(42);
   jpsi_eta_fex_1->GetZaxis()->SetLabelFont(42);
   jpsi_eta_fex_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_eta_fex_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_eta_fex_1->GetZaxis()->SetTitleFont(42);
   jpsi_eta_fex_1->Draw("same");
   
   TH1F *jpsi_eta_muID_1 = new TH1F("jpsi_eta_muID_1","J/#psi",10,-3,3);
   jpsi_eta_muID_1->SetBinContent(1,4);
   jpsi_eta_muID_1->SetBinContent(2,64);
   jpsi_eta_muID_1->SetBinContent(3,73);
   jpsi_eta_muID_1->SetBinContent(4,70);
   jpsi_eta_muID_1->SetBinContent(5,54);
   jpsi_eta_muID_1->SetBinContent(6,64);
   jpsi_eta_muID_1->SetBinContent(7,58);
   jpsi_eta_muID_1->SetBinContent(8,77);
   jpsi_eta_muID_1->SetBinContent(9,41);
   jpsi_eta_muID_1->SetBinContent(10,9);
   jpsi_eta_muID_1->SetMinimum(0);
   jpsi_eta_muID_1->SetMaximum(115.5);
   jpsi_eta_muID_1->SetEntries(514);
   jpsi_eta_muID_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   jpsi_eta_muID_1->SetFillColor(ci);
   jpsi_eta_muID_1->SetLineWidth(2);
   jpsi_eta_muID_1->SetMarkerStyle(20);
   jpsi_eta_muID_1->SetMarkerSize(1.2);
   jpsi_eta_muID_1->GetXaxis()->SetTitle(" sub-leading muon #eta");
   jpsi_eta_muID_1->GetXaxis()->SetLabelFont(42);
   jpsi_eta_muID_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_eta_muID_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_eta_muID_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_eta_muID_1->GetXaxis()->SetTitleFont(42);
   jpsi_eta_muID_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_eta_muID_1->GetYaxis()->SetLabelFont(42);
   jpsi_eta_muID_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_eta_muID_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_eta_muID_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_eta_muID_1->GetYaxis()->SetTitleFont(42);
   jpsi_eta_muID_1->GetZaxis()->SetLabelFont(42);
   jpsi_eta_muID_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_eta_muID_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_eta_muID_1->GetZaxis()->SetTitleFont(42);
   jpsi_eta_muID_1->Draw("same");
   
   TLegend *leg = new TLegend(0.55,0.65,0.9,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("jpsi_eta_1","Offline J/#psi","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("jpsi_eta_trk_1","After Tracking","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("jpsi_eta_fex_1","After FEX","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("jpsi_eta_muID_1","After Hypo","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *jpsi_eta_1__3 = new TH1F("jpsi_eta_1__3","J/#psi",10,-3,3);
   jpsi_eta_1__3->SetBinContent(1,7);
   jpsi_eta_1__3->SetBinContent(2,74);
   jpsi_eta_1__3->SetBinContent(3,90);
   jpsi_eta_1__3->SetBinContent(4,104);
   jpsi_eta_1__3->SetBinContent(5,73);
   jpsi_eta_1__3->SetBinContent(6,93);
   jpsi_eta_1__3->SetBinContent(7,78);
   jpsi_eta_1__3->SetBinContent(8,102);
   jpsi_eta_1__3->SetBinContent(9,49);
   jpsi_eta_1__3->SetBinContent(10,11);
   jpsi_eta_1__3->SetBinError(1,2.645751);
   jpsi_eta_1__3->SetBinError(2,8.602325);
   jpsi_eta_1__3->SetBinError(3,9.486833);
   jpsi_eta_1__3->SetBinError(4,10.19804);
   jpsi_eta_1__3->SetBinError(5,8.544004);
   jpsi_eta_1__3->SetBinError(6,9.643651);
   jpsi_eta_1__3->SetBinError(7,8.831761);
   jpsi_eta_1__3->SetBinError(8,10.0995);
   jpsi_eta_1__3->SetBinError(9,7);
   jpsi_eta_1__3->SetBinError(10,3.316625);
   jpsi_eta_1__3->SetMinimum(0);
   jpsi_eta_1__3->SetMaximum(218.4);
   jpsi_eta_1__3->SetEntries(681);
   jpsi_eta_1__3->SetDirectory(0);
   jpsi_eta_1__3->SetStats(0);
   jpsi_eta_1__3->SetLineWidth(2);
   jpsi_eta_1__3->SetMarkerStyle(20);
   jpsi_eta_1__3->SetMarkerSize(1.2);
   jpsi_eta_1__3->GetXaxis()->SetTitle(" sub-leading muon #eta");
   jpsi_eta_1__3->GetXaxis()->SetLabelFont(42);
   jpsi_eta_1__3->GetXaxis()->SetLabelSize(0.05);
   jpsi_eta_1__3->GetXaxis()->SetTitleSize(0.05);
   jpsi_eta_1__3->GetXaxis()->SetTitleOffset(1.4);
   jpsi_eta_1__3->GetXaxis()->SetTitleFont(42);
   jpsi_eta_1__3->GetYaxis()->SetTitle("No. of candidates");
   jpsi_eta_1__3->GetYaxis()->SetLabelFont(42);
   jpsi_eta_1__3->GetYaxis()->SetLabelSize(0.05);
   jpsi_eta_1__3->GetYaxis()->SetTitleSize(0.05);
   jpsi_eta_1__3->GetYaxis()->SetTitleOffset(1.4);
   jpsi_eta_1__3->GetYaxis()->SetTitleFont(42);
   jpsi_eta_1__3->GetZaxis()->SetLabelFont(42);
   jpsi_eta_1__3->GetZaxis()->SetLabelSize(0.05);
   jpsi_eta_1__3->GetZaxis()->SetTitleSize(0.05);
   jpsi_eta_1__3->GetZaxis()->SetTitleFont(42);
   jpsi_eta_1__3->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.5205747,0.9390678,0.5894253,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *text = pt->AddText("J/#psi");
   pt->Draw();
   c_jpsi_eta->Modified();
   c_jpsi_eta->cd();
   c_jpsi_eta->SetSelected(c_jpsi_eta);
}
