/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

{
//=========Macro generated from canvas: c_jpsi_pt/c_jpsi_pt
//=========  (Thu Jun 24 16:31:16 2010) by ROOT version5.26/00
   TCanvas *c_jpsi_pt = new TCanvas("c_jpsi_pt", "c_jpsi_pt",15,34,700,500);
   gStyle->SetOptFit(1);
   c_jpsi_pt->Range(1.341772,-114.9474,10.4557,603.4737);
   c_jpsi_pt->SetFillColor(0);
   c_jpsi_pt->SetBorderMode(0);
   c_jpsi_pt->SetBorderSize(2);
   c_jpsi_pt->SetTickx(1);
   c_jpsi_pt->SetTicky(1);
   c_jpsi_pt->SetLeftMargin(0.16);
   c_jpsi_pt->SetRightMargin(0.05);
   c_jpsi_pt->SetTopMargin(0.08);
   c_jpsi_pt->SetBottomMargin(0.16);
   c_jpsi_pt->SetFrameBorderMode(0);
   c_jpsi_pt->SetFrameBorderMode(0);
   
   TH1F *jpsi_pt_1 = new TH1F("jpsi_pt_1","J/#psi",10,2.8,10);
   jpsi_pt_1->SetBinContent(1,260);
   jpsi_pt_1->SetBinContent(2,201);
   jpsi_pt_1->SetBinContent(3,99);
   jpsi_pt_1->SetBinContent(4,48);
   jpsi_pt_1->SetBinContent(5,27);
   jpsi_pt_1->SetBinContent(6,31);
   jpsi_pt_1->SetBinContent(7,1);
   jpsi_pt_1->SetBinContent(8,4);
   jpsi_pt_1->SetBinContent(9,2);
   jpsi_pt_1->SetBinContent(10,1);
   jpsi_pt_1->SetBinContent(11,7);
   jpsi_pt_1->SetBinError(1,16.12452);
   jpsi_pt_1->SetBinError(2,14.17745);
   jpsi_pt_1->SetBinError(3,9.949874);
   jpsi_pt_1->SetBinError(4,6.928203);
   jpsi_pt_1->SetBinError(5,5.196152);
   jpsi_pt_1->SetBinError(6,5.567764);
   jpsi_pt_1->SetBinError(7,1);
   jpsi_pt_1->SetBinError(8,2);
   jpsi_pt_1->SetBinError(9,1.414214);
   jpsi_pt_1->SetBinError(10,1);
   jpsi_pt_1->SetBinError(11,2.645751);
   jpsi_pt_1->SetMinimum(0);
   jpsi_pt_1->SetMaximum(546);
   jpsi_pt_1->SetEntries(681);
   jpsi_pt_1->SetStats(0);
   jpsi_pt_1->SetLineWidth(2);
   jpsi_pt_1->SetMarkerStyle(20);
   jpsi_pt_1->SetMarkerSize(1.2);
   jpsi_pt_1->GetXaxis()->SetTitle(" sub-leading muon p_{T} (GeV)");
   jpsi_pt_1->GetXaxis()->SetLabelFont(42);
   jpsi_pt_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_pt_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_pt_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_pt_1->GetXaxis()->SetTitleFont(42);
   jpsi_pt_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_pt_1->GetYaxis()->SetLabelFont(42);
   jpsi_pt_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_pt_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_pt_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_pt_1->GetYaxis()->SetTitleFont(42);
   jpsi_pt_1->GetZaxis()->SetLabelFont(42);
   jpsi_pt_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_pt_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_pt_1->GetZaxis()->SetTitleFont(42);
   jpsi_pt_1->Draw("");
   
   TH1F *jpsi_pt_trk_1 = new TH1F("jpsi_pt_trk_1","J/#psi",10,2.8,10);
   jpsi_pt_trk_1->SetBinContent(1,250);
   jpsi_pt_trk_1->SetBinContent(2,192);
   jpsi_pt_trk_1->SetBinContent(3,95);
   jpsi_pt_trk_1->SetBinContent(4,46);
   jpsi_pt_trk_1->SetBinContent(5,24);
   jpsi_pt_trk_1->SetBinContent(6,31);
   jpsi_pt_trk_1->SetBinContent(7,1);
   jpsi_pt_trk_1->SetBinContent(8,4);
   jpsi_pt_trk_1->SetBinContent(9,2);
   jpsi_pt_trk_1->SetBinContent(10,1);
   jpsi_pt_trk_1->SetBinContent(11,5);
   jpsi_pt_trk_1->SetMinimum(0);
   jpsi_pt_trk_1->SetMaximum(375);
   jpsi_pt_trk_1->SetEntries(651);
   jpsi_pt_trk_1->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ff0000");
   jpsi_pt_trk_1->SetFillColor(ci);
   jpsi_pt_trk_1->SetLineWidth(2);
   jpsi_pt_trk_1->SetMarkerStyle(20);
   jpsi_pt_trk_1->SetMarkerSize(1.2);
   jpsi_pt_trk_1->GetXaxis()->SetTitle(" sub-leading muon p_{T} (GeV)");
   jpsi_pt_trk_1->GetXaxis()->SetLabelFont(42);
   jpsi_pt_trk_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_pt_trk_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_pt_trk_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_pt_trk_1->GetXaxis()->SetTitleFont(42);
   jpsi_pt_trk_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_pt_trk_1->GetYaxis()->SetLabelFont(42);
   jpsi_pt_trk_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_pt_trk_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_pt_trk_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_pt_trk_1->GetYaxis()->SetTitleFont(42);
   jpsi_pt_trk_1->GetZaxis()->SetLabelFont(42);
   jpsi_pt_trk_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_pt_trk_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_pt_trk_1->GetZaxis()->SetTitleFont(42);
   jpsi_pt_trk_1->Draw("same");
   
   TH1F *jpsi_pt_fex_1 = new TH1F("jpsi_pt_fex_1","J/#psi",10,2.8,10);
   jpsi_pt_fex_1->SetBinContent(1,199);
   jpsi_pt_fex_1->SetBinContent(2,169);
   jpsi_pt_fex_1->SetBinContent(3,86);
   jpsi_pt_fex_1->SetBinContent(4,42);
   jpsi_pt_fex_1->SetBinContent(5,23);
   jpsi_pt_fex_1->SetBinContent(6,27);
   jpsi_pt_fex_1->SetBinContent(7,1);
   jpsi_pt_fex_1->SetBinContent(8,4);
   jpsi_pt_fex_1->SetBinContent(9,2);
   jpsi_pt_fex_1->SetBinContent(10,1);
   jpsi_pt_fex_1->SetBinContent(11,5);
   jpsi_pt_fex_1->SetMinimum(0);
   jpsi_pt_fex_1->SetMaximum(298.5);
   jpsi_pt_fex_1->SetEntries(559);
   jpsi_pt_fex_1->SetStats(0);

   ci = TColor::GetColor("#00ff00");
   jpsi_pt_fex_1->SetFillColor(ci);
   jpsi_pt_fex_1->SetLineWidth(2);
   jpsi_pt_fex_1->SetMarkerStyle(20);
   jpsi_pt_fex_1->SetMarkerSize(1.2);
   jpsi_pt_fex_1->GetXaxis()->SetTitle(" sub-leading muon p_{T} (GeV)");
   jpsi_pt_fex_1->GetXaxis()->SetLabelFont(42);
   jpsi_pt_fex_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_pt_fex_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_pt_fex_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_pt_fex_1->GetXaxis()->SetTitleFont(42);
   jpsi_pt_fex_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_pt_fex_1->GetYaxis()->SetLabelFont(42);
   jpsi_pt_fex_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_pt_fex_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_pt_fex_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_pt_fex_1->GetYaxis()->SetTitleFont(42);
   jpsi_pt_fex_1->GetZaxis()->SetLabelFont(42);
   jpsi_pt_fex_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_pt_fex_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_pt_fex_1->GetZaxis()->SetTitleFont(42);
   jpsi_pt_fex_1->Draw("same");
   
   TH1F *jpsi_pt_muID_1 = new TH1F("jpsi_pt_muID_1","J/#psi",10,2.8,10);
   jpsi_pt_muID_1->SetBinContent(1,179);
   jpsi_pt_muID_1->SetBinContent(2,157);
   jpsi_pt_muID_1->SetBinContent(3,79);
   jpsi_pt_muID_1->SetBinContent(4,38);
   jpsi_pt_muID_1->SetBinContent(5,22);
   jpsi_pt_muID_1->SetBinContent(6,26);
   jpsi_pt_muID_1->SetBinContent(7,1);
   jpsi_pt_muID_1->SetBinContent(8,4);
   jpsi_pt_muID_1->SetBinContent(9,2);
   jpsi_pt_muID_1->SetBinContent(10,1);
   jpsi_pt_muID_1->SetBinContent(11,5);
   jpsi_pt_muID_1->SetMinimum(0);
   jpsi_pt_muID_1->SetMaximum(268.5);
   jpsi_pt_muID_1->SetEntries(514);
   jpsi_pt_muID_1->SetStats(0);

   ci = TColor::GetColor("#ffff00");
   jpsi_pt_muID_1->SetFillColor(ci);
   jpsi_pt_muID_1->SetLineWidth(2);
   jpsi_pt_muID_1->SetMarkerStyle(20);
   jpsi_pt_muID_1->SetMarkerSize(1.2);
   jpsi_pt_muID_1->GetXaxis()->SetTitle(" sub-leading muon p_{T} (GeV)");
   jpsi_pt_muID_1->GetXaxis()->SetLabelFont(42);
   jpsi_pt_muID_1->GetXaxis()->SetLabelSize(0.05);
   jpsi_pt_muID_1->GetXaxis()->SetTitleSize(0.05);
   jpsi_pt_muID_1->GetXaxis()->SetTitleOffset(1.4);
   jpsi_pt_muID_1->GetXaxis()->SetTitleFont(42);
   jpsi_pt_muID_1->GetYaxis()->SetTitle("No. of candidates");
   jpsi_pt_muID_1->GetYaxis()->SetLabelFont(42);
   jpsi_pt_muID_1->GetYaxis()->SetLabelSize(0.05);
   jpsi_pt_muID_1->GetYaxis()->SetTitleSize(0.05);
   jpsi_pt_muID_1->GetYaxis()->SetTitleOffset(1.4);
   jpsi_pt_muID_1->GetYaxis()->SetTitleFont(42);
   jpsi_pt_muID_1->GetZaxis()->SetLabelFont(42);
   jpsi_pt_muID_1->GetZaxis()->SetLabelSize(0.05);
   jpsi_pt_muID_1->GetZaxis()->SetTitleSize(0.05);
   jpsi_pt_muID_1->GetZaxis()->SetTitleFont(42);
   jpsi_pt_muID_1->Draw("same");
   
   TLegend *leg = new TLegend(0.55,0.3,0.9,0.5,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("jpsi_pt_1","Offline J/#psi","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry=leg->AddEntry("jpsi_pt_trk_1","After Tracking","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("jpsi_pt_fex_1","After FEX","f");

   ci = TColor::GetColor("#00ff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("jpsi_pt_muID_1","After Hypo","f");

   ci = TColor::GetColor("#ffff00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   
   TH1F *jpsi_pt_1__2 = new TH1F("jpsi_pt_1__2","J/#psi",10,2.8,10);
   jpsi_pt_1__2->SetBinContent(1,260);
   jpsi_pt_1__2->SetBinContent(2,201);
   jpsi_pt_1__2->SetBinContent(3,99);
   jpsi_pt_1__2->SetBinContent(4,48);
   jpsi_pt_1__2->SetBinContent(5,27);
   jpsi_pt_1__2->SetBinContent(6,31);
   jpsi_pt_1__2->SetBinContent(7,1);
   jpsi_pt_1__2->SetBinContent(8,4);
   jpsi_pt_1__2->SetBinContent(9,2);
   jpsi_pt_1__2->SetBinContent(10,1);
   jpsi_pt_1__2->SetBinContent(11,7);
   jpsi_pt_1__2->SetBinError(1,16.12452);
   jpsi_pt_1__2->SetBinError(2,14.17745);
   jpsi_pt_1__2->SetBinError(3,9.949874);
   jpsi_pt_1__2->SetBinError(4,6.928203);
   jpsi_pt_1__2->SetBinError(5,5.196152);
   jpsi_pt_1__2->SetBinError(6,5.567764);
   jpsi_pt_1__2->SetBinError(7,1);
   jpsi_pt_1__2->SetBinError(8,2);
   jpsi_pt_1__2->SetBinError(9,1.414214);
   jpsi_pt_1__2->SetBinError(10,1);
   jpsi_pt_1__2->SetBinError(11,2.645751);
   jpsi_pt_1__2->SetMinimum(0);
   jpsi_pt_1__2->SetMaximum(546);
   jpsi_pt_1__2->SetEntries(681);
   jpsi_pt_1__2->SetDirectory(0);
   jpsi_pt_1__2->SetStats(0);
   jpsi_pt_1__2->SetLineWidth(2);
   jpsi_pt_1__2->SetMarkerStyle(20);
   jpsi_pt_1__2->SetMarkerSize(1.2);
   jpsi_pt_1__2->GetXaxis()->SetTitle(" sub-leading muon p_{T} (GeV)");
   jpsi_pt_1__2->GetXaxis()->SetLabelFont(42);
   jpsi_pt_1__2->GetXaxis()->SetLabelSize(0.05);
   jpsi_pt_1__2->GetXaxis()->SetTitleSize(0.05);
   jpsi_pt_1__2->GetXaxis()->SetTitleOffset(1.4);
   jpsi_pt_1__2->GetXaxis()->SetTitleFont(42);
   jpsi_pt_1__2->GetYaxis()->SetTitle("No. of candidates");
   jpsi_pt_1__2->GetYaxis()->SetLabelFont(42);
   jpsi_pt_1__2->GetYaxis()->SetLabelSize(0.05);
   jpsi_pt_1__2->GetYaxis()->SetTitleSize(0.05);
   jpsi_pt_1__2->GetYaxis()->SetTitleOffset(1.4);
   jpsi_pt_1__2->GetYaxis()->SetTitleFont(42);
   jpsi_pt_1__2->GetZaxis()->SetLabelFont(42);
   jpsi_pt_1__2->GetZaxis()->SetLabelSize(0.05);
   jpsi_pt_1__2->GetZaxis()->SetTitleSize(0.05);
   jpsi_pt_1__2->GetZaxis()->SetTitleFont(42);
   jpsi_pt_1__2->Draw("sameaxis");
   
   TPaveText *pt = new TPaveText(0.5205747,0.9390678,0.5894253,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *text = pt->AddText("J/#psi");
   pt->Draw();
   c_jpsi_pt->Modified();
   c_jpsi_pt->cd();
   c_jpsi_pt->SetSelected(c_jpsi_pt);
}
