/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

#ifndef MuonChainIdMap_h
#define MuonChainIdMap_h
void MuonTriggerMatching::createChainIdMapFromFile() {
  std::cerr << "MuonTriggerMatching\t" << "inf> " << "Create ChainIdMap from TrigMuonEfficiency/MuonChainIdMap.h.\n";
  std::cerr << std::endl;

  std::map<std::string, int> ChainIdMap;
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu18",                      10937));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu18_medium",               10941));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu18_MG",                   10975));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu18_MG_medium",            10824));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu40_MSonly_barrel",        10944));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu40_MSonly_barrel_medium", 10874));
  ChainIdMap.insert(std::pair<std::string, int>("L2_mu15",                      131));
  ChainIdMap.insert(std::pair<std::string, int>("L2_mu15_medium",               957));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu15",                      10131));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu15_mu10_EFFS",            10943));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu15_mu10_EFFS_medium",     10845));
  ChainIdMap.insert(std::pair<std::string, int>("EF_2mu4",                      10288));
  ChainIdMap.insert(std::pair<std::string, int>("EF_2mu4T",                     10288));
  ChainIdMap.insert(std::pair<std::string, int>("EF_2mu6",                      10135));
  ChainIdMap.insert(std::pair<std::string, int>("EF_2mu10",                     10914));
  ChainIdMap.insert(std::pair<std::string, int>("EF_2mu10_loose",               10274));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu20it_tight",              10970));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu24i_tight",               10785));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu36_tight",                10950));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu40_MSonly_barrel_tight",  10870));
  ChainIdMap.insert(std::pair<std::string, int>("EF_mu18_tight_mu8_EFFS",       10545));
  ChainIdMap.insert(std::pair<std::string, int>("EF_2mu13",                     10823));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(-1, ChainIdMap));

  std::map<std::string, int> ChainIdMap1051;
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_mu18",               10937));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_mu18_MG",            10975));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_mu40_MSonly_barrel", 10944));
  ChainIdMap1051.insert(std::pair<std::string, int>("L2_mu15",                 943));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_mu15",               10131));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_mu15_mu10_EFFS",     10943));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_2mu4",               10288));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_2mu4T",              10288));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_2mu6",               10135));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_2mu10",              10914));
  ChainIdMap1051.insert(std::pair<std::string, int>("EF_2mu10_loose",        10274));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1051, ChainIdMap1051));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1052, ChainIdMap1051));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1053, ChainIdMap1051));
  
  std::map<std::string, int> ChainIdMap1122;
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu18",                      10937));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu18_medium",               10941));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu18_MG",                   10975));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu18_MG_medium",            10824));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu40_MSonly_barrel",        10944));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu40_MSonly_barrel_medium", 10874));
  ChainIdMap1122.insert(std::pair<std::string, int>("L2_mu15",                        131));
  ChainIdMap1122.insert(std::pair<std::string, int>("L2_mu15_medium",                 136));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu15",                      10131));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu15_mu10_EFFS",            10943));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_mu15_mu10_EFFS_medium",     10845));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_2mu4",                      10288));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_2mu4T",                     10288));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_2mu6",                      10135));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_2mu10",                     10914));
  ChainIdMap1122.insert(std::pair<std::string, int>("EF_2mu10_loose",               10274));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(295,  ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(308,  ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(310,  ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1259, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1255, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1254, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1237, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1236, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1232, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1231, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1228, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1223, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1216, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1215, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1213, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1208, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1187, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1190, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1187, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1176, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1172, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1170, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1168, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1164, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1163, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1161, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1141, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1137, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1132, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1127, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1123, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1122, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1101, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1096, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1094, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1087, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1085, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1082, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1078, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1053, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1052, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1051, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1048, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1044, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1043, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1039, ChainIdMap1122));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1038, ChainIdMap1122));
  
  std::map<std::string, int> ChainIdMap325;
  ChainIdMap325.insert(std::pair<std::string, int>("L2_mu18_tight"  ,               943));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu8",                      10815));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu18_tight"  ,             10943));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu15",                     10840));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu18",                       850));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu20it_tight",             10970));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu24_tight",               10944));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu24i_tight",              10785));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu36_tight",               10950));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu40_MSonly_barrel_tight", 10870));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu18_tight_mu8_EFFS",      10545));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_2mu13",                    10823));
  ChainIdMap325.insert(std::pair<std::string, int>("EF_mu24_j65_a4tchad_EFxe40_tclcw", 10109));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(325,  ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1369, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1370, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1372, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1373, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1374, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1375, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1388, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1389, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1393, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1396, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1398, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1399, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1404, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1407, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1409, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1413, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1428, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1430, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1433, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1439, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1441, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1443, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1445, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1446, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1453, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1459, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1487, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1505, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1511, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1514, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1518, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1522, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1529, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1532, ChainIdMap325));
  m_MapOfChainIdMap.insert(std::pair<int, std::map<std::string, int> >(1534, ChainIdMap325));
  
}
#endif
