# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addService
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ1FieldSvc", "Q1")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ2FieldSvc", "Q2")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ3FieldSvc", "Q3")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getD1FieldSvc", "D1")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getD2FieldSvc", "D2")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ4FieldSvc", "Q4")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ5FieldSvc", "Q5")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ6FieldSvc", "Q6")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ7FieldSvc", "Q7")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ1hkickFieldSvc", "Q1HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ1vkickFieldSvc", "Q1VKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ2hkickFieldSvc", "Q2HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ2vkickFieldSvc", "Q2VKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ3hkickFieldSvc", "Q3HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ3vkickFieldSvc", "Q3VKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ4vkickAFieldSvc", "Q4VKickA")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ4hkickFieldSvc", "Q4HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ4vkickBFieldSvc", "Q4VKickB")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ5hkickFieldSvc", "Q5HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfigLegacy.getQ6vkickFieldSvc", "Q6VKick")
