# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addService
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ1FieldSvc", "Q1")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ2FieldSvc", "Q2")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ3FieldSvc", "Q3")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getD1FieldSvc", "D1")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getD2FieldSvc", "D2")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ4FieldSvc", "Q4")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ5FieldSvc", "Q5")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ6FieldSvc", "Q6")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ7FieldSvc", "Q7")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ1hkickFieldSvc", "Q1HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ1vkickFieldSvc", "Q1VKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ2hkickFieldSvc", "Q2HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ2vkickFieldSvc", "Q2VKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ3hkickFieldSvc", "Q3HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ3vkickFieldSvc", "Q3VKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ4vkickAFieldSvc", "Q4VKickA")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ4hkickFieldSvc", "Q4HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ4vkickBFieldSvc", "Q4VKickB")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ5hkickFieldSvc", "Q5HKick")
addService("ForwardRegionMgField.ForwardRegionMgFieldConfig.getQ6vkickFieldSvc", "Q6VKick")
