# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

from PowhegConfig_bb import *
from PowhegConfig_DMS_tloop import *
from PowhegConfig_DMV import *
from PowhegConfig_DMGG import *
from PowhegConfig_ggF_H import *
from PowhegConfig_ggF_HZ import *
from PowhegConfig_Hj import *
from PowhegConfig_Hjj import *
from PowhegConfig_HWj import *
from PowhegConfig_HZj import *
from PowhegConfig_jj import *
from PowhegConfig_jjj import *
from PowhegConfig_ssWWjj import *
from PowhegConfig_t_sch import *
from PowhegConfig_tt import *
from PowhegConfig_ttH import *
from PowhegConfig_ttj import *
from PowhegConfig_VBF_H import *
from PowhegConfig_VBF_ssWW import *
from PowhegConfig_VBF_W import *
from PowhegConfig_VBF_Z import *
from PowhegConfig_W import *
from PowhegConfig_W_EW import *
from PowhegConfig_Wj import *
from PowhegConfig_Wjj import *
from PowhegConfig_Wt_DR import *
from PowhegConfig_Wt_DS import *
from PowhegConfig_WW import *
from PowhegConfig_WZ import *
from PowhegConfig_Z import *
from PowhegConfig_Z_EW import *
from PowhegConfig_Zj import *
from PowhegConfig_Zjj import *
from PowhegConfig_ZZ import *
