#!/bin/sh

DATADIR=/afs/cern.ch/atlas/offline/test/POOLCollectionTools
TRF=POOLUtilityRun_trf.py
UTIL=CollAppend
XMLFILE=$UTIL.test.xml
#RELEASE=AtlasPOOL,takeFromEnv

# remove detritus from previous tests
rm -f authentication.xml
rm -f PoolCollectionCatalog.xml
ln -s $DATADIR/authentication.xml .

get_files CollAppend.test.xml

# run the test
which $TRF
if [[ $? -ne 0 ]]; then
  echo "ERROR: $TRF not found"
  exit 2
fi
cmd="$TRF $UTIL $XMLFILE"
#cmd="$TRF $UTIL $XMLFILE $RELEASE"
echo $cmd
$cmd

