#!/bin/sh

DATADIR=/afs/cern.ch/atlas/offline/test/POOLCollectionTools
INPUT=$DATADIR/Ryan_Buckingham_data10_7TeV_debugrec_hltacc_f243_m435_READ_1271245689_.root
INPUT2=$DATADIR/Sky_French_data10_7TeV_physics_MinBias_f238_m427_READ_1271338106_.root
OUTPUT=atn_test_tagMergeAtlas.root
TRF=tagMerge_trf.py
RELEASE=Atlas,takeFromEnv

# remove detritus from previous tests
rm -f $TRF
rm -f PoolCollectionCatalog.xml
rm -f $OUTPUT

# run the test
which $TRF
if [[ $? -ne 0 ]]; then
  echo "ERROR: $TRF not found"
  exit 2
fi

# Do first file
cmd="$TRF $INPUT $OUTPUT $RELEASE"
echo $cmd
$cmd
# Do second file
cmd="$TRF $INPUT2 $OUTPUT $RELEASE"
echo $cmd
$cmd
# Dump metadata
cmd="CollListMetadata -src PFN:$OUTPUT RootCollection"
echo $cmd
$cmd

