/*
  Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration
*/

#ifndef LARRECEVENT_LAREVENTBITINFO_H
#define LARRECEVENT_LAREVENTBITINFO_H

namespace LArEventBitInfo {
  enum   LARFLAGREASON {
    BADFEBS=0, 
    MEDIUMSATURATEDQ=1, 
    TIGHTSATURATEDQ=2, 
    NOISEBURSTVETO=3, 
    DATACORRUPTED=4, 
    DATACORRUPTEDVETO=5, 
    BADFEBS_W=6,
    MININOISEBURSTLOOSE=7,
    MININOISEBURSTTIGHT=8,
    MININOISEBURSTTIGHT_PSVETO=9
  };
}

#endif
