#include "LArL1Sim/LArTTL1Maker.h"
#include "LArL1Sim/LArSCL1Maker.h"
#include "LArL1Sim/LArTTL1Calib.h"

DECLARE_COMPONENT( LArTTL1Maker )
DECLARE_COMPONENT( LArSCL1Maker )
DECLARE_COMPONENT( LArTTL1Calib )

