ToolSvc.InDetPixelClusterOnTrackTool.CorrectDigitalCentroid=True
ToolSvc.InDetPixelClusterOnTrackTool.PositionStrategy=0
ToolSvc.InDetPixelClusterOnTrackTool.ErrorStrategy=1
ToolSvc.InDetPixelClusterOnTrackToolDigital.PositionStrategy=0
ToolSvc.InDetPixelClusterOnTrackToolDigital.ErrorStrategy=1
ToolSvc.InDetSCT_ClusterOnTrackTool.CorrectionStrategy=0
ToolSvc.InDetSCT_ClusterOnTrackTool.ErrorStrategy=0
