from AthenaCommon.DetFlags import DetFlags
DetFlags.ID_setOn()
DetFlags.TRT_setOff()
DetFlags.detdescr.TRT_setOff()
DetFlags.makeRIO.TRT_setOff()
DetFlags.BCM_setOff()
DetFlags.detdescr.BCM_setOff()
DetFlags.makeRIO.BCM_setOff()
DetFlags.DBM_setOff()
DetFlags.detdescr.DBM_setOff()
DetFlags.makeRIO.DBM_setOff()
DetFlags.Calo_setOn()
DetFlags.Muon_setOn()
DetFlags.Truth_setOn()
