# Copyright (C) 2002-2019 CERN for the benefit of the ATLAS collaboration
# flake8: noqa
import TriggerJobOpts.EgammaSliceFlags
import TriggerJobOpts.JetSliceFlags
import TriggerJobOpts.BjetSliceFlags
import TriggerJobOpts.MuonSliceFlags
import TriggerJobOpts.METSliceFlags
import TriggerJobOpts.TauSliceFlags
import TriggerJobOpts.BphysicsSliceFlags
import TriggerJobOpts.MinBiasSliceFlags
import TriggerJobOpts.HeavyIonSliceFlags
import TriggerJobOpts.CombinedSliceFlags
import TriggerJobOpts.CosmicSliceFlags
import TriggerJobOpts.CalibSliceFlags
import TriggerJobOpts.StreamingSliceFlags
import TriggerJobOpts.MonitorSliceFlags
import TriggerJobOpts.BeamspotSliceFlags
import TriggerJobOpts.EnhancedBiasSliceFlags
import TriggerJobOpts.UnconventionalTrackingSliceFlags
import TriggerJobOpts.TestSliceFlags
