-- PROJECT: ATLAS MDT Calibration DB
-- AUTHOR: Elisabetta.Vilucchi@lnf.infn.it, celio@roma3.infn.it
-- DATE: May 08
-- VERSION v1r1

--USAGE:
--sqlplus <USER_NAME>/<USER_PASSWORD> @mdt_rt_map_r_table.sql <USER_NAME> <SITE_NAME>(2 characters like MU,MI,RM...) <USER_PASSOWRD> <TABLESPCE_NAME>

--DROP TABLE &1.."MDT_RT_MAP_R";
CREATE TABLE &1.."MDT_RT_MAP_R" 
("MDT_RT_MAP_R_ID"  NUMBER        NOT NULL ,
"MDT_RT_ID" 	    NUMBER        NOT NULL ,
"MDT_RT_MAP_T_ID"   NUMBER        NOT NULL ,
"BINS"		    NUMBER(4)     NOT NULL ,
"SITE_NAME"         VARCHAR2(2) DEFAULT UPPER('&2') ,
"INSERT_TIME"       VARCHAR2(19),
"R_1"		    NUMBER(8,6)   NOT NULL ,
"R_2"               NUMBER(8,6)   NOT NULL ,
"R_3"               NUMBER(8,6)   NOT NULL ,
"R_4"               NUMBER(8,6)   NOT NULL ,
"R_5"               NUMBER(8,6)   NOT NULL ,
"R_6"               NUMBER(8,6)   NOT NULL ,
"R_7"               NUMBER(8,6)   NOT NULL ,
"R_8"               NUMBER(8,6)   NOT NULL ,
"R_9"               NUMBER(8,6)   NOT NULL ,
"R_10"              NUMBER(8,6)   NOT NULL ,
"R_11"              NUMBER(8,6)   NOT NULL ,
"R_12"              NUMBER(8,6)   NOT NULL ,
"R_13"              NUMBER(8,6)   NOT NULL ,
"R_14"              NUMBER(8,6)   NOT NULL ,
"R_15"              NUMBER(8,6)   NOT NULL ,
"R_16"              NUMBER(8,6)   NOT NULL ,
"R_17"              NUMBER(8,6)   NOT NULL ,
"R_18"              NUMBER(8,6)   NOT NULL ,
"R_19"              NUMBER(8,6)   NOT NULL ,
"R_20"              NUMBER(8,6)   NOT NULL ,
"R_21"              NUMBER(8,6)   NOT NULL ,
"R_22"              NUMBER(8,6)   NOT NULL ,
"R_23"              NUMBER(8,6)   NOT NULL ,
"R_24"              NUMBER(8,6)   NOT NULL ,
"R_25"              NUMBER(8,6)   NOT NULL ,
"R_26"              NUMBER(8,6)   NOT NULL ,
"R_27"              NUMBER(8,6)   NOT NULL ,
"R_28"              NUMBER(8,6)   NOT NULL ,
"R_29"              NUMBER(8,6)   NOT NULL ,
"R_30"              NUMBER(8,6)   NOT NULL ,
"R_31"              NUMBER(8,6)   NOT NULL ,
"R_32"              NUMBER(8,6)   NOT NULL ,
"R_33"              NUMBER(8,6)   NOT NULL ,
"R_34"              NUMBER(8,6)   NOT NULL ,
"R_35"              NUMBER(8,6)   NOT NULL ,
"R_36"              NUMBER(8,6)   NOT NULL ,
"R_37"              NUMBER(8,6)   NOT NULL ,
"R_38"              NUMBER(8,6)   NOT NULL ,
"R_39"              NUMBER(8,6)   NOT NULL ,
"R_40"              NUMBER(8,6)   NOT NULL ,
"R_41"              NUMBER(8,6)   NOT NULL ,
"R_42"              NUMBER(8,6)   NOT NULL ,
"R_43"              NUMBER(8,6)   NOT NULL ,
"R_44"              NUMBER(8,6)   NOT NULL ,
"R_45"              NUMBER(8,6)   NOT NULL ,
"R_46"              NUMBER(8,6)   NOT NULL ,
"R_47"              NUMBER(8,6)   NOT NULL ,
"R_48"              NUMBER(8,6)   NOT NULL ,
"R_49"              NUMBER(8,6)   NOT NULL ,
"R_50"              NUMBER(8,6)   NOT NULL ,
"R_51"              NUMBER(8,6)   NOT NULL ,
"R_52"              NUMBER(8,6)   NOT NULL ,
"R_53"              NUMBER(8,6)   NOT NULL ,
"R_54"              NUMBER(8,6)   NOT NULL ,
"R_55"              NUMBER(8,6)   NOT NULL ,
"R_56"              NUMBER(8,6)   NOT NULL ,
"R_57"              NUMBER(8,6)   NOT NULL ,
"R_58"              NUMBER(8,6)   NOT NULL ,
"R_59"              NUMBER(8,6)   NOT NULL ,
"R_60"              NUMBER(8,6)   NOT NULL ,
"R_61"              NUMBER(8,6)   NOT NULL ,
"R_62"              NUMBER(8,6)   NOT NULL ,
"R_63"              NUMBER(8,6)   NOT NULL ,
"R_64"              NUMBER(8,6)   NOT NULL ,
"R_65"              NUMBER(8,6)   NOT NULL ,
"R_66"              NUMBER(8,6)   NOT NULL ,
"R_67"              NUMBER(8,6)   NOT NULL ,
"R_68"              NUMBER(8,6)   NOT NULL ,
"R_69"              NUMBER(8,6)   NOT NULL ,
"R_70"              NUMBER(8,6)   NOT NULL ,
"R_71"              NUMBER(8,6)   NOT NULL ,
"R_72"              NUMBER(8,6)   NOT NULL ,
"R_73"              NUMBER(8,6)   NOT NULL ,
"R_74"              NUMBER(8,6)   NOT NULL ,
"R_75"              NUMBER(8,6)   NOT NULL ,
"R_76"              NUMBER(8,6)   NOT NULL ,
"R_77"              NUMBER(8,6)   NOT NULL ,
"R_78"              NUMBER(8,6)   NOT NULL ,
"R_79"              NUMBER(8,6)   NOT NULL ,
"R_80"              NUMBER(8,6)   NOT NULL ,
"R_81"              NUMBER(8,6)   NOT NULL ,
"R_82"              NUMBER(8,6)   NOT NULL ,
"R_83"              NUMBER(8,6)   NOT NULL ,
"R_84"              NUMBER(8,6)   NOT NULL ,
"R_85"              NUMBER(8,6)   NOT NULL ,
"R_86"              NUMBER(8,6)   NOT NULL ,
"R_87"              NUMBER(8,6)   NOT NULL ,
"R_88"              NUMBER(8,6)   NOT NULL ,
"R_89"              NUMBER(8,6)   NOT NULL ,
"R_90"              NUMBER(8,6)   NOT NULL ,
"R_91"              NUMBER(8,6)   NOT NULL ,
"R_92"              NUMBER(8,6)   NOT NULL ,
"R_93"              NUMBER(8,6)   NOT NULL ,
"R_94"              NUMBER(8,6)   NOT NULL ,
"R_95"              NUMBER(8,6)   NOT NULL ,
"R_96"              NUMBER(8,6)   NOT NULL ,
"R_97"              NUMBER(8,6)   NOT NULL ,
"R_98"              NUMBER(8,6)   NOT NULL ,
"R_99"              NUMBER(8,6)   NOT NULL ,
"R_100"             NUMBER(8,6)   NOT NULL ,
CONSTRAINT "MDT_RT_MAP_R_MDT_RT_ID_REF" FOREIGN KEY ("MDT_RT_ID", "SITE_NAME") REFERENCES &1.."MDT_RT" ("MDT_RT_ID", "SITE_NAME") VALIDATE ,
CONSTRAINT "MDT_RT_MAP_R_MDT_RT_MAP_T_REF" FOREIGN KEY ("MDT_RT_MAP_T_ID", "SITE_NAME") REFERENCES &1.."MDT_RT_MAP_T" ("MDT_RT_MAP_T_ID", "SITE_NAME") VALIDATE ,
CONSTRAINT "MDT_RT_MAP_R_ID_SITE_PR" PRIMARY KEY ("MDT_RT_MAP_R_ID", "SITE_NAME") VALIDATE )
TABLESPACE &4 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K BUFFER_POOL DEFAULT) LOGGING;
