-- PROJECT: ATLAS MDT Calibration DB
-- AUTHOR: Elisabetta.Vilucchi@lnf.infn.it, celio@fis.uniroma3.it
-- DATE: May 08 
-- VERSION v1r1

--USAGE:
--sqlplus <USER_NAME>/<USER_PASSWORD> @mdt_tube_trigger.sql <USER_NAME>

--DROP TRIGGER &1..MDT_TUBE_TRIGGER;
CREATE TRIGGER &1..MDT_TUBE_TRIGGER BEFORE
INSERT ON &1.."MDT_TUBE" REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW
BEGIN

SELECT &1..mdt_tube_sequence.NEXTVAL INTO :NEW.SEQID FROM DUAL;
SELECT TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH:MI AM') INTO :NEW.INSERT_TIME FROM DUAL;

EXCEPTION
WHEN OTHERS THEN
       RAISE;
END MDT_TUBE_TRIGGER;
/
