-- PROJECT: ATLAS MDT Calibration DB
-- AUTHOR: Elisabetta.Vilucchi@lnf.infn.it, celio@roma3.infn.it
-- DATE: May 08
-- VERSION v1r1

--USAGE:
--sqlplus <USER_NAME>/<USER_PASSWORD> @mdt_head_trigger.sql <USER_NAME>

--DROP TRIGGER &1..MDT_HEAD_TRIGGER;
CREATE TRIGGER &1..MDT_HEAD_TRIGGER BEFORE
INSERT ON &1.."MDT_HEAD" REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW BEGIN

SELECT &1..mdt_head_sequence.nextval INTO :NEW.HEAD_ID FROM dual;
SELECT TO_CHAR(SYSTIMESTAMP,'YYYY-MM-DD HH:MI AM') INTO :NEW.INSERT_TIME FROM DUAL;

EXCEPTION
WHEN OTHERS THEN RAISE;
END mdt_head_trigger;
/
