-- PROJECT: ATLAS MDT Calibration DB
-- AUTHOR: Elisabetta.Vilucchi@lnf.infn.it, celio@roma3.infn.it
-- DATE: May 08
-- VERSION v1r1

--USAGE: 
--sqlplus sys/password @sites_table.sql <USER_NAME> <SITE_NAME>(2 characters like MU,MI,RM...) <USER_PASSOWRD> <TABLESPCE_NAME>

--DROP TABLE &1.."SITES";
CREATE TABLE &1.."SITES" ( "NAME" VARCHAR2(2), PRIMARY KEY ("NAME") VALIDATE ) TABLESPACE &4 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K BUFFER_POOL DEFAULT) NOLOGGING;
INSERT INTO &1.."SITES" VALUES ( UPPER('&2') );
