# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addTool
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.PixelHitsTestTool", "PixelHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.SCT_HitsTestTool", "SCT_HitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TrtHitsTestTool", "TrtHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.PileupPixelHitsTestTool", "PileupPixelHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.PileupSCT_HitsTestTool", "PileupSCT_HitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.PileupTrtHitsTestTool", "PileupTrtHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.EMBHitsTestTool", "EMBHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.EMECHitsTestTool", "EMECHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.HECHitsTestTool", "HECHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.FCALHitsTestTool", "FCALHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TileHitsTestTool", "TileHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.CSCHitsTestTool", "CSCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.MDTHitsTestTool", "MDTHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.RPCHitsTestTool", "RPCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TGCHitsTestTool", "TGCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.MMHitsTestTool", "MMHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.sTGCHitsTestTool", "sTGCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.ALFA_SimHitsTestTool", "ALFA_SimHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.ZDCHitsTestTool", "ZDCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.LArActiveCaloCalibHitsTestTool", "LArActiveCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.LArInactiveCaloCalibHitsTestTool", "LArInactiveCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.LArDeadMaterialCaloCalibHitsTestTool", "LArDeadMaterialCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TileActiveCellCaloCalibHitsTestTool", "TileActiveCellCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TileInactiveCellCaloCalibHitsTestTool", "TileInactiveCellCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TileDeadMaterialCaloCalibHitsTestTool", "TileDeadMaterialCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TileCellCaloCalibHitsTestTool", "TileCellCaloCalibHitsTestTool") #old name
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TileDMCaloCalibHitsTestTool", "TileDMCaloCalibHitsTestTool") #old name
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.EvgenTruthTestTool", "EvgenTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.BeamTruthTestTool", "BeamTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.TruthTestTool", "TruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.PileupEvgenTruthTestTool", "PileupEvgenTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.PileupTruthTestTool", "PileupTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.CaloEntryLayerTestTool", "CaloEntryLayerTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.MuonEntryLayerTestTool", "MuonEntryLayerTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.MuonExitLayerTestTool",  "MuonExitLayerTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.getSteppingValidationTool", "G4UA::SteppingValidationTool")
addTool("G4AtlasTests.G4AtlasTestsConfigLegacy.LucidHitsTestTool", "LucidHitsTestTool")
