# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addTool
addTool("G4AtlasTests.G4AtlasTestsConfig.PixelHitsTestTool", "PixelHitsTestTool")              
addTool("G4AtlasTests.G4AtlasTestsConfig.SCT_HitsTestTool", "SCT_HitsTestTool")              
addTool("G4AtlasTests.G4AtlasTestsConfig.TrtHitsTestTool", "TrtHitsTestTool")             
addTool("G4AtlasTests.G4AtlasTestsConfig.PileupPixelHitsTestTool", "PileupPixelHitsTestTool")              
addTool("G4AtlasTests.G4AtlasTestsConfig.PileupSCT_HitsTestTool", "PileupSCT_HitsTestTool")              
addTool("G4AtlasTests.G4AtlasTestsConfig.PileupTrtHitsTestTool", "PileupTrtHitsTestTool")             
#addTool("G4AtlasTests.G4AtlasTestsConfig.LArHitsTestTool", "LArHitsTestTool")             
addTool("G4AtlasTests.G4AtlasTestsConfig.EMBHitsTestTool", "EMBHitsTestTool")             
addTool("G4AtlasTests.G4AtlasTestsConfig.EMECHitsTestTool", "EMECHitsTestTool")            
addTool("G4AtlasTests.G4AtlasTestsConfig.HECHitsTestTool", "HECHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.FCALHitsTestTool", "FCALHitsTestTool")            
addTool("G4AtlasTests.G4AtlasTestsConfig.TileHitsTestTool", "TileHitsTestTool")            
addTool("G4AtlasTests.G4AtlasTestsConfig.CSCHitsTestTool", "CSCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.MDTHitsTestTool", "MDTHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.RPCHitsTestTool", "RPCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.TGCHitsTestTool", "TGCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.MMHitsTestTool", "MMHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.sTGCHitsTestTool", "sTGCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.ALFA_SimHitsTestTool", "ALFA_SimHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.ZDCHitsTestTool", "ZDCHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.LArActiveCaloCalibHitsTestTool", "LArActiveCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.LArInactiveCaloCalibHitsTestTool", "LArInactiveCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.LArDeadMaterialCaloCalibHitsTestTool", "LArDeadMaterialCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.TileActiveCellCaloCalibHitsTestTool", "TileActiveCellCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.TileInactiveCellCaloCalibHitsTestTool", "TileInactiveCellCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.TileDeadMaterialCaloCalibHitsTestTool", "TileDeadMaterialCaloCalibHitsTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.TileCellCaloCalibHitsTestTool", "TileCellCaloCalibHitsTestTool") #old name
addTool("G4AtlasTests.G4AtlasTestsConfig.TileDMCaloCalibHitsTestTool", "TileDMCaloCalibHitsTestTool") #old name
addTool("G4AtlasTests.G4AtlasTestsConfig.EvgenTruthTestTool", "EvgenTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.BeamTruthTestTool", "BeamTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.TruthTestTool", "TruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.PileupEvgenTruthTestTool", "PileupEvgenTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.PileupTruthTestTool", "PileupTruthTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.CaloEntryLayerTestTool", "CaloEntryLayerTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.MuonEntryLayerTestTool", "MuonEntryLayerTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.MuonExitLayerTestTool",  "MuonExitLayerTestTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.getSteppingValidationTool", "G4UA::SteppingValidationTool")
addTool("G4AtlasTests.G4AtlasTestsConfig.LucidHitsTestTool", "LucidHitsTestTool")
