
/*
  Copyright (C) 2002-2019 CERN for the benefit of the ATLAS collaboration
*/

// Originally, this file was autogenerated by CMT with VP1 Factory Code Header File
// Now we add this file to plugins by hand, to simplify the CMake compilation

#include <QtPlugin>
#include "VP1CaloPlugin/VP1CaloPlugin_VP1AutoFactory.h"
#include "VP1CaloPlugin/VP1CaloCellChannel.h"

QStringList VP1CaloPlugin_VP1AutoFactory::channelWidgetsProvided() const
{
  return QStringList()
        << "Calo"
         ;
}

IVP1ChannelWidget * VP1CaloPlugin_VP1AutoFactory::getChannelWidget(const QString & channelwidget)
{
  if (channelwidget == "Calo")
    return new VP1CaloCellChannel();

  return 0;
}

