## Not autogenerated anymore do not overwrite

## method filling an item-list with some data

def _fill( item ):
    item.add(
{'Analysis::TauDetailsContainer': ['TauRecDetailsContainer'],
 'Analysis::TauJetContainer': ['TauRecContainer'],

 'CaloClusterContainer': ['CaloCalTopoCluster',
                          'EMTopoCluster430',
                          'LArClusterEMFrwd',
                          'LArClusterEMSofte',
                          'MuonClusterCollection',
                          'egClusterCollection'],

 'JetCollection': ['AntiKt4LCTopoJets',
                   'AntiKt4TopoEMJets',
                   'AntiKt4TopoJets',
                   'AntiKt4TowerJets',
                   'AntiKt4TruthJets',
                   'AntiKt4TruthPileupJets',
                   'AntiKt6LCTopoJets',
                   'AntiKt6TopoEMJets',
                   'AntiKt6TopoJets',
                   'AntiKt6TowerJets',
                   'AntiKt6TruthJets'],
 'JetKeyDescriptor': ['JetKeyMap'],
 'JetMomentMap': ['AntiKt4LCTopoJetsMomentMap',
                  'AntiKt4TopoEMJetsMomentMap',
                  'AntiKt4TopoJetsMomentMap',
                  'AntiKt4TowerJetsMomentMap',
                  'AntiKt4TruthJetsMomentMap',
                  'AntiKt6LCTopoJetsMomentMap',
                  'AntiKt6TopoEMJetsMomentMap',
                  'AntiKt6TopoJetsMomentMap',
                  'AntiKt6TowerJetsMomentMap',
                  'AntiKt6TruthJetsMomentMap'],


 'RecoTimingObj': ['RAWtoESD_timings',
                   'RAWtoESD_mems',
                   'EVNTtoHITS_timings',
                   'HITStoRDO_timings'],

 'egDetailContainer': ['egDetailAOD'],
 'egammaContainer': ['ElectronAODCollection',
                     'PhotonAODCollection']}
    )
    return

## EOF ##
