#!/bin/sh

# cleanlog
# 
# July 2014
# Script to remove some of the fields from a log
# that are expected to vary.

FILE1=$1
FILE2=$FILE1.clean

# Replace addresses with "address"
sed 's/0x[0-9,a-f,\/]*/address/g' $FILE1 >$FILE2

echo Output is $FILE2
