# Author: Karsten Koeneke (karsten.koeneke@cernSPAMNOT.ch)
# PATCore root stand-alone makefile

PACKAGE          = PATCore
PACKAGE_TRYDEP   = D3PDReader
PACKAGE_CXXFLAGS = 
PACKAGE_LDFLAGS  =
PACKAGE_CLEAN    = PATCore/config.h

include $(ROOTCOREDIR)/Makefile-common
