DROP INDEX master_id_ind;
DROP INDEX type_id_ind;
DROP INDEX type_id_ind_1;
DROP INDEX type2sig_id_ind;
DROP INDEX type_name_ind;
--DROP INDEX sig_config_id_ind1;
DROP INDEX sig_config_name_ind;
DROP INDEX sig_config_recostep_ind;
--DROP INDEX sig_config_data_ind;
--DROP INDEX sig_config_script_ind;
DROP INDEX sig_config_data_hash_ind;
DROP INDEX sig_config_script_hash_ind;
ALTER TABLE mt2type DROP CONSTRAINT mt2type_fk_mt;
ALTER TABLE mt2type DROP CONSTRAINT mt2type_fk_type;
ALTER TABLE type2sig DROP CONSTRAINT type2sig_fk_type;
ALTER TABLE type2sig DROP CONSTRAINT type2sig_fk_sig;
ALTER TABLE master_table DROP CONSTRAINT mt_pk;
ALTER TABLE type_table DROP CONSTRAINT type_pk1;
ALTER TABLE sig_config DROP CONSTRAINT sc_pk;  
ALTER TABLE mt2type DROP CONSTRAINT mt2type_uc;
ALTER TABLE mt2type DROP CONSTRAINT master_id_NN;
ALTER TABLE mt2type DROP CONSTRAINT type_id_NN1;
ALTER TABLE type2sig DROP CONSTRAINT type2sig_uc;
DROP TABLE master_table;
DROP TABLE type_table;
DROP TABLE sig_config;
DROP TABLE mt2type;
DROP TABLE type2sig; 
