DROP INDEX mck_id_index;
DROP INDEX mck_default_index;
DROP INDEX smck_id_index;
DROP INDEX smck_config_hash_index;
DROP INDEX link_mck_index;
DROP INDEX link_smck_index;
ALTER TABLE mck_to_smck_link DROP CONSTRAINT link_smck_fk;
ALTER TABLE mck_to_smck_link DROP CONSTRAINT link_smck_nn;
ALTER TABLE mck_to_smck_link DROP CONSTRAINT link_mck_fk;
ALTER TABLE mck_to_smck_link DROP CONSTRAINT link_mck_nn;
ALTER TABLE mck_to_smck_link DROP CONSTRAINT link_u;
ALTER TABLE smck_table DROP CONSTRAINT smck_config_hash_nn;
ALTER TABLE smck_table DROP CONSTRAINT smck_config_nn;
ALTER TABLE smck_table DROP CONSTRAINT smck_slice_version_nn;
ALTER TABLE smck_table DROP CONSTRAINT smck_slice_version_u;
ALTER TABLE smck_table DROP CONSTRAINT smck_slice_type_nn;
ALTER TABLE smck_table DROP CONSTRAINT smck_pk;
ALTER TABLE mck_table DROP CONSTRAINT mck_default_nn;
ALTER TABLE mck_table DROP CONSTRAINT mck_pk;
DROP TABLE mck_to_smck_link;
DROP TABLE smck_table;
DROP TABLE mck_table;
