#include "../RoIBuilder.h"
#include "../RoIBTester.h"
#include "../RecRoIBTester.h"

DECLARE_NAMESPACE_ALGORITHM_FACTORY( ROIB, RoIBuilder )
DECLARE_NAMESPACE_ALGORITHM_FACTORY( ROIB, RoIBTester )
DECLARE_NAMESPACE_ALGORITHM_FACTORY( ROIB, RecRoIBTester )

