# Copyright (C) 2002-2017 CERN for the benefit of the ATLAS collaboration

# Auto-generated by /mnt/classis03/home3/calib/splitter/trf/AtlasProduction/12.0.6.4/Tools/PyJobTransformsCore/share/ensure_init.py -s=../scripts mdt_calib*_trf.py
