
PACKAGE          = ElectronEfficiencyCorrection
PACKAGE_PRELOAD  = Tree TreePlayer XMLParser XMLIO
PACKAGE_CXXFLAGS = -I/usr/include/libxml2 -g
PACKAGE_BINFLAGS = -lxml2
PACKAGE_DEP      = AsgTools xAODEgamma xAODEventInfo PATCore  PATInterfaces PathResolver
PACKAGE_PEDANTIC = 1
PACKAGE_REFLEX   = 1
include $(ROOTCOREDIR)/Makefile-common
