void MuonTriggerMatching::createChainIdMapFromFile() {
  std::map<std::string, int> ChainIdMap;
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu4", 10127) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu6", 10129) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu10", 10130) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu10_loose", 10962) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu13", 10873) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu13_MG", 10321) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu15", 10131) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu15_mu10_EFFS", 10943) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu15_mu10_EFFS_medium", 10845) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu15_mu10_EFFS_tight", 10545) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu15i", 10483) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu15i_medium", 10484) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu18", 10937) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu18_medium", 10941) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu18_MG", 10975) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu18_MG_medium", 10824) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu20", 10134) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu20_medium", 10138) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu20_MG", 10956) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu20_MG_medium", 10826) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu20_mu10_EFFS_tight", 10532) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu20i", 10132) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu20i_medium", 10133) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu22", 10960) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu22_medium", 10827) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu22_MG", 10950) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu22_MG_medium", 10954) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu24_MG_medium", 10444) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu24_MG_tight", 10841) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu24_medium", 10797) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu24_tight", 10107) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu30_MG_medium", 10825) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu30_MG_tight", 10415) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu30_medium", 10748) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu30_tight", 10582) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu40_MSonly_barrel", 10944) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu40_MSonly_barrel_medium", 10874) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu40_MSonly_tight", 10948) );
  ChainIdMap.insert( std::pair<std::string, int>("EF_mu40_MSonly_tighter", 10946) );
  m_MapOfChainIdMap.insert( std::pair<int, std::map<std::string, int> >(-1, ChainIdMap) );
}
