!
   MODULE M_MB_COMATI
      IMPLICIT NONE
      INTEGER, PARAMETER :: KVOLU=10000, KPLAN=200000, KEDGE=80000, KADGE=30000
      INTEGER, PARAMETER :: KMAJFF=100, KMAJZZ=100, KMANAM=1000
      INTEGER, PARAMETER :: KtransMati=3500
      INTEGER, PARAMETER :: KVOLUmat=2000
      REAL(8), PARAMETER :: Xmat1=150.d0, Ymat1=150.d0
      REAL(8), PARAMETER :: Zmat1=450.d0, Zmat2=600.d0  !< used in trmusc, must be such that Zmat2-Zmat1>Tracking step
      INTEGER, SAVE :: NVMATI, NPMATI, NEMATI, NAMATI, NTMATI, NMANAM
      INTEGER, SAVE :: NVPOSMATI(4), NVNEGMATI(4), NVCENMATI(4)
      INTEGER, SAVE, ALLOCATABLE :: ITRANSMATI(:)
      INTEGER, SAVE, ALLOCATABLE :: NPMAT0(:), NPMAT1(:),  JMATI(:)
      INTEGER, SAVE, ALLOCATABLE :: NEMAT0(:), NEMAT1(:), IAMATI(:)
      INTEGER, SAVE, ALLOCATABLE, TARGET :: IVPOSMATI(:,:), IVNEGMATI(:,:), IVCENMATI(:,:)
      REAL(8), SAVE, ALLOCATABLE :: XYZMATI(:,:), XXMATI(:), YYMATI(:)
      REAL(8), SAVE, ALLOCATABLE :: VXMATI(:,:), VYMATI(:,:), VZMATI(:,:)
      REAL(8), SAVE, ALLOCATABLE :: XMIMATI(:), YMIMATI(:), ZMIMATI(:)
      REAL(8), SAVE, ALLOCATABLE :: XMAMATI(:), YMAMATI(:), ZMAMATI(:)
      REAL(8), SAVE, ALLOCATABLE :: TRANSMATI(:,:,:)
      CHARACTER(8), SAVE, ALLOCATABLE :: CAMATI(:)
   CONTAINS
     SUBROUTINE Init_MB_Comati
       NVMATI = 0
       NPMATI = 0
       NEMATI = 0
       NAMATI = 0
       NTMATI = 0
       NMANAM = 0
       NVPOSMATI(:) = 0
       NVNEGMATI(:) = 0
       NVCENMATI(:) = 0
       IF( .NOT.ALLOCATED(ITRANSMATI) ) THEN
         ALLOCATE( ITRANSMATI(KVOLU) )
         ALLOCATE( TRANSMATI(3,4,KtransMati) )
         ALLOCATE( NPMAT0(KVOLU) )
         ALLOCATE( NPMAT1(KVOLU) )
         ALLOCATE(  JMATI(KVOLU) )
         ALLOCATE( NEMAT0(KPLAN) )
         ALLOCATE( NEMAT1(KPLAN) )
         ALLOCATE( IAMATI(KEDGE) )
         ALLOCATE( IVPOSMATI(KVOLUmat,4) )
         ALLOCATE( IVNEGMATI(KVOLUmat,4) )
         ALLOCATE( IVCENMATI(KVOLUmat,4) )
         ALLOCATE( XYZMATI(3,KADGE) )
         ALLOCATE( XXMATI(KEDGE) )
         ALLOCATE( YYMATI(KEDGE) )
         ALLOCATE( VXMATI(4,KPLAN) )
         ALLOCATE( VYMATI(4,KPLAN) )
         ALLOCATE( VZMATI(4,KPLAN) )
         ALLOCATE( XMIMATI(KVOLU) )
         ALLOCATE( YMIMATI(KVOLU) )
         ALLOCATE( ZMIMATI(KVOLU) )
         ALLOCATE( XMAMATI(KVOLU) )
         ALLOCATE( YMAMATI(KVOLU) )
         ALLOCATE( ZMAMATI(KVOLU) )
         ALLOCATE( CAMATI(KMANAM) )
       ENDIF
       CALL INITRANSMATI
     END SUBROUTINE Init_MB_Comati
!
     SUBROUTINE Decode_Jmati( IV, AAA,MAT,JFF,JZZ )
     INTEGER,      INTENT(IN)  :: IV
     INTEGER,      INTENT(OUT) :: MAT, JFF, JZZ
     CHARACTER(8), INTENT(OUT) :: AAA
     INTEGER :: N1, N2, JAA
       N2  = JMATI(IV)
       N1  = N2 / KMAJFF
       JFF = N2 - N1*KMAJFF
       N2  = N1 / KMAJZZ
       JZZ = N1 - N2*KMAJZZ
       MAT = N2 / KMANAM
       JAA = N2 - MAT*KMANAM
       AAA = CAMATI(JAA)
     END SUBROUTINE Decode_Jmati
!
     SUBROUTINE Free_MB_Comati
       IF( ALLOCATED(ITRANSMATI) ) THEN
         DEALLOCATE(ITRANSMATI)
         DEALLOCATE(TRANSMATI)
         DEALLOCATE(NPMAT0)
         DEALLOCATE(NPMAT1)
         DEALLOCATE(JMATI)
         DEALLOCATE(NEMAT0)
         DEALLOCATE(NEMAT1)
         DEALLOCATE(IAMATI)
         DEALLOCATE(IVPOSMATI)
         DEALLOCATE(IVNEGMATI)
         DEALLOCATE(IVCENMATI)
         DEALLOCATE(XYZMATI)
         DEALLOCATE(XXMATI)
         DEALLOCATE(YYMATI)
         DEALLOCATE(VXMATI)
         DEALLOCATE(VYMATI)
         DEALLOCATE(VZMATI)
         DEALLOCATE(XMIMATI)
         DEALLOCATE(YMIMATI)
         DEALLOCATE(ZMIMATI)
         DEALLOCATE(XMAMATI)
         DEALLOCATE(YMAMATI)
         DEALLOCATE(ZMAMATI)
         DEALLOCATE(CAMATI)
       ENDIF
     END SUBROUTINE Free_MB_Comati
   END MODULE M_MB_COMATI
!
