// Originally autogenerated by CMT with VP1 Factory Code Header File (Fri Aug 19 13:36:52 CEST 2016)
// Now we add this file to plugins by hand, to simplify the CMake compilation

#include <QtPlugin>
#include "VP13DCocktailPlugin/VP13DCocktailPlugin_VP1AutoFactory.h"
#include "VP13DCocktailPlugin/VP13DCocktailChannel.h"

QStringList VP13DCocktailPlugin_VP1AutoFactory::channelWidgetsProvided() const
{
  return QStringList()
        << "3DCocktail"
         ;
}

IVP1ChannelWidget * VP13DCocktailPlugin_VP1AutoFactory::getChannelWidget(const QString & channelwidget)
{
  if (channelwidget == "3DCocktail")
    return new VP13DCocktailChannel();

  return 0;
}

