# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = EventLoopAlgs
PACKAGE_PRELOAD  = 
PACKAGE_CXXFLAGS = 
PACKAGE_OBJFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = 
PACKAGE_DEP = EventLoop MultiDraw
PACKAGE_TRYDEP   = xAODEventInfo
PACKAGE_CLEAN    = 
PACKAGE_PEDANTIC = 1
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 0

include $(ROOTCOREDIR)/Makefile-common
