!
!> add a new MDT/CSC hit in the xTUBHI arrays
!
 SUBROUTINE ATUBHI(Ident,IC0,IW0,IP0,ZZZ,DDD,RRR,SSS,JJJ,Iquali)
 USE M_MB_Digis
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: Ident, IC0, IW0, IP0, JJJ, Iquali
 REAL(8), INTENT(IN) :: ZZZ, DDD, RRR, SSS
!
   IF( SIZE(JTUBHI) < NTUBHT+1 ) CALL Push_MB_Digis_NTUBMA
!
   NTUBHT = NTUBHT + 1
   ZTUBHI(NTUBHT) = ZZZ
   DTUBHI(NTUBHT) = DDD
   RTUBHI(NTUBHT) = RRR
   STUBHI(NTUBHT) = SSS
   ITUBHI(NTUBHT) = Ident
   JTUBHI(NTUBHT) = JJJ
   IF( JJJ == 0 ) JTUBHI(NTUBHT) = 66
   KTUBHI(NTUBHT) = IC0*10000 + IW0*10 + IP0
   LTUBHI(NTUBHT) = Iquali
!
 END SUBROUTINE ATUBHI
!
