!
 SUBROUTINE ATUEND
 USE M_MB_Digis
 USE M_MB_MuGeom, ONLY : NCOUCH
 IMPLICIT NONE
 REAL(8), ALLOCATABLE :: XTEMP(:)
 INTEGER, ALLOCATABLE :: ITEMP(:),NORDR(:)
 INTEGER :: IT, ICODE, IC, IW, IP
! protection contre evts vides (crash sur OSF) : pourrait etre fait plus tot
   IF( NTUBHT <= 0 )  RETURN
!
   ALLOCATE( XTEMP(NTUBHT) )
   ALLOCATE( ITEMP(NTUBHT) )
   ALLOCATE( NORDR(NTUBHT) )
!
   CALL KROISS(KTUBHI,NTUBHT,NORDR)
!
   XTEMP(:) = ZTUBHI(1:NTUBHT)
   ITEMP(:) = KTUBHI(1:NTUBHT)
   ZTUBHI(1:NTUBHT) = XTEMP(NORDR(:))
   KTUBHI(1:NTUBHT) = ITEMP(NORDR(:))
!
   XTEMP(:) = DTUBHI(1:NTUBHT)
   ITEMP(:) = JTUBHI(1:NTUBHT)
   DTUBHI(1:NTUBHT) = XTEMP(NORDR(:))
   JTUBHI(1:NTUBHT) = ITEMP(NORDR(:))
!
   XTEMP(:) = RTUBHI(1:NTUBHT)
   ITEMP(:) = ITUBHI(1:NTUBHT)
   RTUBHI(1:NTUBHT) = XTEMP(NORDR(:))
   ITUBHI(1:NTUBHT) = ITEMP(NORDR(:))
!
   XTEMP(:) = STUBHI(1:NTUBHT)
   ITEMP(:) = LTUBHI(1:NTUBHT)
   STUBHI(1:NTUBHT) = XTEMP(NORDR(:))
   LTUBHI(1:NTUBHT) = ITEMP(NORDR(:))
!
   DEALLOCATE( XTEMP )
   DEALLOCATE( ITEMP )
   DEALLOCATE( NORDR )
!
   ICODE  = 0
   NTUBHM = -1
   DO IT=1,NTUBHT
     IF( KTUBHI(IT) == ICODE ) THEN
       NTUBHI(IC,IW,IP) = NTUBHI(IC,IW,IP) + 1
     ELSE
       ICODE = KTUBHI(IT)
       IC =  ICODE / 10000
       IW = (ICODE - IC*10000) / 10
       IP =  ICODE - IC*10000 - IW*10
       NTUBH0(IC,IW,IP) = IT - 1
       NTUBHI(IC,IW,IP) = 1
       IF( NTUBHM < 0 .AND. IC > NCOUCH ) NTUBHM = IT - 1
     ENDIF
   ENDDO
   IF( NTUBHM < 0 ) NTUBHM = NTUBHT
!
 END SUBROUTINE ATUEND
!
