!
!> \author M.Virchaux
!
 REAL(8) FUNCTION Chi2_Fixe(L)
 USE M_MB_PACONS
 USE M_MB_Fit
 IMPLICIT None
 INTEGER, INTENT(IN) :: L
 REAL(8) :: XDENOM
!
   XDENOM = NZFIXE(L,1,1) + NZFIXE(L,2,1) + NSFIXE(L,1,1)*FacSZ + NSFIXE(L,2,1)*FacSZ - 1.D0
   XDENOM = MAX( XDENOM , 1.D0 )
   Chi2_Fixe = ( DZFIXE(L,1,1) + DZFIXE(L,2,1) + DSFIXE(L,1,1) + DSFIXE(L,2,1)) / XDENOM
!
 END FUNCTION Chi2_Fixe
!
