!
!> Get  :  VDEB(1 to 8)
!> From :  VPERIGEE(1 to 5)
!> \author M.Virchaux
!
 SUBROUTINE GIVDEB3(IVDEB)
 USE M_MB_Fit
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: IVDEB
 REAL(8) :: SINPHI, COSPHI, COTTHE, PTINV, VDEB456, VDEB456inv 
!
   SINPHI  = SIN(VPERIGEE(3))
   COSPHI  = COS(VPERIGEE(3))
   COTTHE  = VPERIGEE(4)
   PTINV   = VPERIGEE(5)
   VDEB456 = SQRT( 1.d0 + COTTHE**2 )
   VDEB456inv = 1.d0 / VDEB456
!
   VDEB(1,IVDEB) =  VPERIGEE(1) * SINPHI
   VDEB(2,IVDEB) = -VPERIGEE(1) * COSPHI
   VDEB(3,IVDEB) =  VPERIGEE(2)
   VDEB(4,IVDEB) = COSPHI * VDEB456inv
   VDEB(5,IVDEB) = SINPHI * VDEB456inv
   VDEB(6,IVDEB) = COTTHE * VDEB456inv
   VDEB(7,IVDEB) = VDEB456 / ABS(PTINV)
   VDEB(8,IVDEB) = SIGN( 1.d0, PTINV )
!
 END SUBROUTINE GIVDEB3
!
