!
!> Get  :  VDEB(1 to 8)
!> From :  VTHETAPHI(1 to 5) , RCHAMI,ZCHAMI
!> \author M.Virchaux
!
 SUBROUTINE GIVDEB2(IVDEB)
 USE M_MB_Fit
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: IVDEB
 REAL(8) :: TANXT, XZ, ASMU
!
   TANXT = TAN( VTHETAPHI(1) )
   XZ = RCHAMI / TANXT
   IF( ABS(XZ) <= ZCHAMI ) THEN
     VDEB(1,IVDEB) = RCHAMI * COS( VTHETAPHI(2) )
     VDEB(2,IVDEB) = RCHAMI * SIN( VTHETAPHI(2) )
     VDEB(3,IVDEB) = XZ
   ELSEIF( XZ > 0.D0 ) THEN
     VDEB(1,IVDEB) = ZCHAMI * TANXT * COS( VTHETAPHI(2) )
     VDEB(2,IVDEB) = ZCHAMI * TANXT * SIN( VTHETAPHI(2) )
     VDEB(3,IVDEB) = ZCHAMI
   ELSE
     VDEB(1,IVDEB) = - ZCHAMI * TANXT * COS( VTHETAPHI(2) )
     VDEB(2,IVDEB) = - ZCHAMI * TANXT * SIN( VTHETAPHI(2) )
     VDEB(3,IVDEB) = - ZCHAMI
   ENDIF
   VDEB(4,IVDEB) = SIN( VTHETAPHI(3) ) * COS( VTHETAPHI(4) )
   VDEB(5,IVDEB) = SIN( VTHETAPHI(3) ) * SIN( VTHETAPHI(4) )
   VDEB(6,IVDEB) = COS( VTHETAPHI(3) )
   ASMU = MAX( ABS(VTHETAPHI(5)), 0.000000001d0 )
   VDEB(7,IVDEB) = 1.d0 / ASMU
   VDEB(8,IVDEB) = SIGN( 1.d0, VTHETAPHI(5) )
!
 END SUBROUTINE GIVDEB2
!
