!
!> \author M.Virchaux
!
 INTEGER FUNCTION IWDRATfun(ID,J,ISC)
 USE M_MB_CODRAT
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: ID,J,ISC
!
   IF( IWcross(ISC,1)+IWcross(ISC,2) < 1 ) THEN
     IWDRATfun = IWDRAT(ID,J,ISC)
   ELSE
     IWDRATfun = IWcross(ISC,J)
   ENDIF
!
 END FUNCTION IWDRATfun
!
