!
!> \author M.Virchaux
!
 LOGICAL FUNCTION L_ISC_SEED(ISC)
 USE M_MB_PACONS
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: ISC
 INTEGER :: IS
!
   L_ISC_SEED = .FALSE.
   DO IS=1,NSEARC
     IF( ISC == ISCEMI(1,IS) .OR. ISC == ISCEMI(2,IS) ) THEN
       L_ISC_SEED = .TRUE.
       RETURN
     ENDIF
   ENDDO
!
 END FUNCTION L_ISC_SEED
!
