!
!> \author M.Virchaux   08/10/96
!
 SUBROUTINE LOJTUB(N,ICC,IWW,JLTUB, JFLAG)
 USE M_MB_Digis
 IMPLICIT NONE
 INTEGER :: N, ICC(*), IWW(*), JLTUB(*), JFLAG(*)
 INTEGER :: J, IP, ITDEB, ITFIN
!
   DO J=1,N
     DO IP=1,JLTUB(J)
       ITDEB = NTUBH0(ICC(J),IWW(J),IP) + 1
       ITFIN = NTUBH0(ICC(J),IWW(J),IP) + NTUBHI(ICC(J),IWW(J),IP)
       KTUBHI(ITDEB:ITFIN) = JFLAG(ITDEB:ITFIN)
     ENDDO
   ENDDO
!
 END SUBROUTINE LOJTUB
!
