!
!> \author M.Virchaux
!
 PURE LOGICAL FUNCTION LOKROA(TTT,FFF,NROA,TROA,FROA,DTROA,DFROA)
 USE M_MB_General_CONSTANTS, ONLY : TwoPi
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: NROA
 REAL(8), INTENT(IN) :: TTT, FFF
 REAL(8), INTENT(IN) :: TROA(*), FROA(*), DTROA(*), DFROA(*)
 INTEGER :: J
 REAL(8) :: THEDIF, PHIDIF
!
   LOKROA = .TRUE.
   IF( NROA <= 0 ) RETURN
   DO J=1,NROA
     THEDIF = ABS( TTT - TROA(J) )
     PHIDIF = ABS( FFF - FROA(J) )
     PHIDIF = MIN( PHIDIF , ABS(PHIDIF-TwoPi) )
     IF( THEDIF < DTROA(J) .AND. PHIDIF < DFROA(J) ) RETURN
   ENDDO
   LOKROA = .FALSE.
!
 END FUNCTION LOKROA
!
