!
!> Reorder the crossing planes before calling trabaz
!
 SUBROUTINE ReorderPlanes(NNNPLA)
 USE M_MB_CTRABAZ
 IMPLICIT NONE
 INTEGER, INTENT(IN) :: NNNPLA
 INTEGER :: IORD(NNNPLA), I, J
!
   CALL CROISS( TT0PLA, NNNPLA, IORD)  
   DO I=1,NNNPLA
     J = IORD(I)
     ZTTPLA(I,1) = TT0PLA(J)
     ZTTPLA(I,2) = CF0PLA(J)
     ZTTPLA(I,3) = SF0PLA(J)
     ZTTPLA(I,4) = CA0PLA(J)
     ZTTPLA(I,5) = SA0PLA(J)
     ICRPLA(I)   = ICCPLA(J)
   ENDDO
   TT0PLA(1:NNNPLA) = ZTTPLA(1:NNNPLA,1)
   CF0PLA(1:NNNPLA) = ZTTPLA(1:NNNPLA,2)
   SF0PLA(1:NNNPLA) = ZTTPLA(1:NNNPLA,3)
   CA0PLA(1:NNNPLA) = ZTTPLA(1:NNNPLA,4)
   SA0PLA(1:NNNPLA) = ZTTPLA(1:NNNPLA,5)
   ICCPLA(1:NNNPLA) = ICRPLA(1:NNNPLA)
!
   FORALL (I=1:NNNPLA) ICRPLA(I) = INDPLA(IORD(I))
   INDPLA(1:NNNPLA) = ICRPLA(1:NNNPLA)
   FORALL (I=1:NNNPLA) ICRPLA(I) = JNDPLA(IORD(I))
   JNDPLA(1:NNNPLA) = ICRPLA(1:NNNPLA)
!
 END SUBROUTINE ReorderPlanes
!
