!
!> Get VPERIGEE(1 to 5) from VFIN(1 to 8)
!> \author M.Virchaux
!
 SUBROUTINE TKVFIN3
 USE M_MB_Fit
 IMPLICIT NONE
 REAL(8) :: R2FIN, RVFIN, PHIFIN
!
   R2FIN = SQRT( VFIN(1)**2 + VFIN(2)**2 )
   RVFIN = SQRT( VFIN(4)**2 + VFIN(5)**2 )
   PHIFIN = ATAN2( VFIN(5) , VFIN(4) )
   VPERIGEE(1) = SIGN( R2FIN , VFIN(1)*PHIFIN )
   VPERIGEE(2) = VFIN(3)
   VPERIGEE(3) = PHIFIN
   VPERIGEE(4) = VFIN(6) / RVFIN
   VPERIGEE(5) = VFIN(8) / VFIN(7) / RVFIN
!
 END SUBROUTINE TKVFIN3
!
