!
!> Get VTHETAPHI(1 to 5) from VFIN(1 to 8)
!> \author M.Virchaux
!
 SUBROUTINE TKVFIN2
 USE M_MB_Fit
 IMPLICIT NONE
 REAL(8) :: R2FIN, RVFIN
!
   R2FIN = SQRT( VFIN(1)**2 + VFIN(2)**2 )
   RVFIN = SQRT( VFIN(4)**2 + VFIN(5)**2 )
   VTHETAPHI(1) = ATAN2(  R2FIN  , VFIN(3) )
   VTHETAPHI(2) = ATAN2( VFIN(2) , VFIN(1) )
   VTHETAPHI(3) = ATAN2(  RVFIN  , VFIN(6) )
   VTHETAPHI(4) = ATAN2( VFIN(5) , VFIN(4) )
   VTHETAPHI(5) = VFIN(8) / VFIN(7)
!
 END SUBROUTINE TKVFIN2
!
