!
!> \author M.Virchaux   08/10/96
!
 SUBROUTINE UNJTUB(N,ICC,IWW,JLTUB, JFLAG)
 USE M_MB_Digis
 IMPLICIT NONE
 INTEGER, INTENT(IN)  :: N, ICC(*), IWW(*), JLTUB(*)
 INTEGER, INTENT(OUT) :: JFLAG(*)
 INTEGER :: J, IP, ITDEB, ITFIN
!
   DO J=1,N
     DO IP=1,JLTUB(J)
       ITDEB = NTUBH0(ICC(J),IWW(J),IP) + 1
       ITFIN = NTUBH0(ICC(J),IWW(J),IP) + NTUBHI(ICC(J),IWW(J),IP)
       JFLAG(ITDEB:ITFIN) = KTUBHI(ITDEB:ITFIN)
     ENDDO
   ENDDO
!
 END SUBROUTINE UNJTUB
!
