# Copyright (C) 2002-2022 CERN for the benefit of the ATLAS collaboration

from AthenaCommon.CfgGetter import addService

addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getPhysicsListSvc","PhysicsListSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getReducedStepSizeUserLimitsSvc","ReducedStepSizeUserLimitsSvc")

addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getDetectorGeometrySvc","DetectorGeometrySvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getG4AtlasSvc","G4AtlasSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getG4GeometryNotifierSvc","G4GeometryNotifierSvc")

addService("G4AtlasServices.G4AtlasUserActionConfigLegacy.getUserActionSvc","G4UA::UserActionSvc")
addService("G4AtlasServices.G4AtlasUserActionConfigLegacy.getISFUserActionSvc","G4UA::ISFUserActionSvc")
addService("G4AtlasServices.G4AtlasUserActionConfigLegacy.getISFFullUserActionSvc","G4UA::ISFFullUserActionSvc")
addService("G4AtlasServices.G4AtlasUserActionConfigLegacy.getISFPassBackUserActionSvc","G4UA::ISFPassBackUserActionSvc")
addService("G4AtlasServices.G4AtlasUserActionConfigLegacy.getISF_AFIIUserActionSvc","G4UA::ISF_AFIIUserActionSvc")
addService("G4AtlasServices.G4AtlasUserActionConfigLegacy.getCTBUserActionSvc","G4UA::CTBUserActionSvc")

addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getStandardFieldSvc","StandardField")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getForwardFieldSvc","ForwardField")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ1FwdG4FieldSvc", "Q1FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ2FwdG4FieldSvc", "Q2FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ3FwdG4FieldSvc", "Q3FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getD1FwdG4FieldSvc", "D1FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getD2FwdG4FieldSvc", "D2FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ4FwdG4FieldSvc", "Q4FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ5FwdG4FieldSvc", "Q5FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ6FwdG4FieldSvc", "Q6FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ7FwdG4FieldSvc", "Q7FwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ1HKickFwdG4FieldSvc", "Q1HKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ1VKickFwdG4FieldSvc", "Q1VKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ2HKickFwdG4FieldSvc", "Q2HKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ2VKickFwdG4FieldSvc", "Q2VKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ3HKickFwdG4FieldSvc", "Q3HKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ3VKickFwdG4FieldSvc", "Q3VKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ4VKickAFwdG4FieldSvc", "Q4VKickAFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ4HKickFwdG4FieldSvc", "Q4HKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ4VKickBFwdG4FieldSvc", "Q4VKickBFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ5HKickFwdG4FieldSvc", "Q5HKickFwdG4FieldSvc")
addService("G4AtlasServices.G4AtlasServicesConfigLegacy.getQ6VKickFwdG4FieldSvc", "Q6VKickFwdG4FieldSvc")
